### ISSUE TITLE
how to check if a session is running with `-n`

### ISSUE THREAD

**Issue by DetachHead** [pytest-dev/pytest-xdist#1011]
i'm developing a plugin that needs to behave differently if the session is running with xdist. i tried doing this:
```py
def pytest_collection(session):
    if session.config.option.numprocesses:
        ...
```
then running `pytest -n 1`, but `numprocesses` returns `None` inside the subprocess started by xdist. i assume becausse the pytest-xdist options do not propagate to the subprocesses.

is there a way i can detect whether a session is in a subprocess started by pytest-xdist?

**Comment by RonnyPfannschmidt** [comment]
https://pytest-xdist.readthedocs.io/en/stable/how-to.html#identifying-the-worker-process-during-a-test

**Comment by DetachHead** [comment]
thanks!
