### ISSUE TITLE
`--looponfail` is incompatible with certain editable installs

### ISSUE THREAD

**Issue by jeremy-hiatt** [pytest-dev/pytest-xdist#1028]
Certain editable installs (those that use a custom finder) fail to import due to path modifications made to support `looponfail`.

`setuptools` supports a few different modes of editable installs; for one of these, it will insert [dummy entries](https://github.com/pypa/setuptools/blob/8c45d6e445a8ca5f5a1fd724a80a5c418fe36780/setuptools/command/editable_wheel.py#L845) into `sys.path` of the form `{package_name}.__path_hook__` and register a corresponding `path_hook` that will be invoked by the import machinery.

Meanwhile, `looponfail` has some logic to [rewrite](https://github.com/pytest-dev/pytest-xdist/blob/f57c65839bccedd4f9fcad4c24d778d3fb3f8c2a/src/xdist/looponfail.py#L161-L166) `sys.path` to resolve any non-absolute paths. Unfortunately this ends up mangling the path entries inserted to support editable installs, and breaks their import.

It's not clear why the path rewrite code exists in `looponfail`; can anyone comment on whether it's still needed? If not, then the simplest possible fix would be to simply remove it. Alternatively the code could specifically avoid modifying entries which appear to be path hooks.

**Comment by jeremy-hiatt** [comment]
One thing to add: a previous version of the `looponfail` code had a call to `os.chdir()`, but that wasn't preserved when the code was moved in [this commit](https://github.com/pytest-dev/pytest-xdist/commit/e03f6d76b6ffe066fafc12ea30c69dc45cfaee6d#diff-ca5c9b9e8b66699fc3ece16d40043939c8d3aa023789bf9f0bfb75c7b15960abL78). Perhaps it's simply not necessary to maintain the path manipulation logic?

**Comment by RonnyPfannschmidt** [comment]
The plan is to drop looponfail as soom as a last failed/stepwise based reimplementation is done

**Comment by jeremy-hiatt** [comment]
Hi @RonnyPfannschmidt , thanks for the reply. I understand this is a deprecated feature. However I would submit the following:
* the replacement option, as I understand it, is not yet available for users to switch to
* this is a bug that affects users of the existing feature
* there appears to be a simple fix, especially if the choice is to drop the path manipulation
* if the new implementation borrows code from the existing, it would be advantageous to have all easily-addressable bugs already fixed so they are not inadvertently replicated

I hope you agree that there's value in fixing this bug. I am happy to iterate on the linked PR if you have concerns.

**Comment by RonnyPfannschmidt** [comment]
The PR looks good, let's go ahead with it

**Comment by jeremy-hiatt** [comment]
Thanks for merging @RonnyPfannschmidt ! Any plans for when the next release would come out?

**Comment by nicoddemus** [comment]
I can't speak for @RonnyPfannschmidt, but I would guess we will get a new release once #1027 gets merged, which depends on a new `execnet` release.

**Comment by RonnyPfannschmidt** [comment]
I'm pretty swamped with personal life ATM

I hope to be able to get back to this mid next week
