### ISSUE TITLE
Unable to run pytest-xdist with pytest-bdd, getting DumpError

### ISSUE THREAD

**Issue by AmirYa412** [pytest-dev/pytest-xdist#1038]
I am using in my pytest-bdd project(**Python 3.7.3** | MacOS Sonoma) the following packages:

```
pytest                      7.4.3     
pytest-bdd               6.1.1    
pytest-xdist             3.5.0     

```
when trying to run my pytest-bdd project in paralle using pytest-xdistl I get the following error:

```
INTERNALERROR> E                 raise DumpError(f"can't serialize {tp}")
INTERNALERROR> E             execnet.gateway_base.DumpError: can't serialize <class 'pytest_bdd.parser.Step'>
INTERNALERROR> E           assert False
```

Any workaround suggestion is appreciated, currently using pytest-parallel as I have no choice but is no longer supported and new issues are surfacing as I'm moving forward with my project.

**Comment by RonnyPfannschmidt** [comment]
Pytest-bdd Lacks a report serialize/deserialize Hook to handle its data

This is a pytest-bdd issue

**Comment by AmirYa412** [comment]
@RonnyPfannschmidt thanks for your answer, closing the issue.
