### ISSUE TITLE
Avoid spawning worker node processes unnecessarily 

### ISSUE THREAD

**Issue by argos83** [pytest-dev/pytest-xdist#104]
Hi! I have configured my project to automatically set a value of `-n` based on the number of available CPUs in the host where the tests are being run. Also, the SUT is started with a level of resources proportional to the value of `-n` so it can handle the load properly. The higher the number of resources required by the SUT the longer it takes to start (and the higher the monetary cost is, since these resources are AWS stuff).
This usually pays off really well, and thanks to xdist I've managed to reduce considerably the time it takes to run the whole test suite.

However when somebody wants to run a subset of tests, based on filters like `-k foo`, even if only 2 or 3 tests match the filter, xdist will still spawn all of the `-n` processes unnecessarily. And it will usually take longer to run with xdist than without (because of the SUT startup time)

I tried to find, with no luck, an appropriate pytest hook that kicks in after the tests have been collected but before xdist creates the worker nodes, so I can set `numprocesses = min(numprocesses, tests_collected)` and set up the SUT with the appropriate amount of resources. But it seems all the tests are collected after the worker nodes are spawned (and they are collected in every single node?).

I hope I made myself clear. Any clues on how can this be solved?

Thanks!

**Comment by RonnyPfannschmidt** [comment]
xdist starts processes *before* collection - currently there is not even a baseline support for enabling this feature

**Comment by nicoddemus** [comment]
I think we can close this, we would have to overhaul how como xdist work internally in order to support it.
