### ISSUE TITLE
Requirement py>=1.4.22 is too low

### ISSUE THREAD

**Issue by jayvdb** [pytest-dev/pytest-xdist#105]
`setup.py` requires `py>=1.4.22` , and `pytest>=2.7.0`, however [pytest 2.7.0 setup.py](https://github.com/pytest-dev/pytest/blob/d2a8866/setup.py#L21) requires `py>=1.4.25`.

This causes problems as pip resolutions is not very good.
If someone installs `pytest-xdist` & `pytest` 2.7.0 together in that order, pip will use `py>=1.4.22` and ignore `py>=1.4.25`.  You can see that at https://travis-ci.org/jayvdb/my-ci-test/jobs/187902155

All is well if pytest-xdist bumps the requirement up to  `py>=1.4.25`, and someone wants to install pytest 2.7.0 : See https://travis-ci.org/jayvdb/my-ci-test/builds/187901866 , which fakes that situation by first intalling `py==1.4.25`

However it fails again if someone wants to use the latest `pytest` , as it [requires py>=1.4.29`](https://github.com/pytest-dev/pytest/blob/3f5edc7/setup.py#L51).  See https://travis-ci.org/jayvdb/my-ci-test/jobs/187913569#L241

**Comment by jayvdb** [comment]
Note : pip does not have a dependency resolver : https://github.com/pypa/pip/issues/988 ; it needs our help..

**Comment by RonnyPfannschmidt** [comment]
Up for doing a PR?

**Comment by jayvdb** [comment]
Sure, but do you want the incomplete solution of bumping up to `py==1.4.25` , or `py>=1.4.29`.
The latter has been tested; see https://travis-ci.org/jayvdb/pytest-xdist/builds/188018807 .

**Comment by jayvdb** [comment]
This is now much worse, as the `setup.py` now requires `pytest>=3.0.0`, and the latest pytest requires `py>=1.4.33`.

The result is it is especially difficult to depend on `pytest-xdist` with a pre-existing `pytest`, such as using the default `pytest` provided by Travis.
See https://github.com/mementoweb/py-memento-client/issues/13 for some major problems caused on Travis Python 2.7 and Python 3.4 environment.
