### ISSUE TITLE
pytest: error: unrecognized arguments: -n

### ISSUE THREAD

**Issue by skybird2022** [pytest-dev/pytest-xdist#1074]
Hi Teams,

When I run pytest -k test_login -n 3 in terminal of Pycharm, there is error message. Before I run,  already installed  pytest-xdist in Pycharm. Could you pls kindly advise how to fix this error ? Thanks 

F:\Pycharm\interfaceAuto>pytest -k test_login -n 3
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
  inifile: F:\Pycharm\interfaceAuto\pytest.ini
  rootdir: F:\Pycharm\interfaceAuto

**Comment by RonnyPfannschmidt** [comment]
Where is pytest- and where is python

This looks like a botched installation 

Please provide details on pytest/python and the installation locations

**Comment by skybird2022** [comment]
Hi Ronny, 

Installation & version for your information. 
 
Pytest (Version: 8.1.1) location : G:\Python\Scripts\pytest.exe & G:\anaconda3\Scripts\pytest.exe
Python (Version: 3.8.8)  location : G:\Python\python.exe &  G:\anaconda3\python.exe
Pytest-xdist(Version: 3.5.0) location: G:\Python\Lib\site-packages

**Comment by RonnyPfannschmidt** [comment]
The path env var decides which pytest will be used it seems like you started the pytest without accompanying xdist

**Comment by skybird2022** [comment]
Good afternoon Ronny, 

I try to uninstall high version pytest (8.1.1) & pytest-xdist(3.5.0), re-install lower version for pytest (7.4.0) & pytest-xdist(3.3.1) in same locations & env var.  Run agian -n params, it's workable.  Around 1 hour later, I uninstall again, and install back latest version, it's workable now, so magical.  Anyway, thanks for your swift response ! Confirm code is running successfully, ticket will be closed.
