### ISSUE TITLE
 worker_internal_error - can someone help me creating a good bug report?

### ISSUE THREAD

**Issue by andreabisello** [pytest-dev/pytest-xdist#1093]
Hi
i have a big testsuite, 4 years of evolution, more than 1000 test, so i use pytest-xdist to speed up execution.
Since the beginning, randomly, xdist were crashing.
Now i would like to understand better what's happening in order to help the development of this awesome plugin.
The problem is that i don't know exacly what to say, neither how to reproduce, because is random.
so i'm asking help to create this "is not working" in an actionable action. thanks for support.

that the situation on a full update windows 11

> platform win32 -- Python 3.11.6, pytest-7.4.4, pluggy-1.3.0
> Suite di test dei webservices
> rootdir: C:\ec4a9867-4d56\qa-lsd-webservices
> configfile: pytest.ini
> plugins: allure-pytest-2.13.2, anyio-4.3.0, flaky-3.7.0, base-url-2.0.0, custom-exit-code-0.3.0, html-4.0.2, metadata-3.0.0, playwright-0.5.0, testconfig-0.2.0, timeout-2.2.0, xdist-3.6.1
> timeout: 900.0s
> timeout method: thread
> timeout func_only: False
> 6 workers [1231 items] skipped
> scheduling tests via LoadGroupScheduling
> 

I was using pytest-xdist 3.3.1 but obtaining crashes I have updated to pytest-xdist 3.6.1 obtaing, the same, crashes.

as you can see after some minutes one of the worker crashes, then another, then execution finished

> 
> [gw4] [  6%] PASSED test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://test-eu-ro1-msg-api.namirialarchive.com/messages/messages.svc]
> test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://test-eu-ro1-msg-api.namirialarchive.com/messages/remoteclientbasic.svc]
> test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://test-eu-ro1-rpt-api.namirialarchive.com/reporting/]
> [gw2] [  6%] PASSED test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://test-eu-ro1-msg-api.namirialarchive.com/messages/remoteclientbasic.svc]
> test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://test-eu-ro1-ws-lta.namirialarchive.com/service/repositoryservice.svc]
> [gw4] [  6%] PASSED test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://test-eu-ro1-rpt-api.namirialarchive.com/reporting/]
> test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://test-eu-ro1-api.namirialarchive.com/swagger/index.html]
> INTERNALERROR> def worker_internal_error(
> INTERNALERROR>         self, node: WorkerController, formatted_error: str
> INTERNALERROR>     ) -> None:
> INTERNALERROR>         """
> INTERNALERROR>         pytest_internalerror() was called on the worker.
> INTERNALERROR>
> INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
> INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
> INTERNALERROR>         here ourselves using the formatted message.
> INTERNALERROR>         """
> INTERNALERROR>         self._active_nodes.remove(node)
> INTERNALERROR>         try:
> INTERNALERROR> >           assert False, formatted_error
> INTERNALERROR> E           AssertionError: Traceback (most recent call last):
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\_pytest\main.py", line 271, in wrap_session
> INTERNALERROR> E                 session.exitstatus = doit(config, session) or 0
> INTERNALERROR> E                                      ^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\_pytest\main.py", line 325, in _main
> INTERNALERROR> E                 config.hook.pytest_runtestloop(session=session)
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_hooks.py", line 493, in __call__
> INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
> INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
> INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
> INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_callers.py", line 152, in _multicall
> INTERNALERROR> E                 return outcome.get_result()
> INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_result.py", line 114, in get_result
> INTERNALERROR> E                 raise exc.with_traceback(exc.__traceback__)
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_callers.py", line 77, in _multicall
> INTERNALERROR> E                 res = hook_impl.function(*args)
> INTERNALERROR> E                       ^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\xdist\remote.py", line 174, in pytest_runtestloop
> INTERNALERROR> E                 self.run_one_test()
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\xdist\remote.py", line 195, in run_one_test
> INTERNALERROR> E                 self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_hooks.py", line 493, in __call__
> INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
> INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
> INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
> INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_callers.py", line 152, in _multicall
> INTERNALERROR> E                 return outcome.get_result()
> INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_result.py", line 114, in get_result
> INTERNALERROR> E                 raise exc.with_traceback(exc.__traceback__)
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_callers.py", line 77, in _multicall
> INTERNALERROR> E                 res = hook_impl.function(*args)
> INTERNALERROR> E                       ^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\flaky\flaky_pytest_plugin.py", line 94, in pytest_runtest_protocol
> INTERNALERROR> E                 self.runner.pytest_runtest_protocol(item, nextitem)
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\_pytest\runner.py", line 114, in pytest_runtest_protocol
> INTERNALERROR> E                 runtestprotocol(item, nextitem=nextitem)
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\_pytest\runner.py", line 133, in runtestprotocol
> INTERNALERROR> E                 reports.append(call_and_report(item, "call", log))
> INTERNALERROR> E                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\flaky\flaky_pytest_plugin.py", line 141, in call_and_report
> INTERNALERROR> E                 report = hook.pytest_runtest_makereport(item=item, call=call)
> INTERNALERROR> E                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_hooks.py", line 493, in __call__
> INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
> INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
> INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
> INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_callers.py", line 130, in _multicall
> INTERNALERROR> E                 teardown[0].send(outcome)
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\_pytest\skipping.py", line 266, in pytest_runtest_makereport
> INTERNALERROR> E                 rep = outcome.get_result()
> INTERNALERROR> E                       ^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_result.py", line 114, in get_result
> INTERNALERROR> E                 raise exc.with_traceback(exc.__traceback__)
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\pluggy\_callers.py", line 77, in _multicall
> INTERNALERROR> E                 res = hook_impl.function(*args)
> INTERNALERROR> E                       ^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\ec4a9867-4d56\qa-lsd-webservices\conftest.py", line 125, in pytest_runtest_makereport
> INTERNALERROR> E                 screenshot = a_page.screenshot(type='png', full_page=True)
> INTERNALERROR> E                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\playwright\sync_api\_generated.py", line 10042, in screenshot
> INTERNALERROR> E                 self._sync(
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\playwright\_impl\_sync_base.py", line 109, in _sync
> INTERNALERROR> E                 return task.result()
> INTERNALERROR> E                        ^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\playwright\_impl\_page.py", line 655, in screenshot
> INTERNALERROR> E                 encoded_binary = await self._channel.send("screenshot", params)
> INTERNALERROR> E                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 61, in send
> INTERNALERROR> E                 return await self._connection.wrap_api_call(
> INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 490, in wrap_api_call
> INTERNALERROR> E                 return await cb()
> INTERNALERROR> E                        ^^^^^^^^^^
> INTERNALERROR> E               File "C:\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 99, in inner_send
> INTERNALERROR> E                 result = next(iter(done)).result()
> INTERNALERROR> E                          ^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR> E             playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
> INTERNALERROR> E             =========================== logs ===========================
> INTERNALERROR> E             taking page screenshot
> INTERNALERROR> E             ============================================================
> INTERNALERROR> E           assert False
> INTERNALERROR>
> INTERNALERROR> C:\Python311\Lib\site-packages\xdist\dsession.py:232: AssertionError
> [gw2] [  6%] PASSED test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://test-eu-ro1-ws-lta.namirialarchive.com/service/repositoryservice.svc]
> test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://test-eu-ro1-lta.namirialarchive.com/swagger/index.html]
> [gw4] [  6%] PASSED test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://test-eu-ro1-api.namirialarchive.com/swagger/index.html]
> test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://eu-ro1-app.namirialarchive.com/client/login.aspx]
> 
> [gw2] [  6%] PASSED test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://test-eu-ro1-lta.namirialarchive.com/swagger/index.html]
> test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://eu-ro1-ws-api.namirialarchive.com/service/service_main.asmx]
> [gw4] [  6%] PASSED test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://eu-ro1-app.namirialarchive.com/client/login.aspx]
> test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://eu-ro1-ws-api.namirialarchive.com/service/service_designer.asmx]
> [gw2] [  6%] PASSED test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://eu-ro1-ws-api.namirialarchive.com/service/service_main.asmx]
> test/test_api/test_endpoints.py::test_endpoints_parametrizzato[https://eu-ro1-ws-api.namirialarchive.com/service/service_fax.asmx]
> INTERNALERROR> Traceback (most recent call last):
> INTERNALERROR>   File "C:\Python311\Lib\site-packages\_pytest\main.py", line 271, in wrap_session
> INTERNALERROR>     session.exitstatus = doit(config, session) or 0
> INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR>   File "C:\Python311\Lib\site-packages\_pytest\main.py", line 325, in _main
> INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
> INTERNALERROR>   File "C:\Python311\Lib\site-packages\pluggy\_hooks.py", line 493, in __call__
> INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
> INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR>   File "C:\Python311\Lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
> INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
> INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR>   File "C:\Python311\Lib\site-packages\pluggy\_callers.py", line 152, in _multicall
> INTERNALERROR>     return outcome.get_result()
> INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR>   File "C:\Python311\Lib\site-packages\pluggy\_result.py", line 114, in get_result
> INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
> INTERNALERROR>   File "C:\Python311\Lib\site-packages\pluggy\_callers.py", line 77, in _multicall
> INTERNALERROR>     res = hook_impl.function(*args)
> INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
> INTERNALERROR>   File "C:\Python311\Lib\site-packages\xdist\dsession.py", line 138, in pytest_runtestloop
> INTERNALERROR>     self.loop_once()
> INTERNALERROR>   File "C:\Python311\Lib\site-packages\xdist\dsession.py", line 163, in loop_once
> INTERNALERROR>     call(**kwargs)
> INTERNALERROR>   File "C:\Python311\Lib\site-packages\xdist\dsession.py", line 217, in worker_workerfinished
> INTERNALERROR>     assert not crashitem, (crashitem, node)
> INTERNALERROR> AssertionError: ('test/test_browser/test_user/test_megasearch/test_tipologie_SDC.py::TestWebpartMegaSearch::test_versa_in_una_tipologia_si_firma_si_marca_aspettati_un_file_si_firmato_si_marcato[chromium]', <WorkerController gw0>)
> INTERNALERROR> assert not 'test/test_browser/test_user/test_megasearch/test_tipologie_SDC.py::TestWebpartMegaSearch::test_versa_in_una_tipologia_si_firma_si_marca_aspettati_un_file_si_firmato_si_marcato[chromium]'
> 
> =============================== 64 passed, 25 skipped, 84 warnings in 521.66s (0:08:41) ===============================
> 

I cant really understand how to debug this to give information to make this issue actionable. Could someone help me please?

**Comment by RonnyPfannschmidt** [comment]
```
INTERNALERROR> E File "C:\ec4a9867-4d56\qa-lsd-webservices\conftest.py", line 125, in pytest_runtest_makereport
INTERNALERROR> E screenshot = a_page.screenshot(type='png', full_page=True)
```

it seems like the timeout isnt caught in your conftest - the makereport hook is not allowed to fail, please catch the exceptions

**Comment by andreabisello** [comment]
@RonnyPfannschmidt  REALLY thanks. i was thinking makereport would be executone ONCE at the END of everything so i was not expecting a problem there with a crash BEFORE the end of the execution. that means that every xdist worker execute makereport when its work is finished?

**Comment by andreabisello** [comment]
That was true. Solved. @RonnyPfannschmidt  i have not found a specific documentation about that kind of problems. maybe we could start a new section in the documentation as https://pytest-xdist.readthedocs.io/en/latest/crash.html "When Xdist crash"? what do you think?
