### ISSUE TITLE
Add support for threaded test execution

### ISSUE THREAD

**Issue by thedrow** [pytest-dev/pytest-xdist#11]
Threads will help speed up I/O intensive or calculation intensive test suites such as end to end tests that perform HTTP requests, invoke methods from with C extensions etc.
See https://github.com/sindresorhus/ava as a good example for the speed gain.

I discussed this with @RonnyPfannschmidt and it seems that it would require a lot of work and thread safety from pytest itself.
This can be provided as a third party provided that pytest-xdist will provide a public extension API.
pytest-cloud is an example of such extension but as far as I know there's no detailed documentation that explains how to do so.

**Comment by RonnyPfannschmidt** [comment]
for now i don't consider this an detail issue for xdist,
which is very much designed for dealing with multiple processes, and speed up both cpu intensive and io wait intensive tests that way

its more something i would consider extending xdist for after py.test itself can support multiple threads

**Comment by RonnyPfannschmidt** [comment]
closing this as out of scope for xdist itself

**Comment by thedrow** [comment]
@RonnyPfannschmidt Should I open an issue on py.test itself for threads support?

**Comment by RonnyPfannschmidt** [comment]
Up to you
