### ISSUE TITLE
pytest xdist abruptly exits with exit code 0 when running on Github Actions

### ISSUE THREAD

**Issue by genesis-jamin** [pytest-dev/pytest-xdist#1106]
We're seeing this strange issue where pytest xdist will abruptly exit with code 0 on Github Actions (self-hosted on k8s), which causes the CI run to be marked as success even though not all the tests ran. 

I've tried enabling a variety of debug / logging flags but I nothing ever gets printed before the exit. The lack of any output is making this difficult to debug. Has anyone seen this before? 

We've seen it exit at multiple points in the test run:
* Before test collection
* During test collection
* During `pytest_sessionstart`
* During test execution

The behavior is always the same -- nothing gets printed, and it returns with exit code 0.

**Comment by RonnyPfannschmidt** [comment]
Does you executors handle all k8s signals

I observed this on gitlab runners on k8s before

**Comment by genesis-jamin** [comment]
I'm going to close this issue because we've been able to show that pytest is not the problem here. We're almost certain it's because of Github's actions runners controller, and those are tracked in separate issues here:
* https://github.com/actions/actions-runner-controller/issues/3578
* https://github.com/actions/runner-container-hooks/issues/165
