### ISSUE TITLE
exitfirst should mark all unrun tests as "failed" for the purpose of last-failed and friends

### ISSUE THREAD

**Issue by xmo-odoo** [pytest-dev/pytest-xdist#1111]
`--exitfirst` and `--last-failed` work fine with xdist. Sadly stepwise doesn't (#458).

One might think that stepwise could be emulated by running with both exitfirst and last-failed, however it looks like exitfirst does not consider any of the yet-to-run tests "failed", as a result last-failed will run only the test which actually failed, instead of resuming from where it stopped.

**Comment by RonnyPfannschmidt** [comment]
Step wise needs a explicit xdist integration, reporting wrong Data to shoehorn it into running will just create more trouble

**Comment by RonnyPfannschmidt** [comment]
I regularly use the combination of lastfailed and exit first to iteratively cull broken tests after internally breaking changes,

The suggestion would break that

**Comment by RonnyPfannschmidt** [comment]
Yes, that is the intent, the goal being to chip away one failing test at a time until it does the next more complete rerun
