### ISSUE TITLE
Timeout with xdist

### ISSUE THREAD

**Issue by Peque** [pytest-dev/pytest-xdist#117]
I am hitting [this issue](https://bitbucket.org/pytest-dev/pytest-timeout/issues/8/internalerror-valueerror-signal-only-works) when using `pytest-xdist` in combination with `pytest-timeout`. They can actually work together using the `--timeout-method=thread` option for `pytest-timeout` but, in that case, the test suite gets stuck forever anyway and there is no actual information about which test timed-out.

I wonder if there is anything that could be done in the `pytest-xdist` side to allow setting a timeout for running tests (if the test does not finish, then stop/kill it and report an error without making the test suite hang forever).

**Comment by RonnyPfannschmidt** [comment]
ypi can either depend on a much older execnet version, the intoduction of green thread support in execnet broken this

this is not per se a bug in xdist, and it could be elevated by completely reimplementing how test distribution works

**Comment by Peque** [comment]
@RonnyPfannschmidt Yes, I know it is not *per se* a bug in `xdist`, just wanted to know if maybe something could be done in this side or if that would make sense.

**Comment by peterzahemszky** [comment]
I think this ticket and https://github.com/pytest-dev/pytest-xdist/issues/631 are duplicates. The issue has been fixed by `pytest-timeout` version 2.0.0: https://github.com/pytest-dev/pytest-timeout/commit/1a35f94298c1260500907bd674b75cf59df0c949

**Comment by nicoddemus** [comment]
Thanks @peterzahemszky
