### ISSUE TITLE
track remote worker id as part of test reports to help disambiguate

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest-xdist#118]
followup to pytest-dev/pytest#2236

currently we have the possibility that when the same test runs at different nodes and fails, we get an ambiguous race condition for the prior mentioned pr that cleans up a misbehavior in normal execution just fine

**Comment by nicoddemus** [comment]
Just to clarify, does this mean adding a new `worker_id` attribute to report objects?

**Comment by RonnyPfannschmidt** [comment]
Yes

**Comment by nicoddemus** [comment]
Fixed by #120
