### ISSUE TITLE
Any way to set test case timeouts?

### ISSUE THREAD

**Issue by Daenyth** [pytest-dev/pytest-xdist#123]
I'd like to specify something like `py.test tests/ -n auto --test-case-timeout=90s` so that any single test case that takes over 90s is automatically killed and marked as a failure. Is this possible?

**Comment by RonnyPfannschmidt** [comment]
pytest-xdist is not all all about test timeouts - plugins like pytest-timeout are, however they are not currently compatible with xdist + recent execnet

**Comment by Daenyth** [comment]
So there's no way to do this currently with xdist enabled?

**Comment by nicoddemus** [comment]
That depends... we use pytest-xdist and pytest-timeout just fine. What is your use case which is not covered?

**Comment by Daenyth** [comment]
I didn't know about pytest-timeout before. I was just going off the above where it says `plugins like pytest-timeout are, however they are not currently compatible with xdist`
