### ISSUE TITLE
ETA on xdist release 

### ISSUE THREAD

**Issue by akhileshk** [pytest-dev/pytest-xdist#137]
Is there any ETA when next release is planned for xdist, which include this (https://github.com/pytest-dev/pytest-xdist/pull/89 ) feature? We are planning to use this custom scheduling feature in our project. Also is this the right forum to ask this kind of question or there is any other forum for this?

**Comment by nicoddemus** [comment]
Hi @akhileshk, this is the right forum, thanks for the ping!

I think we can make a release right away. @RonnyPfannschmidt what do you think? It should be just a matter of pushing a new tag IIRC.

**Comment by RonnyPfannschmidt** [comment]
Yup, I'm about to leave for a easter travel, so either Monday or someone else goes ahead

**Comment by akhileshk** [comment]
Hi @RonnyPfannschmidt @nicoddemus, 
Looks like the new release tag has not yet been pushed. Can someone please do that?  
Thanks,

**Comment by nicoddemus** [comment]
Just pushed the tag, the new package should be available soon. Thanks for the ping! 👍

**Comment by nicoddemus** [comment]
It is now available: https://pypi.python.org/pypi/pytest-xdist 👍
