### ISSUE TITLE
changing node_id using pytest_xdist_setupnodes hook

### ISSUE THREAD

**Issue by akhileshk** [pytest-dev/pytest-xdist#143]
Hi Xdist contributor,

I am using following hooks to change/rename the node id  eg., gw0=>"xxx1", gw1=> "xxx2", I didn't use "tryfirst"  marker initially, which cause <INTERNALERROR> Key error(stack trace below). Once I used the "try first" marker it worked fine. 
I would like to know, If it is ok to rename the nodeid, and if this is the right way of renaming the nodeid? 

@pytest.hookimpl(tryfirst=True)
def pytest_xdist_setupnodes(config, specs):
    """ called before any remote node is set up. """
"""detail removed for brevity"""
   some condition 
       specs[0].id = "mantis1"
some condition
    specs[1].id = "mantis2"

///Stack trace

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/_pytest/main.py", line 96, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xdist/dsession.py", line 507, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xdist/slavemanage.py", line 64, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xdist/slavemanage.py", line 69, in setup_node
INTERNALERROR>     self.config.hook.pytest_xdist_newgateway(gateway=gw)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xdist/dsession.py", line 771, in pytest_xdist_newgateway
INTERNALERROR>     self.setstatus(gateway.spec, "C")
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xdist/dsession.py", line 741, in setstatus
INTERNALERROR>     self.rewrite(self.getstatus())
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xdist/dsession.py", line 745, in getstatus
INTERNALERROR>     for spec in self._specs]
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/xdist/dsession.py", line 745, in <listcomp>
INTERNALERROR>     for spec in self._specs]
INTERNALERROR> KeyError: 'mantis2'

**Comment by RonnyPfannschmidt** [comment]
in general the correct way to name nodes is to name them by using id=... and passing multiple name space

renaming them in the tryfirst is only working because the name was not yet used in any other way

**Comment by RonnyPfannschmidt** [comment]
im closing this one as it seems to be only a question, please correct me in case i misunderstood
