### ISSUE TITLE
Send complete report to mark_test_complete for custom schedulers

### ISSUE THREAD

**Issue by hdattada** [pytest-dev/pytest-xdist#145]
# Environment 
pytest-xdist: 1.16
Python version: 3.5
pytest: 3.0.7

# Issue
Current we are using custom scheduler for our framework and we have a requirement to decide on the next step after a test completes in `mark_test_complete`. Current `slave_testreport` only sends _item_index_ and _duration_ , I cannot find a way to find the test outcome in `mark_test_complete` method of my custom scheduler.

**Comment by RonnyPfannschmidt** [comment]
this actually works as intended, the schedulers themselves are not concerned with results
in order to map this, you'd need to integrate with the bits that handle collection and reports

it may be viable to make schedulers plugins

**Comment by hdattada** [comment]
Thanks @RonnyPfannschmidt I was able to use `pytest_runtest_logreport` to achieve whatever I was trying to
