### ISSUE TITLE
Question test discovery Plugin registration from master/slave

### ISSUE THREAD

**Issue by akhileshk** [pytest-dev/pytest-xdist#150]
We have a test discovery plugin for test which are not written in python, and we run those test using pytest and xdist. What we have noticed that if we register the plugin only from master then "pytest_collect_file" method on plugin does not get called, but if we register  the plugin from (each)slave then everything works as expected. I was wondering if this is expected behavior? 

is there way to know which hooks should be register only from master which from slave.  

```
def pytest_configure(config):
   """ if called from  slave return"""
    if hasattr(config, 'slaveinput'):
        return 
    my_plugign = MyPlugin(config)
    config.pluginmanager.register(my_plugign, 'my_plugign')
```

**Comment by RonnyPfannschmidt** [comment]
thats correct, the master never does collection - all collection happens on the slave processes 

a blog post showing an example for that is on https://holgerkrekel.net/2013/11/12/running-tests-against-multiple-devicesresources-in-parallel/
i believe this should be a help,

im leaving the issue open in case this doesnt solve your problem, please close the issue if this works out for you and ask more if it doesnt

**Comment by akhileshk** [comment]
Thanks @RonnyPfannschmidt, Since we already noticed this behavior you described. I wanted to make sure that this is the correct behavior, and not because we are doing something wrong.

**Comment by RonnyPfannschmidt** [comment]
thanks for the followup
