### ISSUE TITLE
pypi tarball contains __pycache__ directory

### ISSUE THREAD

**Issue by swt2c** [pytest-dev/pytest-xdist#161]
The tarball (for 1.17.1, for example) hosted on pypi contains a __pycache__ directory inside the testing directory.  This can cause problems when trying to run the tests, such as this:

```
_________________ ERROR collecting testing/test_looponfail.py __________________
import file mismatch:
imported module 'test_looponfail' has this __file__ attribute:
  /home/travis/build/pytest-dev/pytest-xdist/testing/test_looponfail.py
which is not the same as the test file we want to collect:
  /builddir/build/BUILD/pytest-xdist-1.17.1/testing/test_looponfail.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```

I can just remove the __pycache__ directory, but it would be helpful to just remove it from the tarball.

**Comment by nicoddemus** [comment]
Definitely, thanks for the report.

**Comment by nicoddemus** [comment]
I was about to open a PR with a fix for this by adding at the end of `MANIFEST.in`:

```
recursive-exclude *.pyc
```

And that did get rid of the `.pyc` files in the `testing` folder. 

But looking more into it, it seems the `MANIFEST.in` file is redundant. After removing `MANIFEST.in`, here's the contents of my `SOURCES.txt` after running `python setup.py sdist` (and make sure there's no `egg-info` and `dist` folders left over):

```
.gitignore
.travis.yml
CHANGELOG.rst
HOWTORELEASE.rst
ISSUES.txt
LICENSE
OVERVIEW.md
README.rst
appveyor.yml
dev-requirements.txt
pyproject.toml
setup.cfg
setup.py
tox.ini
.github/PULL_REQUEST_TEMPLATE.md
changelog/_template.rst
example/boxed.txt
pytest_xdist.egg-info/PKG-INFO
pytest_xdist.egg-info/SOURCES.txt
pytest_xdist.egg-info/dependency_links.txt
pytest_xdist.egg-info/entry_points.txt
pytest_xdist.egg-info/not-zip-safe
pytest_xdist.egg-info/requires.txt
pytest_xdist.egg-info/top_level.txt
testing/acceptance_test.py
testing/conftest.py
testing/test_boxed.py
testing/test_dsession.py
testing/test_looponfail.py
testing/test_newhooks.py
testing/test_plugin.py
testing/test_remote.py
testing/test_slavemanage.py
xdist/__init__.py
xdist/_version.py
xdist/boxed.py
xdist/dsession.py
xdist/looponfail.py
xdist/newhooks.py
xdist/plugin.py
xdist/remote.py
xdist/slavemanage.py
```

This list looks right to me. Am I missing something? @RonnyPfannschmidt any thoughts?

**Comment by RonnyPfannschmidt** [comment]
Looks good, setuptools-scm makes the file list

**Comment by nicoddemus** [comment]
You mean that it will automatically include the version controlled files into the sdist? That's brilliant, I didn't know that (there's no mention of it in the docs). 😁 

So in summary if one uses `setuptools_scm` one doesn't need a `MANIFEST.in` file in general, correct?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus manifest excludes are sometimes nice, github/global ci metadata is not usefull for a sdist

**Comment by nicoddemus** [comment]
>  manifest excludes are sometimes nice, github/global ci metadata is not usefull for a sdist

Agreed, but IMHO not worth having to maintain a `MANIFEST.in` file and related linting like we do in pytest just because of those files. 😁 

I'm opening a PR in pytest doing the same in a few minutes.
