### ISSUE TITLE
Namespace intersection

### ISSUE THREAD

**Issue by ksantr** [pytest-dev/pytest-xdist#174]
I have multiple tests which I run in a concurrent mode (-n) with xdist plugin. Every test creates a personal helper object from a Helper class with specific settings. But finally attributes from different tests are mixed in objects. One test has attributes from another. test1 gets helper.test2_config.

```
from helper import Helper

def test1():
    helper = Helper(test1_config)
    assert helper.test()

def test2():
    helper = Helper(test2_config)
    assert helper.test()
```

**Comment by RonnyPfannschmidt** [comment]
with the amount of information given there is literally nothing we can do to help

**Comment by nicoddemus** [comment]
@ksantr if you post more information about what you are trying to do we might be able to help. From your example it is not really clear what you are trying to accomplish.

Regardless, there's no builtin support in `pytest-xdist` to explicitly exchange information between the different workers, so depending on how you are structuring things it might not be possible to do, but we might suggest other ways to deal with the same problem. Also, almost always making tests depend on one another is a bad idea and viewed as bad practice.
