### ISSUE TITLE
Different env variables in parallel mode

### ISSUE THREAD

**Issue by corporatepiyush** [pytest-dev/pytest-xdist#179]
Can I mention different environment variable(s) to different process ?

currently if I execute my test suite with following command it causes test cases to fail because they uses same database 

`py.test -n 2 tests`

what i like to do is 

ENV_PROCESS_1=databaserUrl1 ENV_PROCESS_2=databaseUrl2 py.test -n 2 tests

**Comment by RonnyPfannschmidt** [comment]
`pytest --dist=load --tx popen//env:DATABASE_URL=... --tx popen//env:DATABASE_URL=...` is the canonical way

you can also do your own lookup based on the node name in the slaveinput

**Comment by corporatepiyush** [comment]
thanks.
`--dist=load` sends or distribute test functions Is there a  way to distribute test files instead ?

also how can we mention multiple env variables in arg `--tx popen//env:......`

**Comment by nicoddemus** [comment]
> thanks.
--dist=load sends or distribute test functions Is there a way to distribute test files instead ?

Take a look at the new `--dist=loadsuite` option, might be what you need. 👍 

About the environment variables, if your environment variables are predictable (`"localhost:5500"` for worker, `"localhost:5501"` for worker 1 and so on), you might consider building them at each node using the `worker_id` fixture:

```python
# conftest.py
@pytest.fixture(scope='session', autouse=True)
def setup_db_env_var(worker_id):
    os,environ['DATABASE_URL'] = get_db_url_from_worker_id(worker_id)
```

I'm closing this for now, feel free to follow up with more questions if you have them.
