### ISSUE TITLE
The --boxed option can fail to isolate tests with threads

### ISSUE THREAD

**Issue by emin63** [pytest-dev/pytest-xdist#188]
I believe that the --boxed option can fail for tests which spawn threads. I don't have a great demo of this bug but am experiencing this in my code:

  1. If I run `py.test --boxed /path/to/X /path/to/X` everything is fine because of the boxing.
  2. If I run `py.test /path/to/X /path/to/X` I get test failures due to lack of boxing and thread confusion.
  3. If I run `py.test --boxed .` in the top-level directory file X fails. 

Is it possible that the --boxed behavior is different if I explicitly specify the files vs run it on `.`?

I suspect that using `os.fork` is not truly providing test isolation because in some cases threads, locks, daemon threads, or some other thread stuff is leaking across the `os.fork` call.

It would be great if `--boxed` was implemented using the subprocess module to start a truly isolated process. This would also have the advantage of working on windows. 

My guess is that there are reasons that hasn't been done. So if boxing is going to continue to use fork, it would be great if there was a way to understand why test 1 above works while test 3 fails.

Thanks.

**Comment by RonnyPfannschmidt** [comment]
boxed got moved into a different project and is going to be phased out from xdist completely in future

**Comment by nicoddemus** [comment]
Should this be moved over to pytest-forked?

**Comment by RonnyPfannschmidt** [comment]
perhaps
