### ISSUE TITLE
Set an environment variable with current test 

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-xdist#189]
When executing tests in CI, sometimes a test may hang indefinitely. One can look at the output using `-v` but that might not always be reliable.

If each worker would set a specific environment variable with the test it is executing, one can use a process monitoring library like `psutil` to figure out which worker is running which test. This could be a variable named something like `PYTEST_XDIST_CURRENT_TEST` which is set to the test node id. Alternatively, we could also add if the test is in the `setup`, `call` or `teardown` phase.

The implementation should be trivial and can be really helpful when diagnosing CI problems.

@RonnyPfannschmidt what do you think?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus this should go to core pytest, as its helpfull even for a non-xdist hang

**Comment by nicoddemus** [comment]
Hmm good point. Will create an issue there.

**Comment by nicoddemus** [comment]
Closed in favor of pytest-dev/pytest#2583
