### ISSUE TITLE
How xdist according to the test file allocation process？

### ISSUE THREAD

**Issue by linlin547** [pytest-dev/pytest-xdist#193]
Hello, my English is very poor, I want to use xdist allocation process, not according to the distribution of the test method,  Need a process distribution a test file, what should I do?Thank you very much.

**Comment by RonnyPfannschmidt** [comment]
with your question, i dont see a good way to answer since you didnt even remotely outline your use-case

your English skill is indeed a major communication blocker there

**Comment by linlin547** [comment]
How are you I want to use xdist plug-in distribution test files, a process to distribute a test file, instead of distribution according to the amount of test method, what should I do?Thank you very much.

**Comment by RonnyPfannschmidt** [comment]
@linlin547 again, if i cant make sense of your question, i cant hope to help, if your own English is too bad please get help from someone with better English skills,

else i will have to close this issue as not actionable due to language barrier

**Comment by nicoddemus** [comment]
I'm going on a limb here, but perhaps @linlin547 means that he wants to distribute the tests to workers grouped by *test module* instead of by individual tests sent to each worker individually? @linlin547 can you confirm? If that's the case, there's #191 going on to fit exactly that.

**Comment by linlin547** [comment]
all methods execute in a same thread from a same file .

**Comment by linlin547** [comment]
execute tests group by class in a same thread @RonnyPfannschmidt @nicoddemus

**Comment by linlin547** [comment]
the same problem

https://stackoverflow.com/questions/36586422/pytest-distributed-testing-xdist-by-class

**Comment by nicoddemus** [comment]
Thanks for finding an example demonstrating your problem. As I said there's work regarding this on #191. I recommend to watch that issue closely. 👍 

Closing this for now.

**Comment by linlin547** [comment]
example : 
 1.I have three test files, they are test1,test2,test3
 2.now pytest.ini addopts= -n 3
 3.I hope thread1 run test1 file,thread2 run test2 file,thread3 run test3 file

@RonnyPfannschmidt @nicoddemus

**Comment by nicoddemus** [comment]
Yep it's clear now. 

The short answer is: that can't be done right now, but there's work being done in #191.
