### ISSUE TITLE
errors on traceback reassembly

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest-xdist#196]
https://gist.github.com/mandeep/eff732745239fee016063215b1cb170c

**Comment by zzzeek** [comment]
getting this also with 1.18.2

**Comment by zzzeek** [comment]
is there a workaround for this issue?   It is a complete blocker for being able to use pytest-xdist the same as #175 was - no test can fail without crashing the CI job.

For now I've pinned to arbitrary versions from a few months ago pytest<=3.0.7 pytest-xdist<=1.16.0.

**Comment by nicoddemus** [comment]
Hi @zzzeek unfortunately not at the moment. 😢 

I think this was introduced in 1.18.0 by #133.

**Comment by nicoddemus** [comment]
A reproducer would be great btw

**Comment by zzzeek** [comment]
easy enough, run this:

```
$ git clone -b reproduce_pytest_196 https://bitbucket.org/zzzeek/alembic
$ cd alembic/
$ tox -e py27-sqla10-sqlite -- tests/test_postgresql.py

```

it blows up in the teardown but that's caused by the 'reprfuncargs' key error prior.

**Comment by nicoddemus** [comment]
Thanks @zzzeek, that's very helpful. I will see if I can take a look at this over the weekend. 👍
