### ISSUE TITLE
Change --max-worker-restart option to a sensible value

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-xdist#226]
The default value allows for infinite restarts, but this is a serious problem for suites which are during collection because the test run never finishes.

We should change the default to a sensible number, [@RonnyPfannschmidt suggested](https://github.com/pytest-dev/pytest-xdist/issues/131#issuecomment-323336651) 4 times the number of nodes as default. A value of `0` would mean the previous behavior.

**Comment by timj** [comment]
I strongly endorse this. We use C++ python modules and sometimes there is a SEGV and it took us a while to understand why we ended up with locked up machines forking processes until the machine begged for mercy. It's highly unlikely that in our case a restart would ever be the right thing to do.

**Comment by blueyed** [comment]
@timj 
Care to create a PR for this?
