### ISSUE TITLE
Pypi has outdated links to repo/issue tracker (needs updating from bitbucket to github)

### ISSUE THREAD

**Issue by jeffwidman** [pytest-dev/pytest-xdist#23]
https://pypi.python.org/pypi/pytest-xdist

'Homepage' lists bitbucket repo

'Issuetracker' section lists bitbucket

**Comment by nicoddemus** [comment]
Ouch, thanks for reporting this! :sweat_smile:

**Comment by nicoddemus** [comment]
Fixed, thanks again!
