### ISSUE TITLE
Stop using master/slave terminology

### ISSUE THREAD

**Issue by timj** [pytest-dev/pytest-xdist#234]
Can xdist please stop using the master/slave terminology? Would you accept a PR changing "slave" to "worker"? The terminology is upsetting to some people (and I've already had complaints where I work) and there is no reason to use it when other words exist that do not offend people. Words do matter.

**Comment by nicoddemus** [comment]
> Can xdist please stop using the master/slave terminology? 

Definitely, we have already decided to use master/workers instead. Checkout the [`OVERVIEW`](https://github.com/pytest-dev/pytest-xdist/blob/master/OVERVIEW.md) for example.

> The terminology is upsetting to some people (and I've already had complaints where I work) and there is no reason to use it when other words exist that do not offend people. Words do matter.

I understand, and I'm sure it was not the intention at all when it was written. I completely agree and understand why some people are offended by it. We did not however took the time yet to go over the code base changing the terminology.

> Would you accept a PR changing "slave" to "worker"?

Definitely! Internally we can rename everything without any problem, but for flags (`max-slave-restart` for example) we should change to `max-workers-restart` but leave the old name in the code as to not break things (even if undocumented).

**Comment by RonnyPfannschmidt** [comment]
This code is around since more than 12 years,
back then that was common terminology,

recent enhancements in understanding humans make a adoption of better names an important social responsibility, 

However simple renaming isnt going to cut it as we need to preserve backward compatibility

Fortunately recent additions are already using the more respectful terminology

**Comment by timj** [comment]
Are there public APIs that have "slave" in the name or are you talking about the command line options? (those would need to hang around as duplicates).

**Comment by RonnyPfannschmidt** [comment]
For example `slaveinput` there is likely more

**Comment by RonnyPfannschmidt** [comment]
I cant take a closer look until next week, im on a houseboat somewhere random atm

**Comment by nicoddemus** [comment]
> For example slaveinput there is likely more

@timj that's a `dict` which is inserted into the `pytestconfig` object in a worker process.

This can be probably changed to `workerinput` and a `slaveinput` added as an alias.

But indeed we will have to decide on a case-by-case basis. But if you want to start the PR @timj feel free to, we can review the parts which use the public API and decide on case-by-case the proper solution to each.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt 

> im on a houseboat somewhere random atm

That's great! Enjoy your well deserved break! 😁 🍺

**Comment by feuillemorte** [comment]
Please, review:

https://github.com/pytest-dev/pytest-xdist/pull/268

**Comment by nicoddemus** [comment]
Closed by #268
