### ISSUE TITLE
provide a consistent looponfail story based on 3rd party tools

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-xdist#235]
Reported by @RonnyPfannschmidt in pytest-dev/pytest#1529

---

looponfail is more than just listening for file changes

also there are more and more tools upcoming that do this more propper and more responsive than what we had in place in xdist

so from my pov we should kill the builtin looponfail and have a well documented and easy to use story for it based on more extensive tools

**Comment by RonnyPfannschmidt** [comment]
Missplaced here, xdist will drop looponfail
