### ISSUE TITLE
Drop/reduce dependency on py?

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-xdist#246]
Should we strive to no longer explicitly depend on `py` in `pytest-xdist`? One thing in particular is `py.log`, which seems like it could/should be replaced by the standard `logging` module.

**Comment by RonnyPfannschmidt** [comment]
👍

**Comment by zmoon** [comment]
Seems like this is now an issue in [pytest 7.2](https://github.com/pytest-dev/pytest/releases/tag/7.2.0)

**Comment by nicoddemus** [comment]
This has been fixed in `3.0.2` actually, released a few hours ago.

**Comment by nicoddemus** [comment]
Fixed by https://github.com/pytest-dev/pytest-xdist/pull/821 and released in `3.0.2`.

**Comment by zmoon** [comment]
Ah ok great, thanks. I guess my timing was just bad, conda-forge hasn't noticed the new release yet and is still on v2.5.0.

**Comment by nicoddemus** [comment]
No worries. :+1:
