### ISSUE TITLE
dist=loadscope scheduling hangs on test class with only one test

### ISSUE THREAD

**Issue by DanaGoyette** [pytest-dev/pytest-xdist#257]
With pytest 3.2.3, when I tried using --dist=loadscope with two ssh nodes, the test framework simply hung without even trying to run any tests.  The same environment works fine with the other schedulers.

Part of the traceback (seems exactly the same as #230 ):
        while not self.session_finished:
>           self.loop_once()

The hang seems to occur when running a test class that has only one test function.
I eventually tracked down a simple change that seems to fix it: on the following line, expect only one item, not two:

https://github.com/pytest-dev/pytest-xdist/blob/master/xdist/remote.py#L62

I can't tell what the change might break, though.

**Comment by timj** [comment]
I wonder if #230 is triggering because the flake8 test only has one test in it. It looks like there is no end condition in that loop you mention if there is only one test to run.

**Comment by nicoddemus** [comment]
Hi @DanaGoyette, sorry for the delay. 

Your reasoning makes sense, but that loop running up until two items is correct; if there are no more tests on `master`, it should immediately send a `"shutdown"` event which will cause the remaining of the tests on all workers to finish:

https://github.com/pytest-dev/pytest-xdist/blob/17978f3beaa61f186752c5a080175a3b0a935630/xdist/remote.py#L61-L68

(If you are interested in the inner details, take a look at [OVERVIEW](https://github.com/pytest-dev/pytest-xdist/blob/master/OVERVIEW.md))

It is probably some condition on the master node which is causing it to not send the `"shutdown"` event at all. Unfortunately I'm out of time to investigate at the moment, but thought I would mention this in case others want to give it a try.

**Comment by DanaGoyette** [comment]
I'll have to try again at making a minimal reproduction case.  I seem to recall the issue happening when I was running a large suite of tests, and the very first test script had only a single test within its scope group.  The scheduler would send that single scope and test to the executor, and then wait forever for a status report that never arrived.

**Comment by DanaGoyette** [comment]
Okay, I've managed to reproduce it with a minimal test.  Create two files (say, test1.py and test2.py), each containing the following lines:

```
class TestWhatever(object):
    def test_whatever(self):
        pass
```

Now run py.test: 

pytest --tx=popen  test*.py  --debug --dist=loadscope -vv

```
scheduling tests via LoadScopeScheduling
[slavectl-gw0] sending command runtests(**{'indices': [0]})
[slave-gw0] received command runtests {'indices': [0]}
[slave-gw0] items to run: [0]
<hangs forever>
```

**Comment by DanaGoyette** [comment]
If I send SIGINT, the parent reports this:
```
run.venv/lib/python2.7/site-packages/pytest-3.2.3-py2.7.egg/_pytest/main.py:110: in wrap_session
    session.exitstatus = doit(config, session) or 0
run.venv/lib/python2.7/site-packages/pytest-3.2.3-py2.7.egg/_pytest/main.py:146: in _main
    config.hook.pytest_runtestloop(session=session)
run.venv/lib/python2.7/site-packages/pytest_xdist-1.20.1-py2.7.egg/xdist/dsession.py:114: in pytest_runtestloop
    self.loop_once()
run.venv/lib/python2.7/site-packages/pytest_xdist-1.20.1-py2.7.egg/xdist/dsession.py:128: in loop_once
    eventcall = self.queue.get(timeout=2.0)
[REDACTED]/lib/python2.7/Queue.py:177: in get
    self.not_empty.wait(remaining)
[REDACTED]/lib/python2.7/threading.py:359: in wait
    _sleep(delay)
E   KeyboardInterrupt
```

The slave / executor reports this:
```
run.venv/lib/python2.7/site-packages/pytest-3.2.3-py2.7.egg/_pytest/main.py:110: in wrap_session
    session.exitstatus = doit(config, session) or 0
run.venv/lib/python2.7/site-packages/pytest-3.2.3-py2.7.egg/_pytest/main.py:146: in _main
    config.hook.pytest_runtestloop(session=session)
<remote exec>:52: in pytest_runtestloop
    ???
<string>:732: in receive
    ???
[REDACTED]/lib/python2.7/Queue.py:168: in get
    self.not_empty.wait()
[REDACTED]/lib/python2.7/threading.py:340: in wait
    waiter.acquire()
E   KeyboardInterrupt
```

Note that [REDACTED] denotes where the python's source lives, outside the virtualenv.

**Comment by lmtierney** [comment]
I ran into this as well, and it does only happen at the beginning when all of the available nodes are assigned a scope that has only one test.

The initial scheduling assigns work here https://github.com/pytest-dev/pytest-xdist/blob/master/xdist/scheduler/loadscope.py#L381 which adds the work items from the first scope and issues the `runtests` command here https://github.com/pytest-dev/pytest-xdist/blob/master/xdist/scheduler/loadscope.py#L271.


So, if any of the nodes have `>= 2` items, that will trigger the run to actually kick off. But I believe this would also leave any nodes that still have only 1 to be stuck at 1 until the overall workqueue is down to 1 where the shutdown command would be sent (https://github.com/pytest-dev/pytest-xdist/blob/master/xdist/scheduler/loadscope.py#L384). Essentially this is giving all of the workload to the any nodes that started with `>=2`; with any starting with 1 stuck until all the work is gone.

Now, I don't know the *best* way to fix it. But the easiest is simply to put:

```
    for node in self.nodes:
        self._reschedule(node)
```

Right after the initial workload is assigned https://github.com/pytest-dev/pytest-xdist/blob/master/xdist/scheduler/loadscope.py#L382

We basically just need to ensure that each node has `>=2` during the initial scheduling. It could alternatively be put into an else off of the shutdown conditional (https://github.com/pytest-dev/pytest-xdist/blob/master/xdist/scheduler/loadscope.py#L384).

Thoughts @DanaGoyette, @nicoddemus, @carlos-jenkins?

**Comment by nicoddemus** [comment]
@lmtierney looks reasonable at first glance, would you like to try a PR?

**Comment by lmtierney** [comment]
I'll see what I can do

**Comment by nicoddemus** [comment]
Thanks! 👍
