### ISSUE TITLE
404 links in OVERVIEW.md

### ISSUE THREAD

**Issue by hugovk** [pytest-dev/pytest-xdist#258]
https://github.com/pytest-dev/pytest-xdist/blob/master/OVERVIEW.md links to:

> [execnet](http://codespeak.net/execnet/) and its [gateways](http://codespeak.net/execnet/basics.html#gateways-bootstrapping-python-interpreters)

Both of which are 404. codespeak.net is @hpk42's site.

The pages should be fixed on codespeak.net, the links switched to archived versions, or links removed.

(If fixed, these can be https as well.)

**Comment by hpk42** [comment]
fixed.
