### ISSUE TITLE
Error "Different tests were collected" when use generator in parametrize

### ISSUE THREAD

**Issue by feuillemorte** [pytest-dev/pytest-xdist#269]
This code
```
import pytest
import random


@pytest.mark.parametrize('number', [random.randint(1, 10)])
def test_one(number):
    print(number)
```
not working because of error:

```
____________________________________________________________________________________ ERROR collecting gw3 _____________________________________________________________________________________
Different tests were collected between gw1 and gw3. The difference is:
--- gw1

+++ gw3

@@ -1 +1 @@

-tests/test_one.py::test_one[5]
+tests/test_one.py::test_one[3]
====================================
```
For temporary solution you can use ids for fix this:
`@pytest.mark.parametrize('number', [random.randint(1, 10)], ids=['number'])`

Can it be fixed or it a feature of pytest?
Thank you!

**Comment by nicoddemus** [comment]
Hi @feuillemorte,

This is a limitation of the xdist architecture: collection must be deterministic throughout all slaves; IOW, they should always collect the exact same test ids.

**Comment by ArseniyAntonov** [comment]
It would be great if we will have the option to collect tests only on master, and then send them to the workers.

**Comment by nicoddemus** [comment]
Unfortunately that's not easy to achieve, please take a look at the FAQ at the bottom of https://github.com/pytest-dev/pytest-xdist/blob/master/OVERVIEW.md.

**Comment by ArseniyAntonov** [comment]
@nicoddemus, there are 2 possible situations: 
1) When we run tests on the same machine using x-dist
2) When we run tests on remote machines.

The first one seems not so hard as the second one. 
I and @feuillemorte may try to prepare a patch for the second one if you interested. 
And after it, we may discuss the second part.

**Comment by nicoddemus** [comment]
@ArseniyAntonov as stated in the FAQ, the problem with trying to make the master worker collect the tests is:

> The problem is that test items are not easily (impossible?) to serialize, as they contain references to the test functions, fixture managers, config objects, etc.

Do you guys have an idea how to overcome this problem?

**Comment by ArseniyAntonov** [comment]
I think we may use `pickle` for it. Have you tried it?

**Comment by RonnyPfannschmidt** [comment]
@ArseniyAntonov the problem is the state that connect the item deeper into pytest, not serializing just the item, its going to be tricky at best, this hasn't been tried since fixtures and setupstate got introduced

**Comment by ArseniyAntonov** [comment]
Oh, I got it. 
So looks like it's really almost impossible.
