### ISSUE TITLE
Retrieving the process id using worker_id

### ISSUE THREAD

**Issue by kunchamlokesh** [pytest-dev/pytest-xdist#280]
Hi,

I have issue related to worker_id. In our project while executing, mulit process will be launched and for every process username & password will be allocated randomly so due to this same credentials were assigned to multiple process., due to this we are facing collision issue.
We can solve this issue by allocating a static credentials to a process ie.

suppose we launched 4 process using pytest -n 4
now four process were launched named pw[0], pw[1], pw[2] & pw[3].

I would allocate user1 credentails to process1 and user2 credentials to process2 bsed on name that pw[0] & pw[1]

Here i am unable to retriever the name of the process . Can any please suggest me how to reterive them

By referring the above comments i have understood we can user worker_id to retrieve but can you please mention in detail

**Comment by nicoddemus** [comment]
Hi @kunchamlokesh,

The `worker_id` fixture or the `PYTEST_XDIST_WORKER` environment variable both can be used for that, so you can at any point in your program inspect `PYTEST_XDIST_WORKER` to get the worker name and map that to the appropriate user credentials.

Without more details on how do you actually use/get the credentials in the worker process I can't given more specific advice, but I think the above might be enough to get you started.

**Comment by kunchamlokesh** [comment]
Hi @nicoddemus 

Thanks for you reply

my credentials are initialized in conftest.py. 

I would like to execute my test from test.py. While test.py is executing it should retrieve the user credentials from conftest.py.

When multiple process are executing the test i've added a condition like

```
If(workerid=='gw0')
    return 'user1'
elsif(workerid=='gw1')
    return 'user2' ........

```
For retrieving the processed(ie.workerid) is created used a function

```
def reterive(pytestconfig):
        hasattr(pytestconfig, 'slaveinput')
        processid = pytestconfig.slaveinput['slaveid']
```
But when using the above method, it asked me to enter(pytestconfig:{slaveid})

Could you please suggest, how can i get processid without passing arguments/calling 'retrieve' function ??

**Comment by nicoddemus** [comment]
Hi @kunchamlokesh,

Sorry, I didn't quite get the overall problem from reading your message, some points are not clear:

> When multiple process are executing the test i've added a condition like

Where have you added these conditions?

> above function, it asked me to enter(pytestconfig:{slaveid})

I don't catch what you mean by ` it asked me to enter(pytestconfig:{slaveid})`, also how do you plan to call `retrieve`?

Note that `pytestconfig` is a *fixture*, so it can be accessed from *test functions* or other *fixtures*, but not from arbitrary functions which seems to be the case with `retrieve`.

**Comment by kunchamlokesh** [comment]
Hi @nicoddemus 

Thanks for info & your time. Issue has been solved

I got the worker_id by using the 'PYTEST_XDIST_WORKER'

**Comment by nicoddemus** [comment]
Glad you got it working, can we close this then?

**Comment by kunchamlokesh** [comment]
Yes you can close this ticket
