### ISSUE TITLE
pytest_unconfigure doesn't always complete on worker nodes

### ISSUE THREAD

**Issue by mikeage** [pytest-dev/pytest-xdist#282]
Hi,

It seems like pytest_unconfigure is called, but doesn't necessarily finish, on worker nodes.

Sample conftest.py:
```python
import time
import logging
logging.basicConfig(level=logging.DEBUG)

def pytest_unconfigure(config):
    if hasattr(config, 'workerinput'):
        logging.info("Unconfiguring worker; sleeping")
        time.sleep(20)
        logging.info("Done")
    else:
        logging.info("Unconfiguring master; not sleeping")
        logging.info("Done")
```

Output:
```
$ py.test -s -n 1
========================================================================================================================================================================== test session starts ==========================================================================================================================================================================
platform darwin -- Python 2.7.14, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /Users/mikemi/pytest_unconf_abort, inifile:
plugins: xdist-1.22.1, forked-0.2
gw0 [0]
scheduling tests via LoadScheduling
INFO:root:Unconfiguring worker; sleeping

===================================================================================================================================================================== no tests ran in 5.42 seconds ======================================================================================================================================================================
INFO:root:Unconfiguring master; not sleeping
INFO:root:Done
```

This is obviously just sample code, but I saw that a long running operation that I have in pytest_unconfigure sometimes didn't finish. Is there any way to make sure that the master blocks on all the workers' completions?

**Comment by RonnyPfannschmidt** [comment]
currently xdist has a default timeout of 10 seconds for workers to terminate on gateway shutdown (which is triggered on shutdown)

in order to handle complete unconfigure correctly we need to take a look at restructuring node shutdown

**Comment by mikeage** [comment]
Ok; I see the 10 second timeout, but it seems like it finishes faster. In my example code, the entire process finishes in <7 seconds; does the shutdown try to killing running processes?

Is there a different hook that would give me access to the `config` object that I could use to do something after all tests have finished?

**Comment by RonnyPfannschmidt** [comment]
please outline what you are trying to do

**Comment by mikeage** [comment]
Sure. I have code that sends the results of the tests to a reporting server somewhere. Currently, this code sits in pytest_unconfigure(), and runs on the workers in an xdist environment (I have some data stored on `config` that isn't sent back to the master node which is why each worker reports its own tests). 

Looking at the junitxml code, it seems like moving this to `pytest_sessionfinish()` might be better.

**Comment by RonnyPfannschmidt** [comment]
sessionfinish is suitable, xdist reports the worker completed in a sessionfinish hookwrapper currently (i believe we should move that to the unconfigure hook)

**Comment by mikeage** [comment]
Thanks! I'll try that.

**Comment by mikeage** [comment]
works!
