### ISSUE TITLE
[Help needed] xdist & Jenkins integration

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest-xdist#283]
Hi,

In the past, in my organization we have implemented some mechanism for parallelize with using Jenkins to split the work among the slaves (with using some java/Jmeter scripts).

Since I found out about pytest, we had switched to it and I'm happy to use it with xdist..

However, one of the things I'm missing is some integration with Jenkins to understand how to run parallel tasks from one of the Jenkins slaves to another.. (meaning, job trigger otherjobs with integration of pytest and xdist).

The way I see it, I can build a script with remote workers and let it run..
However, what will happen if jenkins will spawn a new job on this slave? how could we have an idea about it?

I got tons of questions about this process.. however, I believe that you folks handlede such integration and I will be happy to learn from it..

**Comment by RonnyPfannschmidt** [comment]
xdist is purely at the pytest level, its completely unaware of jenkins, im also not aware of anyone creating such a integration

**Comment by nicoddemus** [comment]
We use Jenkins at work with pytest-xdist quite sucessfull @Formartha, do you have any questions to ask?

**Comment by Formartha** [comment]
@RonnyPfannschmidt  - Thanks, that I understood.

@nicoddemus, 
My end goal was to make some job that fires up the regression testsuite and uses slaves to publish the report. running couple of suites on couple of slaves would be perfect match in terms of loading utilization & automation adjustment.
Could you share what is your setup looks like?

**Comment by Formartha** [comment]
@nicoddemus - That seems nice! how do you combine the JUnitXML report together? it looks somehow like I want to be able to build.

**Comment by nicoddemus** [comment]
> how do you combine the JUnitXML report together? it looks somehow like I want to be able to build.

We are running `pytest -n auto --junitxml=tests.xml` in a worker, and that contains the full test report, so in our case there's nothing required to put the report together.

**Comment by Formartha** [comment]
10x @nicoddemus 

Do we have an ability to parallel running to multiple workers?

**Comment by RonnyPfannschmidt** [comment]
@Formartha currently sdist has no mechanism/way to have another infrastructure start the worker processes after a setup so while you can use multiple machines, pytest-xdist has to be in control of the distribution of code and the starting of the workers

as far as i understood that would mismatch your needs

**Comment by Formartha** [comment]
Thanks @RonnyPfannschmidt.

So in order to solve my gap i will need to build a wrapper (test_runner) to grab all the workers I have and spread the work among them.. that's something I will be able to send to the community :)

**Comment by RonnyPfannschmidt** [comment]
off hand its not clear how to enable it from the xdist side

**Comment by Formartha** [comment]
well, agree. it might be on the project setup level (e.g. injecting the worker list based on some predefined logic).

Thanks

**Comment by nicoddemus** [comment]
Which only runs a subset of the tests on each worker, you can use the `pytest_collection_modifyitems` hook to selectively run some tests on each worker by some criteria.

OK @Formartha I think we can close this then. 👍
