### ISSUE TITLE
Running with custom marker support

### ISSUE THREAD

**Issue by Mr-F** [pytest-dev/pytest-xdist#290]
I'm hoping this is more a question rather than an issue/feature request.  I'm trying to run a specific set of tests across multiple cores.  Currently, without xdist I simply use pytest's custom marker selection option `-m` i.e.
```
py.test -m foo_bar ./tests/
```
This quite happily selects the tests marked with `foo_bar` and runs only those tests.  However, if I introduce the number of processes using `-n` i.e.
```
py.test -n 2 -m foo_bar ./tests/
```
It simply ignores that and runs them all.  Am I missing something or does using `-n` flag exclude the ability to use custom markers?

**Comment by Mr-F** [comment]
Sorry, please ignore this.  I updated the versions of PyTest and pytest-xdist and this all started to work correctly.  Sorry

**Comment by rchoksi-hw** [comment]
> Sorry, please ignore this. I updated the versions of PyTest and pytest-xdist and this all started to work correctly. Sorry

Even though I have the latest pytest(4.6.9) and pytest-xdist(1.32.0) versions, I still see the same issue. Could you please let me know which versions are you using?

**Comment by RonnyPfannschmidt** [comment]
Pytest 4 is outdated, and no longer under active maintenance
