### ISSUE TITLE
pytest_xdist_make_scheduler doesn't work if pytest is executed from ancestor folder

### ISSUE THREAD

**Issue by abotalov** [pytest-dev/pytest-xdist#291]
There is the following directory structure - `temp/src/tests`.  
`tests` folder contains `conftest.py` and `test_a.py` files:
```python
# conftest.py
from xdist.scheduler import LoadScopeScheduling

def pytest_xdist_make_scheduler(config, log):
  return LoadScopeScheduling(config, log)
```

```python
# test_a.py
def test_answer():
  assert 5 == 5
```

If I execute `pytest -n=2` from child `src` or `tests` folder, I see `scheduling tests via LoadScopeScheduling` in test output as expected.
But if I execute `pytest -n=2` from ancestor `temp` folder, I see **`scheduling tests via LoadScheduling`** in test output. I would expect pytest to discover `conftest.py` and see `LoadScopeScheduling`.

**Comment by RonnyPfannschmidt** [comment]
we can only consider initial conftests there, if your conftest is not a initial one its goign ti fail, please declare an actual pytest plugin

**Comment by abotalov** [comment]
But there's no `conftest.py` inside `temp` folder. And other hooks (when workers execute tests) seem to work.
Could you please explain why `conftest.py` inside `src/tests` is not considered?

**Comment by abotalov** [comment]
Ah, I see "Plugin discovery order at tool startup " at https://docs.pytest.org/en/latest/writing_plugins.html:
* if exists, load conftest.py and test*/conftest.py relative to the directory part of the first test path.
