### ISSUE TITLE
Question: run py.test+xdist from python

### ISSUE THREAD

**Issue by moleksyuk** [pytest-dev/pytest-xdist#292]
Hi,

Pytest provides ability to run tests from python [directly](https://docs.pytest.org/en/latest/usage.html#calling-pytest-from-python-code):

```python
pytest.main(['-x', 'mytestdir'])
```

But when I try to run it with `xdist`:
```python
pytest.main(["-d", "--tx", "'ssh=-i ec2-nano-key-pair.pem ubuntu@ec2.amazonaws.com//python=/usr/bin/python3.5'", "--rsyncdir", "mytestdir", "mytestdir"])
```
Getting error that xdist params are not recognized:
```
usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: -d --tx --rsyncdir mytestdir mytestdir
```

Also, when I tried to run:
```python
o = os.popen("py.test --help").read()
print(o)
``` 
It doesn't out section related to **xdist** (`distributed and subprocess testing`) but everything works from Terminal directly.

Does it require some additional configuration or it's impossible at all?

Thanks.

**Comment by RonnyPfannschmidt** [comment]
in order to use xdist it must be available in the python thats used for pytest

without more context i cant say anything about that (your issues seem to stem from the environment)

**Comment by moleksyuk** [comment]
@RonnyPfannschmidt Thanks 👍  You was right. The problem was in configuration that IntelliJ IDEA was using (venv vs osx python).
Works fine now.

**Comment by RonnyPfannschmidt** [comment]
@moleksyuk thanks for following up and describing the configuration issue you faced - it will help in future when people hit the same issue
