### ISSUE TITLE
better document that -s (capture=no) doesn't work with xdist

### ISSUE THREAD

**Issue by valignatev** [pytest-dev/pytest-xdist#296]
Hi, I want to print some info in stdout, so I use `-s` pytest option. It works fine unless I also use xdist with something like `-n 2`. In this case, logs got captured and I don't see anything.
Am I missing something?

**Comment by RonnyPfannschmidt** [comment]
-s doesn't work with xdist and gets disabled

**Comment by valignatev** [comment]
Thanks for the answer, probably this should be somewhere in the docs.
For now, I use this workaround in my test:
`assert False, 'Info I need'`

**Comment by valignatev** [comment]
What would be a good place to put it? Maybe the second entry in the FAQ section?

**Comment by RonnyPfannschmidt** [comment]
i think so

**Comment by valignatev** [comment]
Also, I've noticed that `-s` is used in examples: https://github.com/pytest-dev/pytest-xdist/blob/2c66187dd848e3a9b5d4baaa92bed6141443e8cf/example/loadscope/tox.ini#L11
And in tests: https://github.com/pytest-dev/pytest-xdist/blob/11e3599785607689586728c6bac14f328f6ef2e2/testing/acceptance_test.py#L406

Should we remove it or it's somehow intended (then it looks misleading)?

**Comment by Akuli** [comment]
Is there really no way to pass `--capture=no` to tests? It feels like a huge :-1: to me.
