### ISSUE TITLE
Final adjustments for finishing GitHub import

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-xdist#3]
Hooray for migrating the repository to GitHub! :balloon: 

I think there are a few steps to finish the migration though:

- [x] Change the README at BitBucket to point to the new repository location
- [ ] Disable issues and Wiki

**Comment by bubenkoff** [comment]
i'd leave issues enabled, and migrate xdist labeled issues from pytest here

**Comment by bubenkoff** [comment]
it's so strange to make a distinction for pytest-xdist plugin, why?
following the labeling logic, we need to create issues for all plugins right in the pytest repo, labeling them?

**Comment by nicoddemus** [comment]
> i'd leave issues enabled, and migrate xdist labeled issues from pytest here

Ideally this should have been the first thing to do because any problem that happens during the migration process (and believe me, they happen) will require the process to be restarted from the beginning, resulting in "stale" issues because GitHub does not allow issues to be deleted. In this case, the solution is to delete the repository and try again. Once you are satisfied on how the issues were migrated, you can continue with the rest of the migration process (code, links, etc). 

At least that was my experience with migrating `pytest` to GitHub.

> it's so strange to make a distinction for pytest-xdist plugin, why?

I think I read @hpk42 mentioning that it was difficult for users, when encountering a problem, to distinguish if a problem was actually a `pytest` or `pytest-xdist` issue, hence asking all issues to be posted in the same repository (I think it was in an email, but I can't find it right now). Perhaps this was an issue a few years back when `pytest-xdist` was new, and now it makes sense to ask users to post issues in `pytest-xdist` instead?

**Comment by RonnyPfannschmidt** [comment]
whats really needed is a propper multi-project bugtracker, but that seems next to impossible
