### ISSUE TITLE
'No module found' error

### ISSUE THREAD

**Issue by michaelbukachi** [pytest-dev/pytest-xdist#300]
Hello. I'm trying to run tests on a remote server but I'm getting a `No module found` error. I'm running pytests in a virtual env created using pipenv. Is it possible to have a setup before the tests that installs all the modules on the remote server ?

**Comment by RonnyPfannschmidt** [comment]
remote setup currently is not implemented that way, you need to provide the environment

**Comment by michaelbukachi** [comment]
Oh. Okay. How do I do that?

**Comment by RonnyPfannschmidt** [comment]
@michaelbukachi for example by creating it as a virtualenv on the remote and passing that virtualenv as the python parameter to the --tx

**Comment by michaelbukachi** [comment]
you mean something like this: `pytest --tx ssh=myremote//python=virtualenv` ?

**Comment by michaelbukachi** [comment]
Thanks. Got it.
