### ISSUE TITLE
Injecting settings changes into test nodes using hooks

### ISSUE THREAD

**Issue by westhomas** [pytest-dev/pytest-xdist#301]
I'm attempting to modify some basic settings within a manager class I maintain by using hooks.

This has been working great for a long time as long as I'm running without xdist. I import my settings class, make my changes and the changes are seen within my test methods. 

However, as soon as I attempt this same pattern using xdist hooks, this trick fails to work. The test nodes are unaware of my changes to the global scope.

Example:
```python
# test-settings-injection.py
import pytest

from settings import base as settings_base


# Tests
def test_foo():
    assert settings_base.settings.IMPORTANT_SETTING == 'parallel value'


def test_foo2():
    assert settings_base.settings.IMPORTANT_SETTING == 'parallel value'


@pytest.mark.serial
def test_bar():
    assert settings_base.settings.IMPORTANT_SETTING == 'serial value'


# Execute Tests
def main():
    class MyPlugin(object):
        def __init__(self):
            self.__name__ = 'myplugin'
            self.collected = set()

        def pytest_xdist_node_collection_finished(self, node, ids):
            self.collected.update(set(ids))

        def pytest_collection_modifyitems(self, items):
            for item in items:
                self.collected.update({item.nodeid})

        def pytest_configure(self, config):
            # mutate setting value
            from settings import base as settings_base
            settings_base.settings.IMPORTANT_SETTING = 'serial value'

        def pytest_testnodeready(self, node):
            # mutate setting value
            from settings import base as settings_base
            settings_base.settings.IMPORTANT_SETTING = 'parallel value'

    # this works
    myplugin = MyPlugin()
    pytest.main(['test-settings-injection.py', '-s', '-m', 'serial'], plugins=[myplugin])
    print('Serial Collected:', myplugin.collected)

    # this doesn't work
    myplugin = MyPlugin()
    pytest.main(['test-settings-injection.py', '-s', '-m', 'not serial', '-d', '--tx', '{}*popen//python=python3'.format(2), ], plugins=[myplugin])
    print('Parallel (threads) Collected:', myplugin.collected)

    # this doesn't work
    myplugin = MyPlugin()
    pytest.main(['test-settings-injection.py', '-s', '-m', 'not serial', '-n2', ], plugins=[myplugin])
    print('Parallel (CPUs) Collected:', myplugin.collected)


if __name__ == '__main__':
    main()
```

Is there anyway to do this sort of patching within the non-master test nodes?

Versions:
```
pytest==3.6.2
pytest-xdist==1.22.2
```

Test project here: https://github.com/westhomas/pytest-testapp
Run with `python test-settings-injection.py`

**Comment by westhomas** [comment]
After digging around in xdist sources and playing around with several alternative solutions, I guess I could shorten this question: 

Are there any hooks that are executed by the pytest *slave* process that would give me access to that memory space?

**Comment by RonnyPfannschmidt** [comment]
bascially if you make a custom plugin in a function that then calls pytest.main, you have lost

**Comment by westhomas** [comment]
I’ve lost… what?


On June 29, 2018 at 2:44:18 PM, Ronny Pfannschmidt (notifications@github.com)
wrote:

bascially if you make a custom plugin in a function that then calls
pytest.main, you have lost

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pytest-dev/pytest-xdist/issues/301#issuecomment-401455217>,
or mute the thread

**Comment by RonnyPfannschmidt** [comment]
any ability to work with those python objects from another process

**Comment by westhomas** [comment]
So are there no hooks that are run *on* or *by* the node itself? I need to execute some code early in the py.test lifecycle before any of my fixtures or tests are executed by the test nodes.

**Comment by RonnyPfannschmidt** [comment]
you can use the node/workerinput to pass data to a worker, and then use those as input for the fixtures

**Comment by westhomas** [comment]
I'm fine with using that, but my problem is that even using that pattern, I still need to apply those settings before my fixtures are instantiated due to some legacy code. Short of doing some massive refactoring to ditch that legacy code, I think there's two options:

1) Find some hook that runs *within* the worker node's scope that can access the `workerinput` settings in the config and then apply my settings OR

2) Find a way to access `pytestconfig` data without using a fixture so I can access it earlier in my legacy object's lifecycle.

**Comment by westhomas** [comment]
BTW, I've been able to make my original sample work. I can access the settings object, make changes, and then see those changes within the worker node's scope. However it doesn't seem to work in my actual implementation with my legacy objects. I'm still debugging why, but figured a working example would be helpful for posterity:

```python
import subprocess

import pytest

from utils import quiet
from settings import base as settings_base


# TODO: Add this to your conftest.py
# pytest_plugins = ["test_settings_injection",]


def pytest_sessionstart(session):
    from settings import base as settings_base
    if hasattr(session.config, 'workerinput'):
        settings_base.settings.IMPORTANT_SETTING = 'parallel value'
    else:
        settings_base.settings.IMPORTANT_SETTING = 'serial value'


# Tests
def test_foo():
    assert settings_base.settings.IMPORTANT_SETTING == 'parallel value'


def test_foo2():
    assert settings_base.settings.IMPORTANT_SETTING == 'parallel value'


@pytest.mark.serial
def test_bar():
    assert settings_base.settings.IMPORTANT_SETTING == 'serial value'


# Execute Tests
@quiet
def main():
    class MyPlugin(object):
        def __init__(self):
            self.__name__ = 'myplugin'
            self.collected = set()

        def pytest_xdist_node_collection_finished(self, node, ids):
            self.collected.update(set(ids))

        def pytest_collection_modifyitems(self, items):
            for item in items:
                self.collected.update({item.nodeid})

    # Run pytest inline with serial tests
    myplugin = MyPlugin()
    pytest.main(['test_settings_injection.py', '-s', '-m', 'serial'], plugins=[myplugin])
    print('Serial Collected:', myplugin.collected)

    # Run pytest inline with parallel tests
    myplugin = MyPlugin()
    pytest.main(['test_settings_injection.py', '-s', '-m', 'not serial', '-d', '--tx', '{}*popen//python=python3'.format(2), ], plugins=[myplugin])
    print('Parallel Collected:', myplugin.collected)

    # Run pytest subprocess with serial tests
    subprocess.check_call(['py.test', 'test_settings_injection.py', '-m', 'serial', ])

    # Run pytest subprocess with parallel tests
    subprocess.check_call(['py.test', 'test_settings_injection.py', '-m', 'not serial', '-d', '--tx', '{}*popen//python=python3'.format(2), ])


if __name__ == '__main__':
    main()
```
See https://github.com/westhomas/pytest-testapp/blob/master/test_settings_injection.py
Run with `python test_settings_injection.py`
