### ISSUE TITLE
using the pytest_sessionstart hook on each of the workers

### ISSUE THREAD

**Issue by shaicantor** [pytest-dev/pytest-xdist#303]
Hi,

I'm trying to write a plugin that uses pytest's 3rd party hooks, meaning, xdist hooks.
I'm trying to understand why the pytest_sessionstart hook is run only once, at the master and not on each worker node.
I saw the pytest-cov plugin that uses this hook for each worker node [here](https://github.com/pytest-dev/pytest-cov/blob/master/src/pytest_cov/plugin.py#L176).

What am I missing?

Thanks

**Comment by westhomas** [comment]
Attached to issue https://github.com/pytest-dev/pytest-xdist/issues/301 is a working sample that shows `pytest_sessionstart` running for master and each worker node. I had to play with it to get it to work, but once it was working it was simple and made sense.

See if that works for you too.

**Comment by nicoddemus** [comment]
Thanks @westhomas for the helpful reply. @shaicantor does that solve your issue, and if so can you close this? Thanks!

**Comment by shaicantor** [comment]
Thanks @westhomas for the sample.
I ended up using pytest-cov as a reference.
