### ISSUE TITLE
#9 is not fixed on PyPy

### ISSUE THREAD

**Issue by skirpichev** [pytest-dev/pytest-xdist#316]
See commit https://github.com/skirpichev/diofant/commit/cfe8a53e29207f6008af235cfc1c5b311e55e6ad,  which return ``-n auto`` and failing CI build: https://travis-ci.org/diofant/diofant/jobs/407725598

CC @greut

**Comment by greut** [comment]
_os.sched_getaffinity_ seems to be Python3 only, so it won't fix it for anything Python2-ish.

**Comment by skirpichev** [comment]
@greut, above build was on
```
$ python --version
Python 3.5.3 (3f6eaa010fce, Jan 11 2018, 04:44:35)
[PyPy 5.10.1 with GCC 6.2.0 20160901]
```
It's Python3-compatible version of PyPy.

**Comment by greut** [comment]
```
$ pypy3
Python 3.5.3 (fdd60ed87e941677e8ea11acf9f1819466521bf2, Jun 22 2018, 02:39:05)
[PyPy 6.0.0 with GCC 8.1.1 20180531] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import os
>>>> os.sched_getaffinity()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'sched_getaffinity'
```

**Comment by skirpichev** [comment]
CPython docs says "New in version 3.3", so, IIUIC it must be in PyPy3.  Sounds like PyPy3 bug.

psutils seems to be working, as it was suggested in related issue https://github.com/travis-ci/travis-ci/issues/4696#issuecomment-210275203:
```
In [1]: import psutil

In [2]: psutil.Process().cpu_affinity()
Out[2]: [0, 1]

In [3]: import sys

In [4]: sys.version
Out[4]: '3.5.3 (fdd60ed87e94, Apr 24 2018, 06:10:04)\n[PyPy 6.0.0 with GCC 6.2.0 20160901]'
```
Not sure if it worth adding additional deps.  You may want implement instead a hack for travis-ci, suggested in #9.

**Comment by nicoddemus** [comment]
I don't mind adding:

```
if os.environ.get('TRAVIS') == 'true':
    return 2
```

To our function that discovers the number of cpus when `auto` is given. It is a hack, but it is just 2 lines of code and will solve a real problem users have right now.

What do you think @RonnyPfannschmidt?

**Comment by RonnyPfannschmidt** [comment]
sounds okish as a hack 

can we factor the cpu number finding into a function and add a few unit/integration tests while we are on it

**Comment by nicoddemus** [comment]
Sure, sounds good.

Anybody would like to take this on? Seems like a quick contribution. I would be happy to review/merge this.

**Comment by skirpichev** [comment]
I'll do.  But first, I believe, pypy3 bug should be created.

Can you release a minor version after merge?

**Comment by greut** [comment]
@skirpichev  https://bitbucket.org/pypy/pypy/issues/2375/missing-posix-attributes-in-py3k

**Comment by nicoddemus** [comment]
> Can you release a minor version after merge?

Sure!
