### ISSUE TITLE
pytest>=3.4 requirement is not being resolved by pip

### ISSUE THREAD

**Issue by effigies** [pytest-dev/pytest-xdist#319]
We require `pytest>=3.0` and `pytest-xdist`. The latest `pytest-xdist` fails for `pytest<3.4`, but pip does not see it as a requirement, and so we get runtime failures for tests on Travis (which comes with pytest 3.3.0 installed).

**Comment by effigies** [comment]
For reference, here's a Travis log: https://travis-ci.org/nipy/nipype/jobs/408947071

**Comment by nicoddemus** [comment]
Thanks @effigies for writing,

Our `install_requires` seems correct:

https://github.com/pytest-dev/pytest-xdist/blob/b814db45cee0c0b7113df691068b6a4940f114c0/setup.py#L3

Unfortunately `pip`s dependency solver is known to have some problems. Not sure what we can do on our side to fix this.

**Comment by nicoddemus** [comment]
Note to self: do not change version requirements in bug fix versions btw.

**Comment by effigies** [comment]
Hmm. Okay. It looks like we're not upgrading our pip to the latest, so hopefully that resolves it. If not, we can just update our minimum version. 3.4 seems old enough.
