### ISSUE TITLE
rsync before running remote interpreter?

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-xdist#323]
I've tried using `--tx server//python=.venv/bin/python` to use the same `python` executable as locally, but this failed apparently due to the rsync not being done before the interpreter is run.

Would it be possible to do the syncing before, or is the interpreter itself used for this?

Another minor issue in this regard is that symlinks are synced as-is, but typically `python` is a symlink, and it would be good if symlinks could be resolved (optionally) when syncing (another issue, will create it if it makes sense).

**Comment by RonnyPfannschmidt** [comment]
basically there is no correct way to do this - resolving a python3 venv python to a executable before copying will completely break the env

xdist requires a working venv as a base to put more in

**Comment by blueyed** [comment]
Ok.

What about the original issue?  (syncing before running)
I assume that this could be useful in general.

**Comment by RonnyPfannschmidt** [comment]
@blueyed sync happens before collection, so thats already working as intended - see rsyncroots

**Comment by RonnyPfannschmidt** [comment]
execnet rsnc needs a running python program

**Comment by blueyed** [comment]
Ok, thanks.
