### ISSUE TITLE
Possibility to run parametrize tests within same worker

### ISSUE THREAD

**Issue by AndreySurzhan** [pytest-dev/pytest-xdist#324]
As QA I would like to be able to run parametrized pytest tests within same worker not load-balancing them across multiple workers.
**Meaning:** Nice to have `test_*.py` module that has one or many parametrized test function -> running that module using `xdist` should not lead to paralleling tests across multiple worker.

That will help me to run parametrized tests that might depend on other tests function within that module

Specific example:

**Actual behavior**

```
>pytest -n 2 --dist=loadfile 

#module test_a.py

@pytest.parametrize("data", params=["a1", "a2"])
 def test_a(data):
     pass

#module test_b.py

@pytest.parametrize("data", params=["b1", "b2"])
 def test_b(data):
     pass

> [gw1] PASSED test_a.py::test_a[a1]
> [gw0] PASSED test_a.py::test_a[a2]
> [gw1] PASSED test_b.py::test_b[b1]
> [gw0] PASSED test_b.py::test_b[b2]
```

**What I would expect using `--dist=loadfile`**
```
>pytest -n 2 --dist=loadfile 

#module test_a.py

@pytest.parametrize("data", params=["a1", "a2"])
 def test_a(data):
     pass

#module test_b.py

@pytest.parametrize("data", params=["b1", "b2"])
 def test_b(data):
     pass

> [gw0] PASSED test_a.py::test_a[a1]
> [gw0] PASSED test_a.py::test_a[a2]
> [gw1] PASSED test_b.py::test_b[b1]
> [gw1] PASSED test_b.py::test_b[b2]
```

*Related issues:*
https://github.com/pytest-dev/pytest-xdist/issues/58

*Example of the log of actual test run:*

![2018-07-31_16-28-58](https://user-images.githubusercontent.com/7816369/43488266-1a4b97f6-94e7-11e8-9c8e-0b6ce9629bcb.png)

**Comment by subha-py** [comment]
Any luck with this?

**Comment by Jongy** [comment]
@subha-py and @AndreySurzhan , you can check out #511 , I think what I've suggested there may be of help to you.

**Comment by ssbarnea** [comment]
Closing as the question is too old, uses syntax that no longer works and we already have a solution. That is not really a bug.
