### ISSUE TITLE
Possible optimization in Worker

### ISSUE THREAD

**Issue by wfaris** [pytest-dev/pytest-xdist#330]
In remote.py WorkerInteractor.pytest_collectreport the collectreport event is sent to the master which I believe handles this in dsession.py:worker_collectreport. It appears that this message is only meaningful if rep.failed is true. I am running pytest on a machine with 16 cpus on a very large test suite. The number of collectreport events actually causes the e2e time of running the test to be slower when using 16 cpus compared to using 8. When I pruned the number of collectreport events sent from workers to the master I was able to reduce the collection time from ~120 seconds to ~32 seconds.  Not sure what the priority of this should be but figured I would mention it,

**Comment by nicoddemus** [comment]
Opened #332 with your solution, thanks for taking the time to report this. 👍

**Comment by nicoddemus** [comment]
@wfaris if you can, could you please check #332 with your test suite to check if you see the expected improvement?
