### ISSUE TITLE
How to create individual log files for each worker

### ISSUE THREAD

**Issue by nbartos** [pytest-dev/pytest-xdist#331]
I'm trying to figure out how individual log files can be created for each worker, in the same manor that pytest --log-file does when not using xdist.

Since the basic pytest --log-file opens with write, not append (see https://github.com/pytest-dev/pytest/issues/3813), there does not seem to be a way of getting a complete log file for a run using xdist with multiple workers.  However, even if it could be opened in append mode, the individual worker IDs would not be present, and having everything mixed together can be more difficult for troubleshooting.

I'm hoping that there is some way of creating a log file for each worker, but I'm not really sure how to do that, if it's even possible.  I tried setting up a logger in pytest_configure, but worker_id does not seem to be available at that time.

**Comment by nicoddemus** [comment]
Actually you can access the worker id with the `PYTEST_XDIST_WORKER` environment variable, does that help?

**Comment by nbartos** [comment]
Yes that works, thanks!

**Comment by k3v8ns** [comment]
@nbartos   plz  help as you described.

**Comment by nbartos** [comment]
@k3v8ns This is basically what I am doing:

```
def pytest_addoption(parser):
    log_help_text = 'Similar to log_file, but %%w will be replaced with a worker identifier.'
    parser.addini('worker_log_file', help=log_help_text)
    log_group = parser.getgroup('logging')
    log_group.addoption('--worker-log-file', dest='worker_log_file', help=log_help_text)

def pytest_configure(config):
    log_file = config.getoption('worker_log_file')
    if log_file is None:
        log_file = config.getini('worker_log_file')
    log_level_opt = config.getoption('log_level')
    if log_level_opt is None:
        log_level_opt = config.getini('log_level')
    if log_level_opt:
        log_level = getattr(logging, log_level_opt.upper(), None)
        if not log_level:
            raise LogError('Invalid log-level option: {}'.format(log_level_opt))
    else:
        log_level = logging.DEBUG
    if log_file:
        logging.basicConfig(
            format='%(asctime)s %(name)s %(levelname)s %(message)s',
            filename=log_file.replace('%w', os.environ.get('PYTEST_XDIST_WORKER', 'master')),
            level=log_level)
```

Then you just need to set `worker_log_file` or `--worker-log-file` to a path that has `%w` in it, which will be replaced by the worker ID (or "master" for the master process).

**Comment by bondnotanymore** [comment]
@nbartos Thanks a lot for the above code, but still few parts of your solution are unclear to me.
Can you kindly help me understand what do you mean by this:
"Then you just need to set worker_log_file or --worker-log-file to a path that has %w in it, which will be replaced by the worker ID (or "master" for the master process)."

Also, i do not understand the usage of the option **log_help_text** in the parser_addoption, and how would the %%w get replaced with the worker identifier. Also is it okay if i can skip that?

**Comment by nbartos** [comment]
@bondnotanymore The `%w` replacement is actually the important thing, as if you don't set that in the log path, each log file would likely get clobbered as they would have the same name.  If you are using a pytest ini file, you need to set worker_log_file to something like `some/path/pytest-%w.log`, or you can use `--worker-log-file some/path/pytest-%w.log`.  Then, you'd have files like `some/path/pytest-gw1.log some/path/pytest-gw2.log some/path/pytest-master.log`

**Comment by bondnotanymore** [comment]
Thanks, @nbartos your response sir.

ok, but I am getting Keyerrors for worker_log_file option 
`INTERNALERROR>   File "/Users/kapilmathur/repositories/Spark_pytest/conftest.py", line 55, in pytest_configure
INTERNALERROR>     filename=config.getini('worker_log_file').replace(
INTERNALERROR>   File "/Users/kapilmathur/personal_virtualenv/spark_pytest/lib/python3.6/site-packages/_pytest/config/__init__.py", line 928, in getini
INTERNALERROR>     self._inicache[name] = val = self._getini(name)
INTERNALERROR>   File "/Users/kapilmathur/personal_virtualenv/spark_pytest/lib/python3.6/site-packages/_pytest/config/__init__.py", line 935, in _getini
INTERNALERROR>     raise ValueError("unknown configuration value: %r" % (name,))
INTERNALERROR> ValueError: unknown configuration value: 'worker_log_file'
`
**This is my env details:**

`pytest==4.6.2
pytest-forked==1.0.2
pytest-logger==0.5.1
pytest-single-file-logging==0.1.18
pytest-xdist==1.31.0`

**Comment by nbartos** [comment]
I haven't seen those in my environment.  I'd make sure you have set the option in the logging section, they are namespaced by section I believe.

**Comment by bondnotanymore** [comment]
If you are talking about the `ini` file, this is how I have defined that:

`[pytest]
addopts=-rsxX -v -l --tb=auto --strict
worker_log_file = pytest-%w.log
log_level = DEBUG
log_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_date_format=%Y-%m-%d %H:%M:%S
markers=
 smoke: Run the smoke test functions
 server_smoke: Filter the tests to be run for the Server smoke test job.
 toskip: Test cases marked to be skipped at later stage
 skip: Skips the test cases marked with this marker in the current session
`

**Comment by bondnotanymore** [comment]
Also, @nbartos is it possible for you and me to connect over a platform apart from just this.
It would be really awesome if i can pick your brain on how have you leveraged the pytest logger stuff and I can draw some help on what i am missing.

This is turning out to be very critical for me. Please let me know if we can sync up over a zoom or a hangout. Shall be highly obliged. thanks.

**Comment by ThreadDao** [comment]
I did like this: Instantiate a `FileHandler` object, whose parameter `filename` is dynamically determined by the current worker name (`os.environ.get('PYTEST_XDIST_WORKER'`)
```
work = os.environ.get('PYTEST_XDIST_WORKER')
log_worker = f'/tmp/logs/{work_log}.log'
wh = logging.FileHandler(log_worker)
wh.setLevel(logging.DEBUG)
self.log.addHandler(wh)
```
And you will see `gw0.log` and `gw1.log` and so on logs on path `/tmp/logs`

**Comment by RolfBippus** [comment]
The following code worked fine for me, avoiding additional logging setup apart from what pytest does anyway and allows to use the existing --log-file option.

```
@pytest.hookimpl(trylast=True) # try to execute after all other hooks to make all plugins available
def pytest_configure(config):
    # for using pytest-xdist with pytest option --log-file
    if 'PYTEST_XDIST_WORKER' in os.environ and config.option.log_file is not None:
        # create one logfile per worker!
        logging_plugin=config.pluginmanager.get_plugin("logging-plugin")
        root, ext = os.path.splitext(config.option.log_file)
        filename = f"{root}__{os.environ['PYTEST_XDIST_WORKER']}__{ext}"
        logging_plugin.set_log_path(filename) # this overwrites the logfile!
        _log.info(f"Logfile for worker {os.environ['PYTEST_XDIST_WORKER']}" )
```

**Comment by marcosanchotene** [comment]
I'm trying to achieve this but the `PYTEST_XDIST_WORKER` and `PYTEST_XDIST_WORKER_COUNT` variables are always returning `None` when called in `conftest.py`.

A code like below:

```
def pytest_configure(config):
    print('pytest_configure PYTEST_XDIST_WORKER', os.environ.get('PYTEST_XDIST_WORKER'))
    print('pytest_configure PYTEST_XDIST_WORKER_COUNT', os.environ.get('PYTEST_XDIST_WORKER_COUNT'))

def pytest_sessionstart(session):
    print('pytest_configure PYTEST_XDIST_WORKER', os.environ.get('PYTEST_XDIST_WORKER'))
    print('pytest_sessionstart PYTEST_XDIST_WORKER_COUNT', os.environ.get('PYTEST_XDIST_WORKER_COUNT'))
```

Is always generating this:

```
Launching pytest with arguments -n3 tests --no-header --no-summary -q in /home/repos/e2e-tests

pytest_configure PYTEST_XDIST_WORKER None
pytest_configure PYTEST_XDIST_WORKER_COUNT None
pytest_sessionstart PYTEST_XDIST_WORKER None
pytest_sessionstart PYTEST_XDIST_WORKER_COUNT None
============================= test session starts ==============================
gw0 I / gw1 I / gw2 I
[gw0] linux Python 3.7.12 cwd: /home/repos/e2e-tests
[gw1] linux Python 3.7.12 cwd: /home/repos/e2e-tests
[gw2] linux Python 3.7.12 cwd: /home/repos/e2e-tests
[gw0] Python 3.7.12 (default, Dec 13 2021, 12:39:51)  -- [GCC 9.3.0]
[gw1] Python 3.7.12 (default, Dec 13 2021, 12:39:51)  -- [GCC 9.3.0]
[gw2] Python 3.7.12 (default, Dec 13 2021, 12:39:51)  -- [GCC 9.3.0]
gw0 [4] / gw1 [4] / gw2 [4]

scheduling tests via LoadScheduling
```

Am I missing something?

**Comment by marcosanchotene** [comment]
Thanks, @nicoddemus ! Based on your answer I added the following code to the `conftest.py` file in the project root:

```
def pytest_addoption(parser):
    log_help_text = 'Similar to log_file, but %w will be replaced with a worker identifier.'
    parser.addini('worker_log_file', help=log_help_text)


def pytest_configure(config):
    configure_logger(config)

def configure_logger(config):
    if is_xdist_enabled():
        log_file = config.getini('worker_log_file')
        logging.basicConfig(
            format=config.getini('log_file_format'),
            filename=log_file.replace('%w', os.environ.get('PYTEST_XDIST_WORKER')),
            level=config.getini('log_file_level')
        )


def is_xdist_enabled():
    return os.environ.get('PYTEST_XDIST_WORKER') is not None
```

When executed with `xdist`, multiple log files are created based on the number of workers.

Thanks to @nbartos also, for such a helpful thread.

@nicoddemus , if you want I can make a pull request to add general instructions for this feature into the documentation.

**Comment by nicoddemus** [comment]
> @nicoddemus , if you want I can make a pull request to add general instructions for this feature into the documentation.

That would be terrific. I think a new section in https://pytest-xdist.readthedocs.io/en/latest/how-to.html would fit nicely. 👍

**Comment by rafalf** [comment]
@nicoddemus Is there any way to get sys.stdout printed? I have lost the output in my pipeline console

**Comment by QAingP** [comment]
I am trying to get log file for each worker. I have added code in conftest.py and pytest.ini file, but still separate log files are not generated. Below are the details of my files. Could someone please help me out.

My pytest.ini file
```python
[pytest]
worker_log_file = Logs/pytest-%w.log
log_file_format = [%(asctime)s  %(levelname)s  %(filename)s  %(lineno)s]  %(message)s
log_file_level = INFO
``` 

My conftest.py file code

```python
import os
from selenium import webdriver
import logging
import pytest
from Utilities.readProperties import ReadConfig
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()


def pytest_addoption(parser):  # This will get the value from Commandline
    parser.addoption("--browser")
    parser.addoption("--mode")
    log_help_text = 'Similar to log_file, but %%w will be replaced with a worker identifier.'
    parser.addini('worker_log_file', help=log_help_text)
    log_group = parser.getgroup('logging')
    log_group.addoption('--worker-log-file', dest='worker_log_file', help=log_help_text)


def pytest_configure(config):
    configure_logger(config)


def configure_logger(config):
    if is_xdist_enabled():
        log_file = config.getini('worker_log_file')
        logging.basicConfig(
            format=config.getini('log_file_format'),
            filename=log_file.replace('%w', os.environ.get('PYTEST_XDIST_WORKER')),
            level=config.getini('log_file_level')
        )


def is_xdist_enabled():
    return os.environ.get('PYTEST_XDIST_WORKER') is not None

**Comment by vitaly-krugl** [comment]
Here is another way with a single hook that overrides the value of the existing `--log-file` option. The only catch is that `pytest_cmdline_parse()` is called only if the plugin is passed to pytest.main() via the `plugins` arg.

```
@pytest.hookimpl(hookwrapper=True)
def pytest_cmdline_parse() -> None:
    outcome = yield

    worker_id = os.getenv('PYTEST_XDIST_WORKER')
    if not worker_id:
        # Called in context of master/controller process, so no need to override pytest's log filename.
        return

    config: pytest.Config = outcome.get_result()  # will raise if exception

    # Get the configured log filename
    pytest_log_file_opt = 'log_file'
    original_log_filename = (config.getoption(pytest_log_file_opt)
                             or config.getini(pytest_log_file_opt))
    if not original_log_filename:
        raise RuntimeError('Unable to get log file option from pytest config')

    old_path = pathlib.Path(original_log_filename)
    new_path = old_path.parent / f'{old_path.stem}.{worker_id}{old_path.suffix}'
    setattr(config.option, pytest_log_file_opt, str(new_path))
```

**Comment by vitaly-krugl** [comment]
I am able to assign worker-specific pytest log filenames as follows, using a single hookimp:

```
@pytest.hookimpl(tryfirst=True)
def pytest_configure(config: pytest.Config) -> None:
        worker_id = os.getenv('PYTEST_XDIST_WORKER')
        if not worker_id:
            # Called in context of master/controller process, so no need to override pytest's log filename.
            return

        # Get the configured log filename
        pytest_log_file_opt = 'log_file'
        original_log_filename = (config.getoption('log_file') or config.getini(pytest_log_file_opt))

        # Replace pytest's log file name with a dedicated pytest log filename for the current xdist worker:
        old_path = pathlib.Path(original_log_filename)
        new_path = old_path.parent / f'{old_path.stem}.worker.{worker_id}{old_path.suffix}'

        config.option.log_file = str(new_path)
```

**Comment by Kamilcuk** [comment]
I wanted to redirect both stdout and stderr. This is what I did:

```
$ cat tests/conftest.py 
import logging
import os
import sys
from pathlib import Path
from typing import IO, Dict

LOGFILES: Dict[str, IO] = {}


def pytest_configure(config):
    worker_id = os.environ.get("PYTEST_XDIST_WORKER")
    if worker_id and worker_id not in LOGFILES:
        logfile = Path(f"build/tests/{worker_id}.log")
        logfile.parent.mkdir(exist_ok=True, parents=True)
        logging.basicConfig(
            format=config.getini("log_file_format"),
            filename=logfile,
            level=config.getini("log_file_level"),
        )
        LOGFILES[worker_id] = logfile.open("wb")
        os.dup2(LOGFILES[worker_id].fileno(), sys.stdout.fileno())
        os.dup2(LOGFILES[worker_id].fileno(), sys.stderr.fileno())
```

**Comment by alex0v3rs0n1c** [comment]
#save to conftest.py
@pytest.hookimpl(tryfirst=True)
def pytest_configure(config):
    worker_id = environ.get("PYTEST_XDIST_WORKER")
    if worker_id is not None:
        logging.basicConfig(
            format=config.getini("log_format"),
            filename=f"./logs/tests_{worker_id}.log",
            level=config.getini("log_file_level"),
        )
