### ISSUE TITLE
Handle pytest_warning_captured in workers

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-xdist#341]
Currently the warnings are no longer being transferred from workers to master.

**Comment by nicoddemus** [comment]
Oh oh. What to do about the `item` parameter of the [`pytest_warning_captured`](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_warning_captured) hook?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus its a unfixable error as is

**Comment by nicoddemus** [comment]
Yep, in hindsight that should have been `nodeid`, not `item`. 😞 See my PR.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus since we don't have a process for experimenting with api and pluggy doesn't have a tool for renames or changes of hook parameters, a new hook name is needed

**Comment by nicoddemus** [comment]
Perhaps, but as it stands at least the warnings are displayed, so I think the current PR is an improvement over not showing anything.

**Comment by RonnyPfannschmidt** [comment]
`None` instead of a item is a **breach of api**

**Comment by nicoddemus** [comment]
Not according to the [docs](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_warning_captured):

> item (pytest.Item|None) – The item being executed if when is "runtest", otherwise None.

So `None` is definitely a possible value for item, and hook implementations should deal with it accordingly.

**Comment by nicoddemus** [comment]
Just to be clear: I'm not saying this is perfect, but we have to take in account a few points:

1. This hook was just introduced, so I think only pytest itself uses it at the moment.
2. The long term solution is to either introduce a new hook as you suggest or a new `nodeid` parameter to the existing hook, possibly deprecating `item` (we will need to introduce such support to `pluggy`).

All of the above are very long term (at least until the next minor release cycle), so the approach proposed here is not a breach of API (according to the documentation) and at least will show warnings from workers. The price? Well, `item` will always be `None` when using xdist, which pytest already handles gracefully and as said I suspect no other plugins make use of this hook anyway.

Because of those reasons I still think the current PR is an improvement over the current state of things.

**Comment by RonnyPfannschmidt** [comment]
Indeed my mistake, if none is valid its good to go in
