### ISSUE TITLE
Warning subclass which break subclassing protocol break xdist

### ISSUE THREAD

**Issue by BrandonHoffman** [pytest-dev/pytest-xdist#344]
The latest xdist change causes issues whenever a subclass of the Warning class which does not set the args property due to this line: https://github.com/nicoddemus/pytest-xdist/commit/eb81450915528976cea8372bbc4c41cb7e82e9d1#diff-cb98e0a92df3b797a1570a6e1a49b8d6R429

see the issue I created for an example: https://github.com/briancurtin/deprecation/issues/36

I think it would be a good to add some error handling for cases like this in xdist so that they do not cause pytest to fail with an internal error.

**Comment by nicoddemus** [comment]
Hi @BrandonHoffman,

Not sure what pytest-xdist can do in this case, as the Warning subclass is not following basic subclassing guarantees (keeping the same interface as the parent class). 

@RonnyPfannschmidt what's your opinion?

**Comment by nicoddemus** [comment]
(@BrandonHoffman took the liberty of updating the title to reflect the underlying issue better)

**Comment by RonnyPfannschmidt** [comment]
xdist doesnt follow the reduce/restore protocols for serialization, so its a xdist bug for now

**Comment by BrandonHoffman** [comment]
I think it may be a good idea to just add a try accept around the class initialization so that it does not cause a pytest to halt abruptly with an internal error

```
try:
    message = cls(*data["message_args"])
except TypeError as error:
    message = Warning("Failed to pass through {module}.{class} with args {args}".format(module=data["message_module"], class=data["message_class_name"], args=data["message_args"]))
```

another option for the message would be to store message_str here:

https://github.com/nicoddemus/pytest-xdist/commit/eb81450915528976cea8372bbc4c41cb7e82e9d1#diff-30240c5c51db0f0f5c8cb678115ed270R185

as

```
message_str = str(warning_message.message)
```

that way you can use that message in the exception case shown above

**Comment by nicoddemus** [comment]
@BrandonHoffman that might be a valid workaround, but it seems @RonnyPfannschmidt suggestion to implement the reduce protocol is the correct one, albeit seems a lot more work because the reduce protocol (IIUC) is more complex to support.

**Comment by RonnyPfannschmidt** [comment]
also setstate/getstate, it bacially requires a safe serialize/deserialize just like we need it for reports as well - this is something that takes quite a while to get right

**Comment by nicoddemus** [comment]
@BrandonHoffman I'm fine with implementing a quick workaround like the one you mention. Would you like to open a PR with that? I'm afraid I'll be short on time on the next few days to work on that PR.

> also setstate/getstate, it basically requires a safe serialize/de-serialize just like we need it for reports as well - this is something that takes quite a while to get right

My feelings exactly.

**Comment by nicoddemus** [comment]
@BrandonHoffman `1.23.2` is out, thanks for bringing this up and providing the initial patch! 👍

**Comment by nicoddemus** [comment]
> xdist doesnt follow the reduce/restore protocols for serialization

@RonnyPfannschmidt I was refreshing my memory about the reduce protocol, and as I remember, it is quite convoluted and error prone: https://docs.python.org/3/library/pickle.html#object.__reduce__

Should we:

1. Try to implement the full protocol?
2. "cheat" a little and use pickle/unpickle directly, so it takes care of implementing the correct protocol.
3. Some other approach?

What is your opinion?

I was taking a look at fixing #349 on the weekend, and due to how warnings can be produced as `warnings.warn(msg, UserWarning)` or `warnings.warn(UserWarning(msg))` (what a mess), it seems we need to go forward with the full `__reduce__` protocol as the code is getting quite unyielding.

**Comment by gsakkis** [comment]
Not sure if it's the same bug but I'm getting `DumpError: can't serialize <class '_pytest.warning_types.RemovedInPytest4Warning'>` with `pytest-xdist>1.23.0`; `pytest-xdist==1.23.0` works fine (both with `pytest==3.9.3`)
