### ISSUE TITLE
Determine the number of workers

### ISSUE THREAD

**Issue by decaz** [pytest-dev/pytest-xdist#352]
Is it possible to determine the number of workers within tests? As I know there is only `worker_id` variable and there is no something like `worker_count` variable.

**Comment by nicoddemus** [comment]
Hi @decaz, you can use the `PYTEST_XDIST_WORKER_COUNT` environment variable for that.

**Comment by decaz** [comment]
Thanks! Also I have found `request.config.workerinput['workercount']`. Is it planned to be added as `worker_count` fixture in the future?

**Comment by nicoddemus** [comment]
Nothing planned, but a PR would be welcome I think.

I'm closing this as I believe your question has been answered. 😁
