### ISSUE TITLE
altering test queue at runtime

### ISSUE THREAD

**Issue by mulawamichal** [pytest-dev/pytest-xdist#355]
hi,

Is there a way to dynamically add some tests to the test queue (at the end) when using xdist ? I sometimes need to rerun my test, but not right after if tails, but rather at the end. I tried something like this:

    request.session.items.append(request.node)

but it only works when xdist is disabled.

**Comment by nicoddemus** [comment]
Hi @mulawamichal,

As @RonnyPfannschmidt mentions there's no official support to do this.

**Comment by mulawamichal** [comment]
Well what can i say. Thanks for reply!
br
mike
