### ISSUE TITLE
Access the CLI parameters when running with pytest xdist

### ISSUE THREAD

**Issue by david-fliguer-ws** [pytest-dev/pytest-xdist#358]
Hi, I have the following script called test_cli.py

```python
import sys
def test_one():
    print(sys.argv[1])
def test_two():
    print(sys.argv[1])
```
    
When I run it like this

```
pytest -s
```

I can see the output -s (Which is fine because it is the second parameter of the CLI) but when I run it with pytest xdist as 

```
pytest -s -n auto
```

I get the following output

```
================================== FAILURES ===================================
__________________________________ test_one ___________________________________
[gw0] win32 -- Python 3.6.4 c:\python36-32\python.exe

    def test_one():
>       print(sys.argv[1])
E       IndexError: list index out of range

test_cli.py:3: IndexError
__________________________________ test_two ___________________________________
[gw1] win32 -- Python 3.6.4 c:\python36-32\python.exe

    def test_two():
>       print(sys.argv[1])
E       IndexError: list index out of range

test_cli.py:5: IndexError
========================== 2 failed in 3.49 seconds ===========================
```

How can I access the CLI parameters when running with pytest-xdist ? 
I need to use one of the parameters of the CLI to control the behaviour of one of my fixtures that is shared between tests and processes..

Thanks,

David

**Comment by david-fliguer-ws** [comment]
I see that when running with pytest-xdist sys.argv has only one element which is -c, where do the rest of the parameters that I pass to pytest invocation go ?

**Comment by RonnyPfannschmidt** [comment]
They stay on the main process, one can't rely on them being available

**Comment by david-fliguer-ws** [comment]
: /

I guess I need a little more deep understanding of pytest-xdist, because I am having a few problems and they all seem related to the fact that (If I understand correctly) pytest-xdist works spawning multiple python processses, instead of creating threads under the same process, right ?

**Comment by david-fliguer-ws** [comment]
Can I access the main process in same way to take them from there ?

If my invocation line is pytest somefolder -n auto

I would like to each worker to have access to the "somefolder"

**Comment by david-fliguer-ws** [comment]
Well I just made the following dirty workaround but it is working for me:

Add another fixture like this

def pytest_configure_node(node):
    # Here we still have access to sys.argv so we can write a txt file containing the name of the plugin_to_run
    with open("plugin_to_run.txt", "w") as file:
        file.write(sys.argv[1])

and on my fixture that is already after we have lost access to sys.argv I read the content of that file...

**Comment by RonnyPfannschmidt** [comment]
you can use workerinput and node configuration hooks to pass over values and data

**Comment by david-fliguer-ws** [comment]
How can I make that data available once the workers are created ?

Can you maybe show a little example of reading sys.argvs on one of those hooks and then using it on a session scoped fixture ?

**Comment by RonnyPfannschmidt** [comment]
Unfortunately I'm on mobile rright now, but the basic gist is extract in pytest-cofigure, pass on via worker config hooks.

**Comment by blueyed** [comment]
Check out https://github.com/pytest-dev/pytest-xdist/pull/388.
