### ISSUE TITLE
All workers are blocked when 'sleep' is running in any worker

### ISSUE THREAD

**Issue by vadym-kovryzhkin** [pytest-dev/pytest-xdist#361]
If `sleep` is invoked in test method in one worker, then all other workers will also wait until that sleep finishes. 

Here are just examples of tests:
```
    def test_1():
        # test is running in gw1 worker
        print("Start sleep 5 sec in test 1")
        sleep(5)
        print("Test 1 finished")

    def test_2():
        # test is running in gw2 worker
        print("Test 2 finished")
```

After running tests with `pytest -s -n2`  we can see, that `test_2` will not start until `sleep(5)` is finished in `test_1` test. So worker `gw2` will be blocked by worker `gw1`

Is this really expected behavior?

**Comment by nicoddemus** [comment]
Hi @Vadim-Kovrizhkin,

You are probably hitting a worst-case scenario on the scheduler, because it probably needs to wait for all tests to finish before ending the session.

If I change your example to a more realistic scenario with more tests:

```python
from time import sleep

import pytest


def test_1():
    # test is running in gw1 worker
    print("Start sleep 5 sec in test 1")
    sleep(5)
    print("Test 1 finished")


@pytest.mark.parametrize('i', range(10))
def test_2(i):
    # test is running in gw2 worker
    print("Test 2 finished")
``` 

Then we can see that most of `test_2` tests run in a worker before we get stuck on `test_1`.

**Comment by Vadim-Kovrizhkin** [comment]
But in real life, if one worker gets stuck, then all other workers will be blocked.  And this is what I see in real life: hanged terminals, hanged Jenkins jobs, etc. Case, that I described in ticket, just helped me to reproduce this behavior(issue). 

On this gif, you can see that worker gw1 does not start until sleep in gw0 is finished:
![example](https://user-images.githubusercontent.com/12123266/47411339-0e89fa80-d771-11e8-9749-2722e663ec5d.gif)

**Comment by RonnyPfannschmidt** [comment]
the 2 tests that are held up in the queue are part of a major design problem of pytest/pytest-xdist that got introduced for a quick hack way of sorting out fixture teardown

the last tests cant run until we know the testrunners can exit, 1 of them is queues on the sleeping worker, the other is being held on the next worker until the end of the test session is indicated by the coordinating process

which as far as i can tell is exactly whats happening there

**Comment by Vadim-Kovrizhkin** [comment]
@RonnyPfannschmidt thank you for explanation 
Is there any way to not set worker into a queue?

**Comment by RonnyPfannschmidt** [comment]
@Vadim-Kovrizhkin no, the queuing and hold is the result of a structural issue that was introduced as a quick solution to a deeper structural problem - it would take a significant amount of time and a few breaking pytest releases to sort this mess out
