### ISSUE TITLE
pytest_runtest_logreport() check for item_index ruins custom test threading logic inside workers

### ISSUE THREAD

**Issue by sosadchuk** [pytest-dev/pytest-xdist#395]
I'm trying to implement ordering and parallel execution of tests inside worker with threading.
For example I have a list of tests to execute defined like:
```
test02
test02, test01
test02
```
I use pytest_generate_tests() hook to order tests and add '_parallel' postfix for simultaneous tests.

Then I use pytest_runtest_protocol() hook to start parallel tests:
```
    def pytest_runtest_protocol(self, item, nextitem):
        if item in self._queue:
            index = self._items.index(item)
            return None        

        if not item.name.endswith('_parallel]'):
            if len(self._queue) > 0:
                threads = []
                for test in self._queue:
                    thread = MyThread(test)
                    thread.start()
                    threads.append(thread)
                [t.join() for t in threads]
                self._queue = []
            return None
        else:
            self._queue.append(item)
            return True


class MyThread(threading.Thread):
    def __init__(self, test):
        super().__init__()
        self.test = test

    def run(self):
        self.test.ihook.pytest_runtest_protocol(item=self.test, nextitem=None)
```

The issue is in pytest-xdist pytest_runtest_logreport() hook in 'remote' module, which performs check:
```
assert self.session.items[self.item_index].nodeid == report.nodeid
```

If I comment this out - everything works perfect.

The question is: is this check really needed to prevent some tests overlay, or is it possible to create a way to pass item_index to WorkerInteractor object, which works inside execnet?

Executing pytest with:
```
-n 2 --dist=loadscope --tx 2*popen//python=python -m 'not serial'
```

**Comment by RonnyPfannschmidt** [comment]
first and foremost i'd like to make it abundantly clear that the internals of pytest are ***not*** thread-safe

so if your testing somehow works please keep in mind that that is by accident/luck and not for a solid base

i am curious about the surrounding use-case that necessitates the threads

**Comment by sosadchuk** [comment]
> first and foremost i'd like to make it abundantly clear that the internals of pytest are _**not**_ thread-safe
> 
> so if your testing somehow works please keep in mind that that is by accident/luck and not for a solid base
> 
> i am curious about the surrounding use-case that necessitates the threads

I noticed session-scoped fixtures are being teardowned before session ends and I might have seen open issue here. In that case I use threading locks for fixtures/connections/requests, and it's fine for me.

About the needs: we are migrating from previous testing engine, where tests were divided into 'batches', some of which intended to be executed simultaneously. We use pure pytest-xdist in that case.

But some of those batches have a file, where test order is describes. And while test ordering is not a problem, running some of them in parallel is a mess. There come additional hooks and threads.

**Comment by RonnyPfannschmidt** [comment]
@sosadchuk session scope fixtures are town down here because nextitem is None

**Comment by sosadchuk** [comment]
> @sosadchuk session scope fixtures are town down here because nextitem is None

Thx! passed nextitem and fixtures started working as expected

**Comment by nicoddemus** [comment]
@sosadchuk can we close this?

**Comment by RonnyPfannschmidt** [comment]
@sosadchuk from my pov this is a relatively important sanity check, and the use-case you try to implement is not really supported at a very basic level by both pytest core and pytest-xdist

i'll review when/why it got added to take a look on whether we can be more relaxed on that front

**Comment by RonnyPfannschmidt** [comment]
i took a look at the surrounding code - as of now its absolutely unacceptable to remove that sanity check

**Comment by sosadchuk** [comment]
> i took a look at the surrounding code - as of now its absolutely unacceptable to remove that sanity check

thx! could you please recommend any way to pass item_index into WorkerInteractor object, maybe I miss one?

or will it be reasonable to add one?

i tried to play with manual calls:
```
from _pytest import runner
item.ihook.pytest_runtest_logstart(nodeid=item.nodeid, location=item.location)

call = runner.call_runtest_hook(item, 'setup')
hook = item.ihook
report = hook.pytest_runtest_makereport(item=item, call=call)
report.nodeid = 'tests/test_xdist.py::TestClass1::test_parm1[Parm.RAMPA0021]'
hook.pytest_runtest_logreport(report=report)

call = runner.call_runtest_hook(item, 'call')
hook = item.ihook
report = hook.pytest_runtest_makereport(item=item, call=call)
report.nodeid = 'tests/test_xdist.py::TestClass1::test_parm1[Parm.RAMPA0021]'
hook.pytest_runtest_logreport(report=report)

# call = runner.call_runtest_hook(item, 'teardown')
hookname = "pytest_runtest_" + 'teardown'
ihook = getattr(item.ihook, hookname)
call = runner.CallInfo(
lambda: ihook(item=item, nextitem=None),
    when='teardown',
    treat_keyboard_interrupt_as_exception=item.config.getvalue("usepdb"),
)
hook = item.ihook
report = hook.pytest_runtest_makereport(item=item, call=call)
report.nodeid = 'tests/test_xdist.py::TestClass1::test_parm1[Parm.RAMPA0021]'
hook.pytest_runtest_logreport(report=report)

item.ihook.pytest_runtest_logfinish(nodeid=item.nodeid, location=item.location)
return True
```
but report will have 3 results for RAMPA0021, which is not good

**Comment by RonnyPfannschmidt** [comment]
iff hand i am unable to correctly suggest this - the state-keeping in the object is absolutely not set up to handle more than one test happening at the same time right now

it would take me a while to decompose it, and even then it would at best work by accident

**Comment by sosadchuk** [comment]
this can be closed.

workaround would be to set current test _nodeid attribute via session object to a needed test and at the end - change it back.

```
    def pytest_runtest_protocol(self, item, nextitem):
        if item in self._queue:
            self.session.items[self.session.items.index(nextitem)]._nodeid = item.nodeid
            return None

        if not item.name.endswith('_parallel]'):
            if len(self._queue) > 0:
                save_nodeid = item.nodeid
                threads = []
                for test in self._queue:
                    thread = MyThread(test, item)
                    thread.start()
                    threads.append(thread)
                [t.join() for t in threads]
                self._queue = []
                item._nodeid = save_nodeid
            return None
        else:
            ...
```
