### ISSUE TITLE
Is --ignore flag not compatible with xdist?

### ISSUE THREAD

**Issue by xNinjaKittyx** [pytest-dev/pytest-xdist#399]
I have one test in particular in my test suite that I would like to ignore specifically when running xdist because it shuts down the server that I'm testing against (which will cause all the other parallel tests to fail)

I added `--ignore=path/to/folder/*` from pytest's parameters to skip those tests, but it seems like xdist is still running the tests in that folder.

I've tested it without using xdist, and it works fine.

With xdist, I'm not doing anything fancy, just using the `-n` parameter

Python 3.6.3
pytest 3.6.4
xdist 1.25.0

**Comment by nicoddemus** [comment]
OK, thanks @xNinjaKittyx for the follow up.
