### ISSUE TITLE
Identify each --tx worker with an alias name

### ISSUE THREAD

**Issue by mitzkia** [pytest-dev/pytest-xdist#405]
My goal is to identify "--tx workers" with an alias name. 
I know there is already a worker_id variable for this, but is is not suitable for me. As I saw it is a sequentially growing id: gw0, gw1, which is not identifies precisely my "--tx" workers.

My use-case is:
1, With using such a pytest.ini file
```
[pytest]
addopts =   --tx ssh="172.17.0.2 -l root"
            ; debian-latest
            --tx ssh="172.17.0.3 -l root" 
            ; ubuntu-latest
```
2, Had a pytest result:
```
...
test_a.py::test_a 
[gw1] [ 50%] FAILED test_a.py::test_a 
test_b.py::test_b 
[gw1] [100%] PASSED test_b.py::test_b 
[gw0] [100%] FAILED test_a.py::test_a 
test_b.py::test_b 
[gw0] [100%] PASSED test_b.py::test_b 
...
```

I would expect to get such a result:
```
test_a.py::test_a 
[debian-latest] [ 50%] FAILED test_a.py::test_a 
test_b.py::test_b 
[debian-latest] [100%] PASSED test_b.py::test_b 
[ubuntu-latest] [100%] FAILED test_a.py::test_a 
test_b.py::test_b 
[ubuntu-latest] [100%] PASSED test_b.py::test_b 
```
It would absolutely ok if I could specify my custom worker name in execution time, like:
```
[pytest]
addopts =   --tx ssh="172.17.0.2 -l root" --tx-name="debian-latest"
            ; debian-latest
            --tx ssh="172.17.0.3 -l root" --tx-name="ubuntu-latest"
            ; ubuntu-latest
```

Is there a native way to achieve my goal? If there is not, is such a feature is relevant for pytest-xdist?

Thanks

**Comment by RonnyPfannschmidt** [comment]
use `--tx id=ubuntu-latest//ssh=...`

**Comment by mitzkia** [comment]
Exactly this is what I need. Thanks a lot :)
