### ISSUE TITLE
Mysterious logwarning warnings only happen with xdist under Pytest 4.1

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest-xdist#406]
[Here's a CI log](https://circleci.com/gh/HypothesisWorks/hypothesis/6219) from HypothesisWorks/hypothesis#1782.  To reproduce this problem, clone Hypothesis (and for posterity, check out the current master d1b0df5).

    pip install -r requirements/test.txt
    pip install -e hypothesis-python/
    pip install pytest==4.1
    pytest hypothesis-python/tests/cover/test_testdecorators.py       # quick subset, passes
    pytest hypothesis-python/tests/cover/test_testdecorators.py -n 2  # fails thanks to -Werror

So *somewhere*, our dependencies must be using a `pytest_logwarning`, right?  Except that I can't find such a location in any of them, and we're not using any pytest plugins aside from xdist itself!

Do you have any idea what's happening here, or how I might find out?  It's been blocking our move to Pytest 4.1 for weeks now :disappointed:

**Comment by RonnyPfannschmidt** [comment]
the culprit is https://github.com/pytest-dev/pytest-xdist/blob/master/xdist/remote.py#L119-L128
in combination with https://github.com/pytest-dev/pytest/blob/5119abe4984a1b21e238b242fe233a250d2cf410/src/_pytest/hookspec.py#L501-L502

CC @nicoddemus

**Comment by RonnyPfannschmidt** [comment]
the culprit is https://github.com/pytest-dev/pytest-xdist/blob/master/xdist/remote.py#L119-L128
in combination with https://github.com/pytest-dev/pytest/blob/5119abe4984a1b21e238b242fe233a250d2cf410/src/_pytest/hookspec.py#L501-L502

CC @nic

**Comment by RonnyPfannschmidt** [comment]
@Zac-HD as  a workaround i propose ignoring that specific warning

but i notice that -Werror is quite a pain as it hides passed on location information

**Comment by RonnyPfannschmidt** [comment]
pytest-xdist already conditionally imports the hook, i believe simply not implementing it when the warning is there suffices

https://github.com/pytest-dev/pluggy/blob/master/pluggy/hooks.py#L37 suggests if we not only check for the existence, but also for (untested) `pytest_spec.get("warn_on_impl")` things should be fine

**Comment by nicoddemus** [comment]
I think we can simply stop implementing it, given that we will remove it anyway in the future.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus we should take a look at the support matrix then just in case

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt went ahead with your suggestion given that it is really simple anyway. 👍

**Comment by Zac-HD** [comment]
Two hours from report to merged fix... you guys are legends :heart_eyes:

**Comment by danmash** [comment]
https://github.com/pytest-dev/pytest-xdist/issues/410
