### ISSUE TITLE
Can not retrieve "assertion" reports from remote run (using --tx ...)

### ISSUE THREAD

**Issue by mitzkia** [pytest-dev/pytest-xdist#408]
I have a code which can retrieve assertion reports:
- this works correctly when I run my tests locally (without --tx ...)
- self.__testcase_context is the request object
- the self.__logger_factory is my own logger factory (not native pytest)
```
terminalreporter = self.__testcase_context.config.pluginmanager.getplugin("terminalreporter")
if terminalreporter and terminalreporter.stats.get("failed"):
    for failed_report in terminalreporter.stats.get("failed"):
        if failed_report.location[2] == self.__testcase_context.node.name:
            self.__logger = self.__logger_factory.create_logger(
                "Teardown", use_console_handler=False, use_file_handler=True
            )
            self.__logger.error(str(failed_report.longrepr))
```

The above code is not work in case of remote run (with --tx ...), maybe there is no terminalreporter object? But I can see the needed AssertionError in my console, which I wanted to query remotely.
Is there a way to get assertion reports on remote run?

Thanks for your answer

**Comment by RonnyPfannschmidt** [comment]
@mitzkia indeed there is no terminalreporte4r on the remote - https://github.com/pytest-dev/pytest-xdist/blob/master/xdist/remote.py#L251 turns it off

**Comment by mitzkia** [comment]
Thanks for the quick answer. What is the behind reason of the disabling this? 
Is not a good choice to enable it?

**Comment by mitzkia** [comment]
Sorry my other question, not really belongs to this issue. 
Is there a handy way to debug the code in remote runs? 
Usually I am using pdb.set_trace() inside my code, but it did not works remotely :(

**Comment by RonnyPfannschmidt** [comment]
@mitzkia the remote has no terminal to report on, so the terminalreporter can't do anything useful there

the lack of remote pdb support is also a quite painful shortcoming (pdb breaks on remotes due to execnet)

**Comment by mitzkia** [comment]
@RonnyPfannschmidt Thanks for your answers.
After investigating a little, I have a new question.
Did not understand how I get back the necessary AssertionError information to my console during the 
pytest_terminal_summary() hook, example:
```
      pytest_terminal_summary [hook]
          terminalreporter: <_pytest.terminal.TerminalReporter object at 0x7f6e1cf55198>
          exitstatus: 1

==================================================================================================== FAILURES =====================================================================================================
___________________________________________________________________________________________________ test_simple ___________________________________________________________________________________________________
[ubuntu-latest-192.168.9.110] linux -- Python 3.6.7 /usr/bin/python3

    def test_simple():
>       assert ret_2() == ret_3()
E       assert 2 == 3
E         -2
E         +3


pytest_framework/pe7_only_tests/simple/test_simple.py:8: AssertionError
      finish pytest_terminal_summary --> [] [hook]
```
Is not this information exist on the other side (remote)?
In my understanding the information came from "ubuntu-latest-192.168.9.110".

**Comment by RonnyPfannschmidt** [comment]
its not clear to me what you mean by "AssertionError information" please elaborate

**Comment by mitzkia** [comment]
Sorry about that, maybe I am not using correct terminologies.
This is the information which I get from (see my first comment):
```
str(failed_report.longrepr)
```

**Comment by mitzkia** [comment]
Just found something from dsession.py:
class TerminalDistReporter(object):
    def __init__(self, config):
        self.config = config
        self.tr = config.pluginmanager.getplugin("terminalreporter")

Maybe this terminalreporter can help me?

**Comment by mitzkia** [comment]
Perhaps my previous tip was wrong. Not yet learnt what runs locally what runs remotely.
I am still investigating.

**Comment by mitzkia** [comment]
My new guess is the information which I needed remotely is "pushed back" here:
remote.py: pytest_runtest_logreport() -> self.sendevent("testreport", data=data)

**Comment by mitzkia** [comment]
Thanks for your answer. 

My use case is the following:
- Until now our tests runs locally.
- We have created an internal logger object to collect our logs from testruns (also from libs also from tests)
- With our logger we could display logs on console and also we can send them to file (Each testcase has own testcase.log file)
- If our testcase failes we wanted to write AssertionError information (longrepr) also into the testcase.log file. It works as I mentioned in comment1

For now we decided that we wanted to run tests remotely, everything seems to work correctly (except debugging is not so easy). First remark we can not access to "longrepr" in same way.
Our remote log collection:
- On remote machine our logger collects logs into testcase.log, which we rsync back to our host (it would be great if it would work natively through execnet, #177 )

**Comment by RonnyPfannschmidt** [comment]
you can just fetch the testcase.log files content and put them into a testreport section

**Comment by mitzkia** [comment]
I am searching for a correct hook, where I can set custom file_handler (file path contains testcase name) for 'logging-plugin'.
Found "pytest_report_header(config)", but it is too early, testcase information are not yet exist, there is no config.node object.
Also found "pytest_runtest_logstart(nodeid, location)", but in the scope of this hook I can not access to config to load "logging-plugin"
