### ISSUE TITLE
running a certain test suite in a certain thread

### ISSUE THREAD

**Issue by SergeyChu** [pytest-dev/pytest-xdist#409]
Not an issue, rather as an improvement or question if it's already exist.

The requirement is to run all the tests belonging to a suite in a certain thread. For example having suite1, suite2, suite3 and so on. And I'd like to make all the tests belonging to the suite1 executed in one thread(thread1), whereas tests belonging to the suite2 in another thread(thread2) and tests from suite3 in one more separate thread(thread3).

Currently there are only 2 options: - --dist=loadscope(by module) - --dist=loadfile(by filename)

And it would be really nice to have kind of a --dist=loaddirectory, to grab all the tests in a certain directory
e.g for each dir in a dir given as a path to all the test suits, or, in all the recursively met directories.

**Comment by RonnyPfannschmidt** [comment]
pytest-xdist does not use threads, do you want to distribute by suite to processes?
right now thats not supported/buildin, it would need someone to push for it

**Comment by SergeyChu** [comment]
Hi Ronny,
thanks for the reply.
Apologies for my ignorance, just presumed that workers and processes from [the description](https://pypi.org/project/pytest-xdist/#parallelization) means threads.
Just a silly question in the case, am I correct that tests distributed in a such way would be run using all the available CPU cores?

**Comment by RonnyPfannschmidt** [comment]
@SergeyChu yes, its the main goal there ^^ cpu usage

**Comment by nicoddemus** [comment]
You still want to propose the `--dist=loaddirectory` @SergeyChu ?

**Comment by SergeyChu** [comment]
Hi @RonnyPfannschmidt thanks for the confirmation.
@nicoddemus, I discussed with the team and we confirmed that the --dist=loadfile is currently enough to deliver an MVP version of our test harness, however, in the future, it would be nice to have the --dist=loaddirectory scope.

Is it anything required from my side to kick off the directory scope development?

**Comment by nicoddemus** [comment]
> Is it anything required from my side to kick off the directory scope development?

It would be nice to create a new issue detailing the proposal, for example, how many directory levels deep do we consider in order to group tests, etc.

Other than that, currently we are short on development time on `pytest-xdist`, focusing mostly on critical bugs, so working on a PR would be the best way to get this rolling. We would love to guide you in this regard. 👍 

I'm closing this issue then, thanks!
