### ISSUE TITLE
--numprocesses  in pytest.ini

### ISSUE THREAD

**Issue by Yobmod** [pytest-dev/pytest-xdist#433]
I'm running pytest with pytest-xdist and pytest-cov. It all works fine from the command line with `pytest --cov="." --numprocesses=4` flags.

But if I put the numprocceses flag in my pytest.ini (`addopts = --numprocesses=4`), then coverage is not repoerted, with error: `The following slaves failed to return coverage data, ensure that pytest-cov is installed on these slaves. `

-n4 flag works both on command line and in the pytest.ini.

Is --numprocesses=x supposed to work in the .ini file?  I'm sure it used to. I didn't know if this was an xdist or cov issue, so reported here first.

Edit: ah, it works if I don't have any comments in my .ini, so I guesss not a xdist issue!

**Comment by nicoddemus** [comment]
Hi @Yobmod, OK, thanks for the follow up!
