### ISSUE TITLE
How to combine the allure report？

### ISSUE THREAD

**Issue by LuanShiZhiJian** [pytest-dev/pytest-xdist#434]
I tried to use distributed Allure to implement distributed testing. 

What is the correct way to do this?Or is there a plan available?

**Comment by nicoddemus** [comment]
Hi @LuanShiZhiJian,

Are you using [pytest-allure](https://github.com/allure-framework/allure-python)? If so I suggest you post the question there, they probably will have more information about how the integration can work.

I'm closing this now but feel free to follow up with further questions.
