### ISSUE TITLE
Seeing logger stream closed prematurely creating pytest errors

### ISSUE THREAD

**Issue by spearsem** [pytest-dev/pytest-xdist#446]
See the description in https://github.com/pytest-dev/pytest/issues/5502 ... I see this when I am using pytest-xdist most frequently and can isolate it to when I am using parallel workers. I can't provide a minimal example that reproduces it unfortunately.

**Comment by Zac-HD** [comment]
Closing this as there is now a reproducer that doesn't need `pytest-xdist` - it's somewhere in the core or the capture plugin.
