### ISSUE TITLE
Installing pytest-xdist 1.29.0 hangs all pytests

### ISSUE THREAD

**Issue by LukeJelly** [pytest-dev/pytest-xdist#449]
Tested on two computers. 
**PC:**
OS WIn10 Pro 1903 64bit
i7-8700K

pytest 5.0.0
pytest-xdist 1.29.0
pytest-forked 1.0.2

**Laptop:**
OS Win10 Pro 1903 64bit
i7-8650U

pytest 5.0.0
pytest-xdist 1.29.0
pytest-forked 1.0.2

I normally run "pytest -v --numprocesses=auto" but this hangs, if also if I just run pytest by itself it just hangs.  I noticed this after reinstalling pytest-xdist recently.  I went to check on my laptop if it was hanging and it wasn't so I checked what version my laptop was on and it was on pytest.xdist 1.28.0.  I installed pytest-xdist 1.29.0 on my laptop and now everything is hanging on it aswell. 

If i uninstall pytest-xdist and pytest-forked on both my machines I can run my tests again but obviously not in parallel.  

I'm new to this what more information do you need from me to fully troubleshoot this? Can in install a legacy version of pytest-dist easily?

**Comment by nicoddemus** [comment]
Hi @LukeJelly,

Strange, we haven't received any reports of `1.29` just hanging. We also use that version daily without problems.

Do you see this hanging with any repository or just with a specific repository? I suggest you try running pytest in a dummy repository with a few tests to see if you get the same behavior. 

Unfortunately pytest 5.0 requires pytest-xdist 1.29, so unless you downgrade pytest too, you cannot really downgrade pytest-xdist.

**Comment by LukeJelly** [comment]
I'll create a new test repository right now and check it out.  The repository I'm working with right now is [this one](https://github.com/joshua-sterner/pygameOpenGLUtil).

**Comment by RonnyPfannschmidt** [comment]
it would be really helpful to figure where exactly it actually hangs,

if you could get fault-handler trace or anything that indicates where exactly it hangs, it would be a big help

**Comment by LukeJelly** [comment]
@RonnyPfannschmidt I don't know what I changed but they tests are working now in parallel.  I really haven't done much besides change my test.py files up a little bit.  I'm gonna close this for now and I'll come back and post again if I figured out what I changed. 

Thanks for the help!

**Comment by LukeJelly** [comment]
I figured out the issue.  If you install pytest-xdist as and administrator and then run pytest with out admin privileges pytest-forked tries to make a temporary folder in the directory it is installed in but does not have permissions this causes everything to hang.  The fix is to uninstall and reinstall using --user or run all your tests as an administrator.

**Comment by nicoddemus** [comment]
Thanks @LukeJelly for following up with your findings. 👍

**Comment by BwL1289** [comment]
@LukeJelly I am also experiencing this. I am following your suggestion, but not successful as of yet.

**Comment by LukeJelly** [comment]
@BwL1289 I was running Ubuntu 18.04 LTS at the time I believe.  If you are on that version uninstall pytest and then reinstall with out the sudo command.  That is what worked for me, if it doesn't work for you I may not be able to help you.

**Comment by BwL1289** [comment]
Thanks @LukeJelly. Im on MacOS, so may not be the same issue. Will give it a try and let you know.

**Comment by LukeJelly** [comment]
@BwL1289 I was mistaken in my last comment so I deleted it.  I was on Windows not Ubuntu.  What I was doing was launching powershell as admin then installing pytest.  If you uninstall pytest as admin, then reinstall in a non elevated command prompt it fixed it for me.  

As for MacOS, I am not super familiar with that you could try using the --user tag see if that helps!

Good luck!

**Comment by BwL1289** [comment]
Thank you!
