### ISSUE TITLE
[Question] - Collecting all tests results after the execution with pytest-xdist

### ISSUE THREAD

**Issue by PeterNgTr** [pytest-dev/pytest-xdist#452]
Hi, I'm a new to python world and pytest in particular. xdist would be an amazing plugin that reduces the execution time dramatically. There is a question that I haven't found any answers yet. My current setup is with pytest, pytest-xdist and pytest-testrail to publish the test results after the run. The issue is when using xdist, pytest-testrail plugin creates Test-Run for each xdist workers and then publishes test cases like Untested. I would like to ask if there is any hook for instance to collect the final tests results when all the workers are completed.

**Comment by RonnyPfannschmidt** [comment]
pytest-testrail should only create one run for the entire set of workers,
to me that seems like a missing feature/bug in pytest-testrail

**Comment by PeterNgTr** [comment]
Hi @RonnyPfannschmidt, thanks for your answer. So far it is used to collect the report:
```
    @pytest.hookimpl(tryfirst=True, hookwrapper=True)
    def pytest_runtest_makereport(self, item, call):
        """ Collect result and associated testcases (TestRail) of an execution """

        outcome = yield
        rep = outcome.get_result()
        if item.get_closest_marker(TESTRAIL_PREFIX):
            testcaseids = item.get_closest_marker(TESTRAIL_PREFIX).kwargs.get('ids')

            if rep.when == 'call' and testcaseids:
                self.add_result(
                    clean_test_ids(testcaseids),
                    get_test_outcome(outcome.get_result().outcome),
                    comment=rep.longrepr,
                    duration=rep.duration
                )
```

and this one to create test run in testrail
```
    def pytest_sessionfinish(self, session, exitstatus):
        """ Publish results in TestRail """
        print('[{}] Start publishing'.format(TESTRAIL_PREFIX))
        if self.results:
            self.create_test_run(
                self.assign_user_id,
                self.project_id,
                self.suite_id,
                self.include_all,
                self.testrun_name,
                self.tr_keys
            )
            tests_list = [str(result['case_id']) for result in self.results]
            print('[{}] Testcases to publish: {}'.format(TESTRAIL_PREFIX, ', '.join(tests_list)))

            if self.testrun_id:
                self.add_results(self.testrun_id)
            elif self.testplan_id:
                testruns = self.get_available_testruns(self.testplan_id)
                print('[{}] Testruns to update: {}'.format(TESTRAIL_PREFIX, ', '.join([str(elt) for elt in testruns])))
                for testrun_id in testruns:
                    self.add_results(testrun_id)
            else:
                print('[{}] No data published'.format(TESTRAIL_PREFIX))

            if self.close_on_complete and self.testrun_id:
                self.close_test_run(self.testrun_id)
            elif self.close_on_complete and self.testplan_id:
                self.close_test_plan(self.testplan_id)
        print('[{}] End publishing'.format(TESTRAIL_PREFIX))
```
I'm not sure if the hook is proper called there.

**Comment by RonnyPfannschmidt** [comment]
i believe if instead of reporting, you add a report id in, then you should be able to do all the actual report collection and writing using the logreport hook on the main process

**Comment by PeterNgTr** [comment]
Would be nice if you show me some example references to do that, I'm just knowing python, pytest. It's not an easy thing for me. Thanks so much @RonnyPfannschmidt

**Comment by RonnyPfannschmidt** [comment]
@PeterNgTr unfortunately im not able to whip something up quickly, but i believe the built-in junitxml plugin as well as its data collection/the property recording fixtures are a good example of a mechanism to pass this data on

**Comment by PeterNgTr** [comment]
@RonnyPfannschmidt thanks for your fast answer. I would deep dive in them a bit.

**Comment by tetienne** [comment]
@PeterNgTr Did you manage to find a solution?

**Comment by PeterNgTr** [comment]
@tetienne yes, I did find a way to make it work.

**Comment by tetienne** [comment]
@PeterNgTr What was your solution?

**Comment by PeterNgTr** [comment]
> @PeterNgTr What was your solution?

well, @tetienne, not a clean solution, but at least it works, enabling the xml report when running tests, after the execution, extracting the results on xml report and publishing data to testrail via testrail apis.
