### ISSUE TITLE
different tests were collected between gw3 and gw1. the difference is

### ISSUE THREAD

**Issue by jade-li1115** [pytest-dev/pytest-xdist#455]
i have searched alot i still couldnt fix this issue
![image](https://user-images.githubusercontent.com/53292092/61938000-b5cae500-afc2-11e9-943c-8d9eeeb73cf1.png)

**Comment by RonnyPfannschmidt** [comment]
with the provided information we have no idea what could be the cause in your case,
please provide examples from the fixture declarations/parameter declarations

**Comment by jade-li1115** [comment]
> with the provided information we have no idea what could be the cause in your case,
> please provide examples from the fixture declarations/parameter declarations

like if i use Parcharm running case ,its no problem,but if i want to xdist command like :pytest -n 3 Test_kline.py,then will be wrong

**Comment by RonnyPfannschmidt** [comment]
again, please how examples of the parameter declarations and fixture definitions

based  on the output there are lots of details involved that don'd even indicate on the id list

**Comment by jade-li1115** [comment]
now i have new issues.........TypeError: __call__() got an unexpected keyword argument 'warn_on_impl'
![image](https://user-images.githubusercontent.com/53292092/62432181-daf8e980-b760-11e9-90fd-32f26e454d07.png)

**Comment by jade-li1115** [comment]
> again, please how examples of the parameter declarations and fixture definitions
> 
> based on the output there are lots of details involved that don'd even indicate on the id list

now ia habe new issues .........TypeError: call() got an unexpected keyword argument 'warn_on_impl'
![image](https://user-images.githubusercontent.com/53292092/62432196-ff54c600-b760-11e9-9e25-52e97cf3f0ff.png)

**Comment by jade-li1115** [comment]
> again, please how examples of the parameter declarations and fixture definitions
> 
> based on the output there are lots of details involved that don'd even indicate on the id list

now i have  new issues .........TypeError: call() got an unexpected keyword argument 'warn_on_impl'
image

**Comment by jade-li1115** [comment]
> again, please how examples of the parameter declarations and fixture definitions
> 
> based on the output there are lots of details involved that don'd even indicate on the id list

![image](https://user-images.githubusercontent.com/53292092/62440684-c67a1880-b783-11e9-9dde-efc112d087a2.png)
![image](https://user-images.githubusercontent.com/53292092/62440779-2a9cdc80-b784-11e9-8a13-efe2631dca1f.png)

**Comment by RonnyPfannschmidt** [comment]
using random samples makes collection non-deterministic and different between runs,
so this is a user-error and expected to happen

**Comment by jade-li1115** [comment]
> using random samples makes collection non-deterministic and different between runs,
> so this is a user-error and expected to happen

thank you for helping my issue, i still dont know how i can change it:((

**Comment by jade-li1115** [comment]
> using random samples makes collection non-deterministic and different between runs,
> so this is a user-error and expected to happen

do you mean becuase this 
![image](https://user-images.githubusercontent.com/53292092/62447441-f206fe00-b797-11e9-93d9-3ef58b38450c.png)?????

**Comment by jade-li1115** [comment]
> using random samples makes collection non-deterministic and different between runs,
> so this is a user-error and expected to happen
![image](https://user-images.githubusercontent.com/53292092/62447534-309cb880-b798-11e9-8f09-ab07b250faae.png)
i just cancelled it still didnt work:((

**Comment by RonnyPfannschmidt** [comment]
there is one for stocks as well

**Comment by jade-li1115** [comment]
> there is one for stocks as well

now it is ok:))),thank you!
