### ISSUE TITLE
Allow richer expressions in -n auto

### ISSUE THREAD

**Issue by gappleto97** [pytest-dev/pytest-xdist#477]
It would be nice if we could put things like `pytest -n auto-1` and have it correctly interpret that as "all CPUs except 1". This ensures that the processor is not hogged by tests, but also that it runs at a very fast clip.

Could be done something like:

```python
cores = 1
if 'auto' in args.n:
    cores = cpu_count()
    if '-' in args.n:
        cores -= int(args.n.split('-')[1])
    elif args.n != 'auto':
        raise ValueError("Invalid option given!")
else:
    cores = int(args.n)
```

**Comment by RonnyPfannschmidt** [comment]
im -10 on this - not going to add a mini pseudo programming language into a option

**Comment by chrahunt** [comment]
This can be done directly in shell, no reason to implement it in xdist.

```
pytest -n $(($(lscpu | awk '/CPU\(s\)/ {print $2; exit}') - 1))
```

There's probably similar for Powershell.

**Comment by nicoddemus** [comment]
I agree, closing as "won't fix"

**Comment by graingert** [comment]
auto_detect_cpus is now a bit more complicated:

https://github.com/pytest-dev/pytest-xdist/blob/59caed8e2fed326746d899a85b62924408df6a2b/src/xdist/plugin.py#L8-L28


```python
pytest --numprocesses=$(python -c 'print(__import__('pytest.plugin').plugin.auto_detect_cpus() - 1)')
```

**Comment by stas00** [comment]
> auto_detect_cpus is now a bit more complicated:
> 
> https://github.com/pytest-dev/pytest-xdist/blob/59caed8e2fed326746d899a85b62924408df6a2b/src/xdist/plugin.py#L8-L28
> 
> ```python
> pytest --numprocesses=$(python -c 'print(__import__('pytest.plugin').plugin.auto_detect_cpus() - 1)')
> ```

that didn't work. 

here is a fixed version
```
# count
python -c "print(__import__('xdist.plugin').plugin.auto_detect_cpus() - 1)"
# feed that to pytest
pytest --numprocesses=$(python -c "print(__import__('xdist.plugin').plugin.auto_detect_cpus() - 1)")
```
