### ISSUE TITLE
rtd builds fail since a while 

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest-xdist#484]
https://readthedocs.org/projects/pytest-xdist/ - noted when looking for the docs, things fall appart

**Comment by nicoddemus** [comment]
We never had docs for pytest-xdist, did we?

**Comment by nicoddemus** [comment]
Yes, I don't think it ever built: https://pytest-xdist.readthedocs.io/en/latest/

I think we just wanted to save the pytest-xdist name in RTD

**Comment by RonnyPfannschmidt** [comment]
I wonder why there is a rtd set up

**Comment by ssbarnea** [comment]
@RonnyPfannschmidt @nicoddemus As I seen that we have a huge number of open bugs that are like 4+ years old and likely obsolete, maybe it would worth setting a bot to close old issues, unless someone reconfirms it. I would do it to clean-up the tracker but I do not have access for that. WDYT?

PS. I did some manual cleanup but there are lots of cases where the close action should be done only if OP does not re-confirm it as still valid with latest version.

**Comment by nicoddemus** [comment]
Thanks @ssbarnea for offering to help here. Definitely the pytest-xdist issues could use some grooming.

Just added you as maintainer here, let me know if you need anything else. 👍
