### ISSUE TITLE
[Question]: Delivering fixture results on one off expensive tasks with xdist

### ISSUE THREAD

**Issue by symonk** [pytest-dev/pytest-xdist#489]
Hi, I have been using xdist for quite some time now and one major flaw I have (and hope a workaround exists for) is:

When using a fixture to yield some value of something that can ONLY run once for ALL tests, something expensive like starting a mountbank server, how can you have all tests use the same server and yield such server object from a fixture?

Traditional session scopes fixtures will run on every xdist worker, and they will also try shut the server down post yield as soon as their batch of tests has completed, killing the server for tests on another process that still may need it.

Is there a simple solution to this? My alternative is starting and stopping the mountbank instance in a plug-in on master only, it sucks! I can’t inject the value into tests from that, any advice?

**Comment by nicoddemus** [comment]
Hi @symonk,

There's no simple solution to this currently, your approach of using a plugin which only does its work on the `master` node seems to be a good approach. Take a look at [the docs](https://github.com/pytest-dev/pytest-xdist#making-session-scoped-fixtures-execute-only-once) for an alternative, but it doesn't cover the case of shutting down the server only when all tests have finised.

Closing for now, feel free to follow up with further questions.
