### ISSUE TITLE
Poor interaction between `-n#` and `--collect-only`

### ISSUE THREAD

**Issue by soltanmm** [pytest-dev/pytest-xdist#5]
Specifying e.g. `-n8` to py.test causes tests to run regardless of whether or not the `--collect-only` flag is set (version is latest from PyPI as of this post; 1.13.1). This was attempted by invoking `py.test` directly rather than by using e.g. a `setup.py` shim. This is a paper-cut.

**Comment by RonnyPfannschmidt** [comment]
duplicate of #6

**Comment by allanlewis** [comment]
I'm seeing this with `pytest==2.9.2` and `pytest-xdist=1.14`, irrespective of other options, including specifying a config file with `-c`; see #6.
