### ISSUE TITLE
Test failure with pytest master

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-xdist#510]
The removal of `_tmpdirhandler` from the config object (https://github.com/pytest-dev/pytest/commit/8a1633c3b4a75caff946c1fb5fefaa73f61e5556, https://github.com/pytest-dev/pytest/pull/6767) breaks https://github.com/pytest-dev/pytest-xdist/blob/136663a5c7b8ea43c154a8505ff70d0d79adbccb/src/xdist/workermanage.py#L255-L257.

Tested in https://github.com/pytest-dev/pytest-xdist/blob/136663a5c7b8ea43c154a8505ff70d0d79adbccb/testing/acceptance_test.py#L118-L129.

Ref: https://github.com/pytest-dev/pytest-xdist/commit/5ddef63085725d2d5f3e6d87cad3d23cb99b557a / #22

**Comment by RonnyPfannschmidt** [comment]
im not aware of a structural fix, we might have to revert https://github.com/pytest-dev/pytest/pull/6767 until we come up with one
