### ISSUE TITLE
'unrecognized arguments: -n' under the   py3env  environment

### ISSUE THREAD

**Issue by invokermoon** [pytest-dev/pytest-xdist#526]
Hi Master,
    error info:
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
  inifile: None
  rootdir: /home/sherlock/eclipse-workspace/epool-scoket

And  This is my environment:
source /home/pyenv/py3env/bin/activate

My step:
1.   source /home/pyenv/py3env/bin/activate
2.   pip install pytest-xdist  
3.   pytest -n 5

**Comment by RonnyPfannschmidt** [comment]
whats the output of `pytest --version`

**Comment by changchiyou** [comment]
i got the same error:

```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
  inifile: None
  rootdir: /xxx/xxx/xxx/xxx
```

`pytest --version`: `pytest 7.3.1`
`pip show pytest-xdist`:

```
Name: pytest-xdist
Version: 3.3.1
Summary: pytest xdist plugin for distributed testing, most importantly across multiple CPUs
Home-page: https://github.com/pytest-dev/pytest-xdist
Author: holger krekel and contributors
Author-email: pytest-dev@python.org,holger@merlinux.eu
License: MIT
Location: /Users/xxx/.cache/trunk/tools/python/3.10.8-214aeca7186675d6b0eef99195843b4a/lib/python3.10/site-packages
Requires: execnet, pytest
Required-by:
```

**Comment by RonnyPfannschmidt** [comment]
Closing this issue as it wasn't originally answered to help solve the original issue

@changchiyou please open a new issues where you also elaborate on tooling,path and python path as the output suggests the usag off tools for managing your python that seem very niche
