### ISSUE TITLE
Feature Request: `--looponfail-checkinterval` option to set `StatRecorder.waitonchange` sleep time

### ISSUE THREAD

**Issue by Jasha10** [pytest-dev/pytest-xdist#540]
I am interested in making the `--looponfail` option faster, so that the call to `looponfail.StatRecorder.check` will happen more frequently. I think that the call to `statrecorder.waitonchange(checkinterval=2.0)` in the `looponfail.looponfail_main` function is the culprit; a sleep time of `2.0` seconds is hardcoded in.

Perhaps we could add a `--looponfail-checkinterval` command-line flag so that users have the option to set a different `checkinterval`. Any thoughts?

**Comment by RonnyPfannschmidt** [comment]
There is a unwritten plan to move looponfail to a new plugin and supporting file system watching for real time starting

**Comment by Jasha10** [comment]
I see.
