### ISSUE TITLE
Provide an environment variable to set the number of CPUs used (-n) 

### ISSUE THREAD

**Issue by arthurzenika** [pytest-dev/pytest-xdist#547]
First off thanks for `pytest-xdist`, we use it on a number of projects to speed up tests and that helps developers a lot to be able to run more test and have quicker feedback. 

When we run those same tests in our CI we would like to have gitlab or jenkins or kubernetes set the number of CPUs those tests should use. For example in kubernetes the load is badly spread out when a job sees 4 CPUs and spread out the test, in some cases like the infrastructure is probably better used by throttling the number of CPUs to avoid disturbing neighbor pods and processes. 

It would be awesome to be able to set this using an environment variable instead of asking each project to add a `-n` to their `.gitlab-ci.yml` or `tox.ini` or `JenkinsFile`. 

Thanks in advance for your input. 

While we're on this subject have you take a look at https://bugs.python.org/issue36054  ?

**Comment by graingert** [comment]
xdist does use os.sched_getaffinity

https://github.com/pytest-dev/pytest-xdist/blob/master/src/xdist/plugin.py#L10

so I presume when https://bugs.python.org/issue36054 is fixed this will no longer happen?

**Comment by bluetech** [comment]
You can use `PYTEST_ADDOPTS="-n auto"` for this.
