### ISSUE TITLE
When using "-n auto", count the number of physical CPU cores instead of logical ones

### ISSUE THREAD

**Issue by utapyngo** [pytest-dev/pytest-xdist#553]
I have a laptop with 6 physical CPU cores and hyper-threading. The code from [auto_detect_cpus](https://github.com/pytest-dev/pytest-xdist/blob/master/src/xdist/plugin.py#L8) gives 12:

```
from os import sched_getaffinity
len(sched_getaffinity(0))
Out[24]: 12
```

The optimal number of parallel processes though is 6. Tests run slower when using 12 processes.
Did you consider using `psutil.cpu_count(logical=False)`?

**Comment by wei-hai** [comment]
+1

**Comment by RonnyPfannschmidt** [comment]
Psutil has not been considered as dependency yet

**Comment by Zac-HD** [comment]
For what it's worth this would be very useful for me too, and I wouldn't mind adding a dependency on `psutil` to support it.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt anything against depending on `psutil`? Seems like a pretty popular and stable package.

Even if we decide to no depend on it explicitly, we can optionally use `cpu_count(logical=False)` only when `psutil` is available.

**Comment by RonnyPfannschmidt** [comment]
There ist nothin against it

**Comment by AdrienPensart** [comment]
Guys you changed something important there, now, how can we specify $(nproc) in pytest.ini or pyproject.toml ?
If -n auto does not work anymore, the tests are not adapted when ran on different kind of machines :/

**Comment by nicoddemus** [comment]
Hi @AdrienPensart, 

> If -n auto does not work anymore, the tests are not adapted when ran on different kind of machines :/

`-n auto` should still be working... can you open an issue if it is not working for you?
