### ISSUE TITLE
Revamp progress output when collecting workers

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-xdist#555]
We might want to review the progress message that happens while workers are being collected, because some people find it too verbose (https://github.com/pytest-dev/pytest-xdist/issues/423), or wonder what `gw` stands for (that's gateway, which an execnet concept).

Currently we have:

## default

collecting:

```
==============================
plugins: forked-1.2.0, xdist-1.32.1
gw0 [0] / gw1 [0]
```

done:

```
==============================
plugins: forked-1.2.0, xdist-1.32.1
gw0 [156] / gw1 [156]
```

## verbose

collecting:

```
==============================
plugins: xdist-1.31.0
[gw0] win32 Python 3.7.6 cwd: d:\projects\pytest-xdist
[gw1] win32 Python 3.7.6 cwd: d:\projects\pytest-xdist
[gw0] Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
[gw1] Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
gw0 [0] / gw1 [0]
```

done:

```
==============================
plugins: xdist-1.31.0
[gw0] win32 Python 3.7.6 cwd: d:\projects\pytest-xdist
[gw1] win32 Python 3.7.6 cwd: d:\projects\pytest-xdist
[gw0] Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
[gw1] Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
gw0 [156] / gw1 [156]
```

---

To remove the `gw` term and reduce the output problems when having too many workers, how about:

## default

collecting:

```
==============================
plugins: forked-1.2.0, xdist-1.32.1
collecting: 1/8 workers...
```

done:

```
==============================
plugins: forked-1.2.0, xdist-1.32.1
2 workers [156 items]
```

## verbose

collecting:

```
==============================
plugins: xdist-1.31.0
[w0] win32 Python 3.7.6 cwd: d:\projects\pytest-xdist
[w1] win32 Python 3.7.6 cwd: d:\projects\pytest-xdist
[w0] Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
[w1] Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
collecting: 1/8 workers...
```

done:

```
==============================
plugins: xdist-1.31.0
[w0] win32 Python 3.7.6 cwd: d:\projects\pytest-xdist
[w1] win32 Python 3.7.6 cwd: d:\projects\pytest-xdist
[w0] Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
[w1] Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
2 workers [156 items]
```

And in case we are running workers for the same interpreter, we even don't print the `[w*]` lines with interpreter/xdist information because they are redundant.

**Comment by bhipple** [comment]
> And in case we are running workers for the same interpreter, we even don't print the [w*] lines with interpreter/xdist information because they are redundant.

This sounds great to me.  In my case I'm running with 72 workers that are all identical to the main python, so I'd prefer to just see nothing (even with `-v`).

**Comment by ssbarnea** [comment]
I would be more than happy to see some improvement here because, that "gw" output is confusing at best and really spammy in some cases.

![](https://sbarnea.com/ss/Screen-Shot-2023-05-05-17-27-44.99.png)

I have being using pytest for years, with xdist and I still find no use for that logging. The image about is from vscode output window.

At least it would be useful to have a way to disable it, but without affecting the normal progress of test execution.
