### ISSUE TITLE
Don't distribute but send all tests to different CPUs

### ISSUE THREAD

**Issue by marincandenza** [pytest-dev/pytest-xdist#576]
Dear pytest developers,

is it possible to run all tests on different CPUs? 
Example: 100 tests included in the repository, three CPUs used -> 300 tests will be executed. 

I'm asking because we have different devices connected to a host and therefore want to execute all tests against the connected devices.
Of course, it is possible to execute pytest three times from command line but having a single report and in Gitlab CI one stage only would simplify the CI workflow. 

Kind regards
Mario

**Comment by RonnyPfannschmidt** [comment]
It's not quite clear what you are asking for, but `--dist=each` sounds like what you might want, for a better suggestion we need a more comprehensible description of your use case

**Comment by marincandenza** [comment]
@RonnyPfannschmidt Great, thank you. `--dist=each` does exactly what I want.
