### ISSUE TITLE
Pytest-django test DB's and pytest-xdist 2.0

### ISSUE THREAD

**Issue by tolomea** [pytest-dev/pytest-xdist#584]
FYI It looks like the 2.0 release broke something with pytest-django. No idea what's going on just thought I should mention it in case you haven't seen this https://github.com/pytest-dev/pytest-django/issues/860

**Comment by nicoddemus** [comment]
Thanks!

Seems fixed by https://github.com/pytest-dev/pytest-django/pull/861. 👍
