### ISSUE TITLE
Limit number of workers spawned

### ISSUE THREAD

**Issue by jdahlin** [pytest-dev/pytest-xdist#586]
The number of workers launched should be capped at the number of collected tests. At least when running auto.

I'm not sure if it's already possible to do this, I couldn't find it in the documentation or code. I'm not sure if the data from the collection phase is available to the plugin and if it's possible to delay the spawn until it's complete.

**Comment by RonnyPfannschmidt** [comment]
Collection happens after spawning,
So as of now this is not possible

**Comment by jdahlin** [comment]
@RonnyPfannschmidt That's too vad. What would be the implications of moving spawning to post collection? Would a configuration option be doable?

**Comment by RonnyPfannschmidt** [comment]
It would currently just add extra costs, as each node starts as a empty python process that then runs a complete xdist worker session that has to do collection anyway

**Comment by nicoddemus** [comment]
Closing as it doesn't seem to have a simple solution in the current design/implementation.
