### ISSUE TITLE
received 'error: unrecognized arguments: -n' running pytest tests

### ISSUE THREAD

**Issue by dkuchynskyi** [pytest-dev/pytest-xdist#594]
Python - 3.8
pytest - 6.0.1
xdist - 2.1.0

I'm running pytest tests using pipenv with custom command line arguments:
pipenv run python -m pytest -m smoke --p local:desktop -n 2
but an error appears
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: -n

Could you please help with it?
thanks

**Comment by nicoddemus** [comment]
doesn't seem like `pytest-xdist` is installed in that environment... try running:

```
$ pipenv run python -m pytest --version --version
```

**Comment by dkuchynskyi** [comment]
yes, in some way it was installed but not registered as a plugin. needed to delete manually python virtual environment and reinstall all dependencies
thanks
