### ISSUE TITLE
Poor interaction between `-n#` and `-c X.cfg`

### ISSUE THREAD

**Issue by soltanmm** [pytest-dev/pytest-xdist#6]
Specifying e.g. `-n8` appears to cause py.test options in config files e.g.

```
[pytest]
python_files = *_test.py
```

to be ignored when they're specified by invocations of the form `py.test -c /something/elsewhere/setup.cfg -n8`. This doesn't appear to be a problem when invoking py.test directly in a `setup.py` [shim](https://github.com/grpc/grpc/blob/master/src/python/grpcio_test/commands.py#L39) s.t. the `setup.cfg` is automagically found by py.test.

I've only stared at this for a little while, however, and may have missed a few things. Pointers?

cc @nathanielmanistaatgoogle

**Comment by RonnyPfannschmidt** [comment]
I'm not sure I understand, can you perhaps create an example project

**Comment by soltanmm** [comment]
[Certainly](https://github.com/soltanmm/case-samples/tree/pytest-dev--pytest-xdist--6).

To replicate the error, add some out-of-tree setup.cfg file
```
[pytest]
python_files = *
```

... to some path `$OTHER_SETUP`, create a virtualenv, and pip install the example project.

The invocations to replicate are then: `./bin/py.test -c $OTHER_SETUP --pyargs mypkg -v` vs. `./bin/py.test -c  $OTHER_SETUP -n8 --pyargs mypkg -v`.

The first command should fail because it's using the `$OTHER_SETUP` file which selects for all python files, although one of the tests really shouldn't be ran. The second command erroneously succeeds because it appears to ignore the bad configuration file.

(I apologize for the double negative example; was in a hurry)

**Comment by RonnyPfannschmidt** [comment]
should be fixed in the pytest feature branch

**Comment by nicoddemus** [comment]
@soltanmm could you please verify if the `features` branch fixes this, as @RonnyPfannschmidt mentioned? If that's the case we could close this.

**Comment by dubglan** [comment]
@RonnyPfannschmidt, we're observing the same behavior from issue #5 with pytest==2.9.1 and pytest-xdist==1.14:
Runs tests:
`.../py.test --collect-only -n 3`
Prints the list of tests:
`.../py.test --collect-only -n 0`

**Comment by davehunt** [comment]
Was this resolved by https://github.com/pytest-dev/pytest-xdist/pull/232?

**Comment by RonnyPfannschmidt** [comment]
nope

**Comment by davehunt** [comment]
> nope

Okay, I asked because https://github.com/pytest-dev/pytest-xdist/issues/5#issuecomment-147689151 suggests that this is a duplicate issue. Thanks.

**Comment by RonnyPfannschmidt** [comment]
@davehunt this one is due to broken config handling in pytest - due to completely broken initialization of the pytest config, the initialization in xdist worker processes is inconsistent and different from the controlling process
