### ISSUE TITLE
 The use case has changed, but the result has not changed

### ISSUE THREAD

**Issue by yili1992** [pytest-dev/pytest-xdist#603]
by sending tests to remote Socket Servers:
First executon:
```
assert res.status_code == 201
```
First socketserver output:
![截屏2020-10-27 下午7 34 50](https://user-images.githubusercontent.com/3176589/97296366-883aae80-188b-11eb-8bba-e2aab74aae0d.png)

Second executon:
```
assert res.status_code == 200
```
Second socketserver output:
![截屏2020-10-27 下午7 35 05](https://user-images.githubusercontent.com/3176589/97296372-8a9d0880-188b-11eb-9ce3-7807b44e34dc.png)
In second socketserver output, I found the source code was modified ,but the assertion is failed yet.
My socket server did not restart during execution

**Comment by RonnyPfannschmidt** [comment]
That is a general problem with execnet socket server's, it's not fixable as execnet is unmaintained
