### ISSUE TITLE
Distribute parameterized tests to different workers

### ISSUE THREAD

**Issue by tomzx** [pytest-dev/pytest-xdist#604]
Hello!

One issue I currently face is that I have a test which takes a long time to execute (~2 minutes). This test itself is parameterized, let say with 8 options. This means that this test will take 16 minutes to complete. In this case, it would make more sense for me if each parameterized instance of the test was considered a different test and as such would be distributed to a different worker, which could potentially bring this test down to 2 minutes.

``` 
@pytest.mark.parametrize("random", range(0, 8))
def test_lasting_2_minutes(random: int):
   # do something lasting 2 minutes
```

From a quick inspection of the `pytes-dist` code I understand that the parameterized tests are considered individual tests, it is that they are chunked as a single unit and sent to the same node that causes the issue here.

**Comment by nicoddemus** [comment]
Hi @tomzx,

Right now the only option to actually customize the distribution mode would be to implement your own scheduler and the `pytest_xdist_make_scheduler` hook; unfortunately there isn't documentation on that yet, but the implementation of the current schedulers is a good starting point. 👍

**Comment by cslominski** [comment]
This would be a nice feature to have!
