### ISSUE TITLE
Link to socketserver.py is dead 

### ISSUE THREAD

**Issue by MatejKoplan** [pytest-dev/pytest-xdist#606]
When reading through the documentation I discovered that the link to socketserver.py is dead. 

Chapter: Sending tests to remote Socket Servers
Link: https://bitbucket.org/hpk42/execnet/raw/2af991418160/execnet/script/socketserver.py

I haven't discovered an alternative anywhere else yet.

**Comment by RonnyPfannschmidt** [comment]
https://www.github.com/pytest-dev/execnet/tree/master/execnet%2Fscript%2Fsocketserver.py

**Comment by MatejKoplan** [comment]
Thanks. 
Now I see that the link is fixed here, but is still incorrect on:
https://pypi.org/project/pytest-xdist/ and 
https://docs.pytest.org/en/3.0.1/xdist.html , which redirects to the newest version of the page (but that version is just an empty page): https://docs.pytest.org/en/6.1.2/xdist.html.

This user opened a similar ticket on pytest's github page: https://github.com/pytest-dev/pytest/discussions/8029

**Comment by RonnyPfannschmidt** [comment]
I put it here as I am currently on mobile and can't fix it, feel free to give it a try

**Comment by MatejKoplan** [comment]
As far as I understand the new version just needs to be published to those sites, since the fix is already merged into master. I'm not sure what I can do.

**Comment by nicoddemus** [comment]
We really only maintain links for the current documentation, old docs like 3.0.1 are not maintained anymore (in fact don't even have a branch associated anymore). Sorry but doing so would be too high a maintenance burden.

Closing this for now, but feel free to follow up with further questions.
