### ISSUE TITLE
Hello, About -- Dist usage

### ISSUE THREAD

**Issue by meilisong1989** [pytest-dev/pytest-xdist#607]
Hello, I want to implement a set of use cases grouped in order, and then execute more concurrently. How do I do that?

Scene:
Now I have a lot of modules. Due to business reasons, I cannot use Pytest-n to run, which will cause data chaos. Can I make the modules run in the specified process in the order that I specify? 
For example, three modules walk through three different processes, and each process executes the test set in the module sequentially

**Comment by symonk** [comment]
Hi @meilisong1989 have you tried this:

`pytest -n=X --dist=loadfile` # This groups items by test file

I am not 100% on your question, but it sounds like you have no choice but to run sequentially in which case `xdist` is probably not what you are after, but perhaps an implementation of `pytest_collection_modifyitems` in a internal plugin / entry point loaded plugin which can organize the items (in-place) to execute in whatever order you desire.

**Comment by meilisong1989** [comment]
very thankful，

But then, can the use cases in the directories of module A and Module B be executed sequently in different processes?

I am now able to do this in a multi-process way, but only to combine test reports, such as:

def func(name, report, modules):
	print(f"my{name}")
	# time.sleep(random.randrange(1, 30))
	# print(f"{name}finish {report},{modules}")
	os.system(f"pytest -v {modules} --html={report}")


if __name__ == '__main__':
	p1 = Process(target=func, args=("process1",), kwargs={"report": "11.html", "modules": "mod1"}) 
	p2 = Process(target=func, args=("process2",), kwargs={"report": "22.html", "modules": "mod3"})
	p1.start() 
	p2.start() 

I don't know if pytest-n X --dict= loadFile works the same way, right?

**Comment by meilisong1989** [comment]
pytest -n=2 mod4 mod3  -v --dist=loadfile

I just tried this again. If I have more than one.py file under mod1, it's going to be processed by more than one process. I want only one process to execute

[gw1] [  9%] PASSED mod4/test_mod4_module2.py::test_mode4_one2
[gw0] [ 18%] PASSED mod4/test_mod4_module.py::test_one

I don't want GW1 to handle the use cases below MOD4, and GW0 to handle only the use cases below MOD3. Is there a way
