### ISSUE TITLE
Extra output in quite mode and --show-capture=stderr

### ISSUE THREAD

**Issue by abyss7** [pytest-dev/pytest-xdist#613]
I run my tests using command line:

    pytest tests/queries --builddir=build -q -n 80 --timeout=600 --html=test_output/report.html --self-contained-html -x --show-capture=stderr

And the output looks like:

> ========================================================================================== FAILURES ===========================================================================================
> ______________________________________________________________________ test_sql_query[01511_prewhere_with_virtuals.sql] _______________________________________________________________________
> [gw70] linux -- Python 3.8.6 /usr/bin/python3.8
> [gw70] linux -- Python 3.8.6 /usr/bin/python3.8[gw70] linux -- Python 3.8.6 /usr/bin/python3.8
> Client died unexpectedly with code 210
> …

I can't find where the multiple `[gw70] linux -- Python 3.8.6 /usr/bin/python3.8` are coming from. I don't print them by myself for sure and I can't find the related source code in extension. Also sometimes these lines get mixed with my output.

Anyway I think that in quite mode they shouldn't be printed by any means. Any workaround for current version is appreciated.

**Comment by wassupxP** [comment]
Hi, this is duplicated by https://github.com/pytest-dev/pytest-html/issues/462 in my opinion, have you found any workaround yet?

**Comment by abyss7** [comment]
@wassupxP yes, looks like your problem has the same cause as this one. And no, I haven't found any workaround yet.

**Comment by ugomancz** [comment]
Just to let anyone interested know, this issue has been fixed by pytest-html plugin. At least since version 4.0.3.

**Comment by nicoddemus** [comment]
Thanks for the info @ugomancz, closing this then. 👍
