### ISSUE TITLE
Python3.7.3版本下执行运行分布式测试代码，报没有： '_pytest.resultlog'模块

### ISSUE THREAD

**Issue by yuxuan6699** [pytest-dev/pytest-xdist#616]
Python3.7.3版本下执行运行分布式测试代码，报没有： '_pytest.resultlog'模块 @svenstaro @sah @EdwardBetts @blueyed 
![image](https://user-images.githubusercontent.com/53070072/103611688-c0cac880-4f5d-11eb-881f-17ec7155cd74.png)

**Comment by RonnyPfannschmidt** [comment]
Bug in pytest-rerunfailures
