### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by staticdev** [pytest-dev/pytest-xdist#617]
Is it planned?

**Comment by RonnyPfannschmidt** [comment]
currently there is no plan,

personally i cant pick it up soon either - perhaps someone from @pytest-dev/core can chime in

**Comment by asottile** [comment]
the tests pass, is there something specific you're looking for @staticdev ?

**Comment by staticdev** [comment]
great, maybe would be nice to update the CI/documentation regarding that.

**Comment by symonk** [comment]
Are we currently running with tox for 3.9?

**Comment by asottile** [comment]
> 
> 
> @asottile great, maybe would be nice to update the CI/documentation regarding that.

it... is? https://github.com/pytest-dev/pytest-xdist/blob/ad99d943de4b0f14511dad48ee148f6ab8abacd7/.github/workflows/main.yml#L33-L34

**Comment by staticdev** [comment]
perfect, just the reading was misleading, this #618 fix that =)
