### ISSUE TITLE
can't run pytest-xdist use freeze pytest by pyinstaller

### ISSUE THREAD

**Issue by BoyOoka** [pytest-dev/pytest-xdist#619]
I use pyinstaller freeze pytest
code like 

> #contents of app_2.py
> #-*- coding:utf-8 -*-
> import sys
> import pytest_timeout
> from xdist import plugin as xdist_plugin
> from xdist import looponfail as xdist_looponfail
> from allure_pytest import plugin as allure_plugin
> from execnet import _version
> from execnet import deprecated
> from execnet import gateway
> from execnet import gateway_base
> from execnet import gateway_bootstrap
> from execnet import gateway_io
> from execnet import gateway_socket
> from execnet import multi
> from execnet import xspec
> if len(sys.argv) > 1 and sys.argv[1] == "--pytest":
>     &nbsp;&nbsp;&nbsp;&nbsp;import pytest
>     &nbsp;&nbsp;&nbsp;&nbsp;sys.exit(pytest.main(sys.argv[2:], plugins=[pytest_timeout, xdist_plugin, allure_plugin, xdist_looponfail]))
> else:
>     &nbsp;&nbsp;&nbsp;&nbsp;pass

pyinstaller -D app_2.py -p [ProjectsPath]
then i try to run
./app_2 --pytest test_demo.py -n 4
got 

> ============================= test session starts ==============================
> platform darwin -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
> rootdir: /Users/username/projectname/test_run, configfile: pytest.ini
> gw0 I / gw1 I / gw2 I / gw3 I
> INTERNALERROR> Traceback (most recent call last):
> INTERNALERROR>   File "_pytest/main.py", line 255, in wrap_session
> INTERNALERROR>   File "pluggy/hooks.py", line 286, in __call__
> INTERNALERROR>   File "pluggy/manager.py", line 93, in _hookexec
> INTERNALERROR>   File "pluggy/manager.py", line 84, in <lambda>
> INTERNALERROR>   File "pluggy/callers.py", line 208, in _multicall
> INTERNALERROR>   File "pluggy/callers.py", line 80, in get_result
> INTERNALERROR>   File "pluggy/callers.py", line 187, in _multicall
> INTERNALERROR>   File "xdist/dsession.py", line 78, in pytest_sessionstart
> INTERNALERROR>   File "xdist/workermanage.py", line 66, in setup_nodes
> INTERNALERROR>   File "xdist/workermanage.py", line 66, in <listcomp>
> INTERNALERROR>   File "xdist/workermanage.py", line 69, in setup_node
> INTERNALERROR>   File "execnet/multi.py", line 134, in makegateway
> INTERNALERROR>   File "execnet/gateway_bootstrap.py", line 109, in bootstrap
> INTERNALERROR>   File "execnet/gateway_bootstrap.py", line 34, in bootstrap_import
> INTERNALERROR>   File "execnet/gateway_base.py", line 404, in read
> INTERNALERROR> EOFError: expected 1 bytes, got 0

**Comment by AlexPaiva** [comment]
Did you manage a fix?
