### ISSUE TITLE
Tests run sequentially near the end

### ISSUE THREAD

**Issue by sbstp** [pytest-dev/pytest-xdist#621]
Hey. I've built a large end to end test suite with pytest. I'm using xdist to parallelize it. Some tests can take more than 10 minutes to run. I've noticed that towards the end of the test run, it seems like only one worker is doing all the work and the other are not doing anything.

I've searched around and I saw a few things about the chunking algorithms, i.e. tests are discovered then chunked and then sent to each worker by default. Is there a scheduler that sends the workers things to do on an on-demand basis? Or a sort of work stealing scheduler?

Thanks.

**Comment by sbstp** [comment]
I was able to solve my problem by creating a custom scheduler which creates smaller work units before dispatching. My e2e test suite now runs in 125 minutes instead of 155 minutes.

I used the xdist scheduler hook to inject my custom scheduler in xdist.

```py
import pytest
from py.log import Producer
from xdist.scheduler import LoadScopeScheduling


class FairScheduling(LoadScopeScheduling):
    """
    FairScheduling is a custom pytest-xdist scheduler which can the amount of time required to run
    test suites with long running tests. It's able to reduce the duration by scheduling tests on workers
    in a more even fashion, by creating smaller "work-units" (groups of tests) before dispatching them
    to workers.
    """
    def __init__(self, config, log=None):
        super(FairScheduling, self).__init__(config, log)
        if log is None:
            self.log = Producer("fairched")
        else:
            self.log = log.loadfilesched

    def _split_scope(self, nodeid):
        return nodeid


@pytest.hookimpl(tryfirst=True)
def pytest_xdist_make_scheduler(config, log):
    return FairScheduling(config, log)
```

**Comment by nicoddemus** [comment]
Thanks for the follow up!
