### ISSUE TITLE
Collection fails with non-deterministic (e.g. random) parametrised tests

### ISSUE THREAD

**Issue by allanlewis** [pytest-dev/pytest-xdist#63]
I have a test that looks something like this:

``` py
@pytest.mark.parametrise('sequence', [
    [random.choice(my_list) for _ in range(n)]
])
def test_foo():
    pass  # Test implementation is irrelevant here
```

This fails at collection time with an error like:

```
collecting 0 items / 1 errors
============================================================ ERRORS =============================================================
_____________________________________________________ ERROR collecting gw1 ______________________________________________________
Different tests were collected between gw0 and gw1. The difference is:
--- gw0

+++ gw1

@@ -213,7 +213,7 @@

-test_foo.py::test_foo[[a, b, c]]
+test_foo.py::test_foo[[b, c, a]]
```

(The diff has some context and I've omitted some details specific to my environment, but hopefully it's clear.)

So it looks like `xdist` cares that each worker gets exactly the same list of tests _in the same order_: why is this? With a randomised test, I don't much care if I run with one random set of parameters or another: they're randomised on purpose. (I've also come across this issue where I generate parameters into an unordered collection like a `set`.)

Other than using a fixed seed for the RNG (e.g. `random.seed(0)`), which defeats the purpose of the randomisation, is there a workaround for this? Or can something be done inside `xdist` to permit this sort of parametrised test?

**Comment by nonatomiclabs** [comment]
AFAIK, this might be because load-balancing between different xdist processes is done dynamically. In order to determine which process will get the next test item, the collected items need to be the same across different processes.

**Comment by nicoddemus** [comment]
>  the collected items need to be the same across different processes.

Exactly; the reported collection is sent to the master node, which ensures all workers collected exactly the same test items. Then the master node sends test indexes to each slave to perform load balancing.

**Comment by allanlewis** [comment]
I understand why each worker needs the same items, but why is order important? Surely item names are unique, so the collection is more like a `set` than a `list`. Anyway, I guess this is more of a feature request: "Allow parallelisation of non-deterministic parametrised tests", or something like that.

**Comment by nicoddemus** [comment]
> I understand why each worker needs the same items, but why is order important?

It is just how things work at the moment: after ensuring every worker collected the same node ids (and in the same order), the `master` node just send test *indexes* to each worker, hence order is important. We could change that so the `master` node sends node ids instead of indexes, but there might be performance implications that should be measured, specially when using remote workers (disclosure: my gut feeling is that performance should be negligible, but should certainly be measured).

**Comment by RonnyPfannschmidt** [comment]
Actually duplicate node ids are currently possible for some edge cases (which is why collection equivalence was tightened and indexed lookup got introduced)

**Comment by nicoddemus** [comment]
Oh I didn't know that, thanks for the clarification.

**Comment by QuLogic** [comment]
That's odd, because [this test](https://github.com/pytest-dev/pytest-xdist/blob/f43a64ae592f34215fbbf8642ec30899319ead8c/testing/test_dsession.py#L284) seems to imply that duplicate test ids don't work.

**Comment by RonnyPfannschmidt** [comment]
@QuLogic https://github.com/pytest-dev/pytest-xdist/commit/18a30fab7d0cd02f203e79d314ee966708e303fa was supposed to fix this, interestingly the test didnt get unmarked

**Comment by bradmwalker** [comment]
This happens on 1.15 when using some sets in parametrized fixtures. This occurs with any set of strings.

```
@pytest.mark.parametrize('character', {' ', '\0xb', '\0xc'})
def test_invalid_character(character):
    pass
```

**Comment by RonnyPfannschmidt** [comment]
@bradmwalker sets are unordered, set up a hashseed if you want consistent order

**Comment by allanlewis** [comment]
Closing as stale.
