### ISSUE TITLE
GitHub shows very out of date release as latest

### ISSUE THREAD

**Issue by max-sixty** [pytest-dev/pytest-xdist#630]
FYI GitHub's view of the latest release is almost five years old, when it was actually less than two weeks ago:

<img width="228" alt="image" src="https://user-images.githubusercontent.com/5635139/108638199-e004b300-7442-11eb-9c3c-22c9ff40d6ed.png">

**Comment by nicoddemus** [comment]
Thanks for noticing!

Hmm that's unfortunate, as we don't publish GitHub releases (seems like that one was an experiment/accident).

**Comment by bluetech** [comment]
This is fixed now
