### ISSUE TITLE
Build failure with Python2.7 running setuptools_scm 6.0.1

### ISSUE THREAD

**Issue by mhetrerajat** [pytest-dev/pytest-xdist#639]
Our test suite uses `pytest-xdist` and the build is failing since yesterday because of the version bump in the `setuptools_scm`. This module does not pin the `setuptools_scm` which is resulting in weird failures.  

<img width="781" alt="image" src="https://user-images.githubusercontent.com/11217092/111513010-5cef2800-8776-11eb-9228-4c5efe067f64.png">

From this issue, https://github.com/pypa/setuptools_scm/issues/541 looks like pining the version is the only option to fix it.

**Comment by RonnyPfannschmidt** [comment]
Python2 is no longer supported by this library, as well, please ensure your own installation scrips handle preinstall of supported versions for dead snakes 

Please note that easy_install was deprecated since years and recent versions of setuptools completely drop the functionality

**Comment by mhetrerajat** [comment]
Thanks for the quick response @RonnyPfannschmidt.

We were not aware of the Python2 deprecation with the package. We have pinned the `pytest-xdist` to `0.16` since it used to work with Python2 but since sub-dependency is not pinned it broked. 
I will close this issue. Thanks for the help though.
