### ISSUE TITLE
[Question] Detecting parallel runs

### ISSUE THREAD

**Issue by AndreiBarsan** [pytest-dev/pytest-xdist#647]
I am using the `pytest_configure` hook to check whether my tests are running in parallel. In particular, I am checking `config.getoption("numprocesses")` and if it's set and >1, I disable multi-threading globally. 

This ensures that `torch`-based tests don't individually attempt to use multiple threads to accelerate linear algebra when the tests themselves are being run in parallel.

However, I am a bit confused about how this hook is being called. I looked through the pytest documentation but I did not find a specific answer to my question.

Specifically, if I run:

```bash
python -m pytest -n 2 myapp
```
then the hook works fine, as it gets processed before `pytest-xdist` forks. However

```bash
python -m pytest -n 2 
```
does not call the hook until after the forking happens, and then the above `getoption` always returns None, which means code can't reliably tell if it's inside a worker or not. 

(I am trying to do this at the conftest level because this is a global setting and I don't want to rely on specific fixtures checking whether the code is running in a worker or not.)

Is there a way to reliably detect if we are running >= 2 workers in both of the above cases?

**Comment by couteau** [comment]
I also have this issue. I am trying to disable certain tests when the test session is running under xdist, using the pytest_collection_modifyitems hook, but by the time that hook is called, there no longer seems to be a way to detect that the test is running in a worker thread.

**Comment by nicoddemus** [comment]
Perhaps looking at `PYTEST_XDIST_WORKER` and `PYTEST_XDIST_WORKER_COUNT` environment variables?

https://pytest-xdist.readthedocs.io/en/latest/how-to.html#identifying-the-worker-process-during-a-test

**Comment by RonnyPfannschmidt** [comment]
In pytest_configure, worker input is avaliable
