### ISSUE TITLE
How to use pytest-xdist in GitHub Actions in parallel

### ISSUE THREAD

**Issue by ma-sadeghi** [pytest-dev/pytest-xdist#648]
Hi. Sorry if my question is basic and/or has already been answered somewhere else. Anyway, is there a straightforward way to use `pytest-xdist` to distribute running unit tests across different machines in GitHub Actions? Thanks!

**Comment by RonnyPfannschmidt** [comment]
Unless you have machines, it's not possible

Someone invented pytest-split to deal with this in ci

**Comment by ma-sadeghi** [comment]
Ok, so let's say I do have two separate machines, how do I do it using `pytest-xdist`? Would it be as simple as `pytest -n NUMBER_OF_MACHINES`?

**Comment by RonnyPfannschmidt** [comment]
@ma-sadeghi its absolutely unclear what you are asking for - `-n` start multiple test runs on the same machine
what is the actual use-case
what do you want to do

**Comment by ma-sadeghi** [comment]
Sorry for the confusion. I want to use `pytest-xdist` to run pytest across multiple machines (distributed memory, not shared).

**Comment by RonnyPfannschmidt** [comment]
@ma-sadeghi in that case you need either ssh or socket servers, and its still not clear what the surrounding use-case is

**Comment by ma-sadeghi** [comment]
Thanks, I guess that works.
