### ISSUE TITLE
pytest-rerunfailures for crashed nodes

### ISSUE THREAD

**Issue by xoviat** [pytest-dev/pytest-xdist#650]
There's a hook for crashed nodes, but it doesn't let you clean-up the test failure. I'm looking for a way to contain a crashed test and rerun it.

**Comment by xoviat** [comment]
cc @RonnyPfannschmidt

**Comment by RonnyPfannschmidt** [comment]
Im not going to be able to do anything about that with the next half year, potentially longer

**Comment by xoviat** [comment]
By inspection, `remove_node` needs to be patched so as not to remove the crashitem from the pending tests. It seems that if a hook was added in `remove_node` that returned whether the crashitem should be rerun, then `pytest-rerunfailures` could take care of the rest of the logic.

**Comment by xoviat** [comment]
If I submitted a PR, would you have time to review it?

**Comment by RonnyPfannschmidt** [comment]
both me and others probably can, there should be a small design discussion beforehand,
