### ISSUE TITLE
execnet.gateway_base.DumpError: can't serialize <class '_pytest.python.Function'>

### ISSUE THREAD

**Issue by Denis-Alexeev** [pytest-dev/pytest-xdist#675]
min reproducible example:

conftest.py
```python
import pytest

@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item):
    outcome = yield
    rep = outcome.get_result()
    rep.item = item
```

test.py
```python
import pytest

def test_test():
    pass

if __name__ == '__main__':
    pytest.main([__file__, '-s', '-v', '-n 1'])
```

I understand the reason it happens. The question is: do you consider to add serialization for pytest Function in future?

**Comment by RonnyPfannschmidt** [comment]
currently its not sanely possible to serialize function

unless someone steps up to make it possible its going to stay that way

im going to close this issue as for now

**Comment by nicoddemus** [comment]
Just to complement the answer a bit: `pytest.Function` is very hard to serialize because it contains references to a bunch of objects which are not simple to serialize, like the FixtureManager.
