### ISSUE TITLE
pytest-xdist[psutil] vs -n auto

### ISSUE THREAD

**Issue by copdips** [pytest-dev/pytest-xdist#676]
Hello,

The readme says `To use psutil for detection of the number of CPUs available, install the psutil extra`,  but without psutil, just `pytest -n auto` seems to be able to set automatically the CPU number.
Could you please explain how to use `pytest-xdist[psutil]`?  and what is difference with the native `-n auto` ?

```bash
21:07 $ nproc
8

21:07 $ pytest -n auto
===================== test session starts =========================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/aa/bb, configfile: setup.cfg
plugins: forked-1.3.0, cov-2.11.1, xdist-2.3.0
gw0 [152] / gw1 [152] / gw2 [152] / gw3 [152] / gw4 [152] / gw5 [152] / gw6 [152] / gw7 [152]
.............................................................................................
```

**Comment by copdips** [comment]
@RonnyPfannschmidt 

Thx for the reply, if I understand well, it's the same usage `-n auto` with or without `pytest-xdist[psutil]`, but `pytest-xdist[psutil]` detects better the cpu number ?

**Comment by RonnyPfannschmidt** [comment]
Correct

**Comment by copdips** [comment]
> Correct
