### ISSUE TITLE
Does not appear possible to get more debug information for why slave has crashed

### ISSUE THREAD

**Issue by rekcahpassyla** [pytest-dev/pytest-xdist#68]
I apologise if there is a documentation option I missed - I've not been able to find any option to indicate this. 

I am running `pytest` with `xdist` on Windows - `python 2.7.11` from Anaconda with the following versions:

```python
pytest                    2.9.1                    py27_0    
pytest-xdist              1.13.1                   py27_0    
```

When I run using more than 1 process for example:

```
py.test -v -r a --tb=long -n 3 -m regression --max-slave-restart=0 [redacted]
```

I get some tests that crash the slaves, but I cannot see what causes the crash. If I repeat the above command line several times, different tests cause slave crashes. The same tests do not crash when run without `-n 3`. I guess it has something to do with my tests, but I don't have any information with which to debug. 

Sample output:

```python
================================== FAILURES ===================================
←[1m←[31m_ redacted.py __←[0m
[gw0] win32 -- Python 2.7.11 C:\dev\bin\Anaconda\python.exe
Slave 'gw0' crashed while running 'redacted'
←[1m←[31m_ redacted.py __←[0m
[gw2] win32 -- Python 2.7.11 C:\dev\bin\Anaconda\python.exe
Slave 'gw2' crashed while running 'redacted'
←[1m←[31m==================== 2 failed, 11 passed in 23.14 seconds =====================←[0m
```

**Comment by RonnyPfannschmidt** [comment]
you can start with the PYTEST_DEBUG and the EXECNET_DEBUG environment variables (beware of massive output

**Comment by rekcahpassyla** [comment]
Many thanks, that is exactly what I needed.
