### ISSUE TITLE
xdist doesn't allow changing test names in the report

### ISSUE THREAD

**Issue by JohnA2** [pytest-dev/pytest-xdist#684]
I want to use code like https://stackoverflow.com/a/59997589/2324685 or https://stackoverflow.com/a/61826461/2324685 that changes `report.nodeid`  in the `pytest_runtest_makereport` hook to change the test name in the html report. It works fine without xdist, but xdist triggers an AssertionError [here](https://github.com/pytest-dev/pytest-xdist/blob/348a9567242bdf9920799f548fb40a057573e3bf/src/xdist/remote.py#L120). 
```
assert self.session.items[self.item_index].nodeid == report.nodeid
```
Is it possible to remove this assert?

**Comment by RonnyPfannschmidt** [comment]
Absolutely not

It's pure luck your hack works, we won't elevate it to supported

**Comment by JohnA2** [comment]
Ok. Maybe you could suggest another way how I can change the test name in the pytest-html report? If you check the stackoverflow questions that I mentioned, currently both have only that hack as the only answers.

**Comment by RonnyPfannschmidt** [comment]
My best guess would be to add the data to the report and alter pytest html reporting

Im unfamiliar with pytest-html
