### ISSUE TITLE
How can I log why my workers are down?

### ISSUE THREAD

**Issue by tamaskakuszi** [pytest-dev/pytest-xdist#687]
We have just changed from Windows tester nodes to Kubernetes Debian 10 agents running our test base in Jenkins. 
We are using pytest with pytest-xdist to run our cases in parallel. Since the change the following error occurs:
...
10:27:45 platform linux -- Python 3.7.3, pytest-6.2.4, py-1.10.0, pluggy-1.0.0.dev0
10:27:45 rootdir: /home/jenkins/agent/workspace/Ui-Automation/Ui-Automation-Build, configfile: pytest.ini
10:27:45 plugins: forked-1.3.0, xdist-2.3.0, profiling-1.7.0, allure-pytest-2.7.1
10:27:45 gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I
10:27:45 
[gw0] Python 3.7.3 (default, Jan 22 2021, 20:04:44)  -- [GCC 8.3.0]
10:27:45 
[gw1] Python 3.7.3 (default, Jan 22 2021, 20:04:44)  -- [GCC 8.3.0]
10:27:45 
[gw2] Python 3.7.3 (default, Jan 22 2021, 20:04:44)  -- [GCC 8.3.0]
10:27:45 
[gw3] Python 3.7.3 (default, Jan 22 2021, 20:04:44)  -- [GCC 8.3.0]
10:27:45 
[gw4] Python 3.7.3 (default, Jan 22 2021, 20:04:44)  -- [GCC 8.3.0]
10:27:45 
[gw6] Python 3.7.3 (default, Jan 22 2021, 20:04:44)  -- [GCC 8.3.0]
10:27:45 
[gw5] Python 3.7.3 (default, Jan 22 2021, 20:04:44)  -- [GCC 8.3.0]
10:27:45 [gw0] node down: Not properly terminated
10:27:45 
10:27:45 replacing crashed worker gw0
10:27:45 
[gw7] linux Python 3.7.3 cwd: /home/jenkins/agent/workspace/Ui-Automation/Ui-Automation-Build
10:27:45 
[gw7] Python 3.7.3 (default, Jan 22 2021, 20:04:44)  -- [GCC 8.3.0]
10:27:45 [gw7] node down: Not properly terminated
10:27:45 
10:27:45 replacing crashed worker gw7
....
10:27:45 
[gw34] Python 3.7.3 (default, Jan 22 2021, 20:04:44)  -- [GCC 8.3.0]
10:27:45 [gw34] node down: Not properly terminated
10:27:45 
10:27:45 maximum crashed workers reached: 28
10:27:45 
10:27:45 ================== xdist: maximum crashed workers reached: 28 ==================
10:27:45 ====================== no tests ran in 124.43s (0:02:04) =======================
10:27:45 Build step 'Execute shell' marked build as failure

I would like to log somehow the issue of the crash. Can you please suggest me a way to do the logging? I do not know which hook could help me in the conftest.py file.
Thank you.

**Comment by jay746** [comment]
i also had same issue, i would like to dump info after the crash any hook available with pytest-xdist?

**Comment by jay746** [comment]
@tamaskakuszi or anyone have any info then please share
