### ISSUE TITLE
pytest cannot find database and tables

### ISSUE THREAD

**Issue by navyad** [pytest-dev/pytest-xdist#690]
I am trying to speed up the test runtime by using `pytest-xdist`, previously I was using pytest, pytest-django to run the tests,

After installing `pytest-xdist`, One is an issue which I am facing is most of the tests are failing with messages that relation does not exist

`pytest -n auto accounts/tests`

for example
` psycopg2.errors.UndefinedTable: relation "auth_user" does not exist`
 
 I guess there is error which says database does not exist:
` django.db.utils.OperationalError: FATAL:  database "test_dev" does not exist`

But the interesting thing is some of tests are passing :(

**Comment by yeseen** [comment]
I am having the same issue even with requesting the fixture django_db_modify_db_settings_parallel_suffix.

the `pytest -n auto` runs 11 cores in my server, and I noticed that this problem happens less with `-n 6` cores.

` E       django.db.utils.OperationalError: FATAL:  database "test_dev_gw1" does not exist`

**Comment by nicoddemus** [comment]
I suggest moving this to `pytest-django`, I'm sure they will be able to help.

**Comment by yeseen** [comment]
`pytest-django ` issue created: https://github.com/pytest-dev/pytest-django/issues/942
