### ISSUE TITLE
feature request: test with same pytest.mark are executed in the same worker

### ISSUE THREAD

**Issue by msscaroso** [pytest-dev/pytest-xdist#693]
hello folks, 

I want to use pytest-xdist in a project but I've a scenario where some tests that are executed in the CI consume common resource and if those tests are executed by different workers, they will fail.

The resource is not slow, but each test does a cleanup/teardown in it and the tests would end up interacting in a bad way.

One solution is to each worker consume a separate resource (i. e. change my application code)

Other way would be to mark those tests and somehow pytest-xdist schedule them to be executed in the same worker (i. e. contribute to the pytest-xdist repo)

I am willing to open a PR for it. 
But is it something that would be beneficial for the project and users?

**Comment by RonnyPfannschmidt** [comment]
It's a desired feature, but currently details about markers are not sanely /nicely communicable
