### ISSUE TITLE
FileLock Pattern shown in example is not reliable on Windows

### ISSUE THREAD

**Issue by cbehopkins** [pytest-dev/pytest-xdist#707]
The home page shows the following pattern:
```
    with FileLock(str(fn) + ".lock"):
        if fn.is_file():
            data = json.loads(fn.read_text())
        else:
            data = produce_expensive_data()
            fn.write_text(json.dumps(data))
```
On windows this is not reliable as across threads the normal file IO used in such operations as write_text and read_text are not guaranteed to be correctly ordered. (note that the FileLock library uses a special windows system call to achieve the inter-thread lock)

It is possible on some hardware to get exceptions from the above code as the file can come into existence between the is_file call, and the write_text. I would show a test case, but the above code will generate exceptions if the json is sufficiently small, and the hardware sufficiently quick. (I suspect there is an in windows buffer that the resultant text is fitting into before being persistent to the coherent part of the file system)

The solution that has worked for us is to use an extra file lock object as the "is the file expected to exist" marker. i.e.:
```
    with FileLock(str(fn) + ".lock"):
        extra_lock = FileLock("extra") # actual file path uses reference to tmpdir

        try:
            extra_lock.aquire(timeout = 0.1):
            data = produce_expensive_data()
            fn.write_text(json.dumps(data))
        Except Timeout:
            while not fn.exist():
                time.sleep(0.01)
            data = json.loads(fn.read_text())
```
(The removal of the extra_lock at the end is an exercise left to the reader; we've ended up implementing a file based semaphore method using these lock objects that is too small for this margin)

**Comment by nicoddemus** [comment]
Hi @cbehopkins,

Thanks for writing up!

> On windows this is not reliable as across threads the normal file I

In pytest's xdist there are no threads involved at all, workers and master are single-threaded processes communicating using `execnet`. 

But that's strange, it was our understanding that `FileLock` would guarantee serial access to the lock file, so only one process would be able to enter the `with` block at once, which should prevent the problems you mentioned.

To make sure I understand, you have used our example and it did not work for you, and you had to change to the 2nd listing above?

**Comment by cbehopkins** [comment]
Okay, I wasn't sure on which mulit-processing model was in use - this has just been determined experimentally.

You are right, FileLock is working correctly. The trouble is, the file write, is (experimentally) not guaranteed to be coherent with the file read of Path's is_file

And your understanding is correct, this problem is quite hard to show - only 2 of our build machines exhibited the need for this different pattern. But they did need it 100% of the time.

**Comment by nicoddemus** [comment]
> The trouble is, the file write, is (experimentally) not guaranteed to be coherent with the file read of Path's is_file

I see, particularly I cannot understand how `Path.write_file` would *not* finish writing the file to disk and it showing up later for the other process to check with `is_file`. 😕 

I'm not doubting your experience, I just don't understand it so it is a bit hard for me to change the example.

How about we update the example by adding a note along the lines "this example might have issues on Windows, see #707 for more information if you have problems"? This way if other people have the same issue they will be pointed to this issue and can try your approach too.

**Comment by cbehopkins** [comment]
I'm more than happy with that. I appreciate I'm not able to point to a specification, or present a reliable test case, so as long as it is searchable here for the next person who has the problem then I've done as much as I know how to ;-)

I'm also fine with closing the issue as No Fault Found, I just want to make sure it's recorded somewhere.

And if anyone hits this or a similar problem then I guess it would be good to see that it's not just me, I'm beginning to think it is just me.

**Comment by nicoddemus** [comment]
Thanks @cbehopkins!
