### ISSUE TITLE
eventlet support

### ISSUE THREAD

**Issue by aschmolck** [pytest-dev/pytest-xdist#71]
It seems pytest-xdist does not play nicely with eventlet. 

Self contained example:

```
pip install eventlet==0.19.0 pytest_xdist==1.14 pytest
cat > blah.py <<EOF
import eventlet
eventlet.monkey_patch()
def f(x):
    return x + 1
EOF

cat > test_blah.py <<EOF
import blah
def test_stuff():
    assert blah.f(1) == 2
EOF

py.test -n2
# hangs forever after printing "scheduling tests via LoadScheduling"
```

**Comment by aschmolck** [comment]
P.S. This is probably the same issue as #61 but the above should make it easy to reproduce.

**Comment by jessepollak** [comment]
We're running into this same issue — has anyone found a workaround?

**Comment by RonnyPfannschmidt** [comment]
with recent execnet you can tell it to use a eventlet backend

**Comment by nicoddemus** [comment]
[Here's the docs](http://codespeak.net/execnet/basics.html?highlight=eventlet#examples-for-valid-gateway-specifications) on how to configure exenet to use eventlet. Closing this for now, if anybody still has questions please ask and we can reopen this.

**Comment by aschmolck** [comment]
@nicoddemus Could you maybe show how to run my minimal example above without hanging?

If I change the final line of my example from `py.test -n 2` to

```
py.test -n 2 --tx popen//execmodel=eventlet
```

it still hangs as before. I seem to have the latest version of execnet installed (1.4.1).

**Comment by RonnyPfannschmidt** [comment]
i think it should be `--tx 2*popen//execmodel=eventlet`

**Comment by aschmolck** [comment]
@RonnyPfannschmidt thanks, this does indeed not hang anymore. On the other hand, it doesn't seem to result in any parallelism either. :(
```
cat > blah.py <<EOF
import eventlet
eventlet.monkey_patch()
def f(x):
    return x + 1
EOF

cat > test_blah.py <<EOF
import blah
import time
def test_stuff():
    time.sleep(4)
    assert blah.f(1) == 2
EOF

cat > test_blah2.py <<EOF
import blah
import time
def test_stuff_again():
    time.sleep(4)
    assert blah.f(1) == 2
EOF


time py.test --tx '2*popen//exemodel=eventlet'
```
0.50s user 0.01s system 5% cpu 8.520 total

**Comment by RonnyPfannschmidt** [comment]
use --dist load?

**Comment by aschmolck** [comment]
Hangs for me. Does it work for you? Pasting the snippet I posted above literally into a terminal should work, if you do have eventlet and pytest_xdist installed (e.g. via `pip install eventlet==0.19.0 pytest_xdist==1.14 pytest`).

**Comment by RonnyPfannschmidt** [comment]
i see, i currently cant test myself, im not sure what is going wrong and what part is being conflicted

**Comment by aschmolck** [comment]
Would it be possible to re-open this?

**Comment by jcpetruzza** [comment]
Hmmm, I think the problem here is:

  1. There was a typo in what @aschmolck was trying: `exemodel=eventlet` instead of `execmodel=eventlet`.
  2. `pytest_xdist` doesn't complain when the argument for `execnet` is bogus

`py.test --tx '2*popen//execmodel=eventlet' --dist load` runs the example above in ~4 seconds for me...

**Comment by RonnyPfannschmidt** [comment]
i see, thanks
