### ISSUE TITLE
Remove worker line from failure output

### ISSUE THREAD

**Issue by GergelyKalmar** [pytest-dev/pytest-xdist#718]
Currently the failure section of the output of a `pytest-xdist` run looks similar to this:

```
=== FAILURES ===
___ [pylint] file1.py ___
[gw1] linux -- Python 3.8.10 .../bin/python3.8
W: 31, 1: TODO: ... (fixme)
W: 32, 1: TODO: ... (fixme)
___ [pylint] file2.py ___
[gw4] linux -- Python 3.8.10...bin/python3.8
W: 47, 1: TODO: ... (fixme)
...
=== 3 failed, 69 passed, 131 skipped in 27.71s ===
```
Notice the lines starting with `[gwX]`: I understand that sometimes they can provide useful information (e.g. when running tests across multiple environments), however, in my case they don't really provide any information given that I just run pytest locally in a single environment. (In fact, a pytest run without xdist looks pretty much the same except for these lines.) Is it possible to somehow disable or remove those lines? Can I somehow patch pytest-xdist to remove those lines from the output (e.g. with a pytest plugin or some other way)?

**Comment by nicoddemus** [comment]
Hi @GergelyKalmar, 

Unfortunately no, that's hard coded into pytest itself I'm afraid:

https://github.com/pytest-dev/pytest/blob/9d17cebe64878f695fbd7596fcfb643f53a56830/src/_pytest/terminal.py#L570

**Comment by GergelyKalmar** [comment]
Well, that's somewhat good news, I can file an issue there to make this at least configurable (or perhaps smarter)! It is a bit weird that this would be controlled straight in `pytest`, I thought `pytest-xdist` was just a plugin like any other.
