### ISSUE TITLE
pytest-xdist rtd documentation site problem

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest-xdist#749]
It seems that pytest-xdist documentation rtd website exists but never container docs on it, but searching for xdist docs brings https://readthedocs.org/projects/pytest-xdist amont top results which is confusing.

Apparently @hpk42 @nicoddemus and @RonnyPfannschmidt the the ones listed as admins on RTD. I suspect that removing the project from RTD can sort the problem. As I guess that if nobody bothered to add a sphinx config in so many years it will never happen.

To improve the situation I would also add extra metadata to package to link directly the readme as the Documentation, avoiding further confusions.

**Comment by nicoddemus** [comment]
I guess it was created with the intention of reserving the domain to add proper docs at some point, but in fact it never materialized. 

I agree this is confusing, but for some time now the docs in the README have bothered me a little, let me see if I can cook something up to at least have a proper documentation page in there.
