### ISSUE TITLE
[Question] Setting environment variable for different workers

### ISSUE THREAD

**Issue by jackalcooper** [pytest-dev/pytest-xdist#760]
I looked into pytest's docs but can't find how to do this. If we have 4 worker in pytest xdist, is it possible to pass environment variables like this:
```
CUDA_VISIBLE_DEVICES=0 gw0
CUDA_VISIBLE_DEVICES=1 gw1
CUDA_VISIBLE_DEVICES=2 gw2
CUDA_VISIBLE_DEVICES=3 gw3
```
Looks like it is possible to use `fixture` to change the environment variable but the package I am trying to run will do some initialization effected by the `CUDA_VISIBLE_DEVICES` when it is imported.
Thanks!

**Comment by RonnyPfannschmidt** [comment]
You can either use - -tx with different env settings, or configure worker input

**Comment by jackalcooper** [comment]
> You can either use - -tx with different env settings, or configure worker input

Got it working now. Thanks you~

**Comment by clemente0420** [comment]
> You can either use - -tx with different env settings, or configure worker input

can   you give a spec case ?

**Comment by clemente0420** [comment]
> 

HOW DID YOU Fix
