### ISSUE TITLE
Import py problem

### ISSUE THREAD

**Issue by DCnTop** [pytest-dev/pytest-xdist#773]
### Discussed in https://github.com/pytest-dev/pytest-xdist/discussions/772

<div type='discussions-op-text'>

<sup>Originally posted by **DCnTop** April  4, 2022</sup>

Context: running on CircleCI, linux Docker image circleci/python:3.8.5
Trying to run as subprocesses with the following command: **pytest -d --tx 2*popen//python=python3.8**
This is a good image, when pytest runs without xdist we run tests, collect coverage, and so on.

Can someone explain this:

============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/circleci/repo
plugins: Faker-11.3.0, forked-1.4.0, cov-3.0.0, xdist-2.5.0
gw0 I / gw1 Igw0 C / gw1 Igw0 C / gw1 C[gw0] node down: Traceback (most recent call last):
  File "<string>", line 1084, in executetask
  File "/home/circleci/repo/venv/lib/python3.8/site-packages/xdist/remote.py", line 13, in <module>
    import py
ModuleNotFoundError: No module named 'py'
</div>

**Comment by RonnyPfannschmidt** [comment]
What's the actual path of the python3.8 binary that is found

**Comment by bluetech** [comment]
`py` is no longer used
