### ISSUE TITLE
pytest_runtest_makereport is not giving the report result with xdist

### ISSUE THREAD

**Issue by gurdeepsinghiet** [pytest-dev/pytest-xdist#786]
platform window
Python 3.9.9
pytest-7.1.2
pluggy-1.0.0
plugins: xdist-2.5.0, forked-1.4.0

I have a scenarioes after executing all the test cases with xdist.i need to colloect the report with **pytest_runtest_makereport**
as follw:
    @pytest.hookimpl(tryfirst=True, hookwrapper=True)
    def pytest_runtest_makereport(self,item, call):
        outcome = yield
        result = outcome.get_result()
        print('makereport:', result)
        if result.when == 'call':
            item.session.results[item] = result

but **result = outcome.get_result()** is not giving any result with xdist.without xdist it is working fine.

**Comment by RonnyPfannschmidt** [comment]
With xdist print does not work, what's your output /expected output?

**Comment by gurdeepsinghiet** [comment]
actually i am asking about  result = outcome.get_result() method ,which is not giving report data retalted to Testcase name Status passed and failed.

**Comment by RonnyPfannschmidt** [comment]
With a partial badly formatted code example and no expected vs actual output, the only thing i can vaguely guess is that print does not work on xdist

For anything else please provide enough detail to work with

**Comment by gurdeepsinghiet** [comment]
No im not asking about print statement.i need complete report summary after excecuting the below code with xdist:

def pytest_sessionstart(session):
    session.results = dict()

@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    result = outcome.get_result()
    if result.when == 'call':
        item.session.results[item] = result


def pytest_sessionfinish(session, exitstatus):
    nm=[result for result in session.results.values()]
    #https://www.lambdatest.com/automation-testing-advisor/python/pytest-pytest_sessionfinish
    #https://korytkin.medium.com/how-to-get-data-from-pytest-xdist-nodes-2fbf2f0fe957
    #testcasename=nm[0].nodeid.split("::")[1]
    passed_amount = sum(1 for result in session.results.values() if result.passed)
    failed_amount = sum(1 for result in session.results.values() if result.failed)
    totalCase=passed_amount+failed_amount
    print(f'there are {passed_amount} passed and {failed_amount} failed tests in {totalCase} test cases')
    summary=[]
    for result in session.results.values():
        summaryPram = {}
        if result.passed:
            summaryPram["testcasename"]=result.nodeid.split("::")[1]
            summaryPram["status"] = "Passed"
            summary.append(summaryPram)
        elif result.failed:
            summaryPram["testcasename"] = result.nodeid.split("::")[1]
            summaryPram["status"] = "Failed"
            summary.append(summaryPram)

**Comment by RonnyPfannschmidt** [comment]
It's unclear what you mean by not working

The posted code is unaware of xdist and likely broken as each worker makes a own summary with that

**Comment by gurdeepsinghiet** [comment]
my question is that how to get the consolidated pass/fail report with tetscasename from each worker node .

**Comment by gurdeepsinghiet** [comment]
logreport hook generate the Log file of test  summary report?

**Comment by RonnyPfannschmidt** [comment]
Kinda

**Comment by gurdeepsinghiet** [comment]
so one more question can i achive this by worked node.and collect all the report data from all worked nodes.

**Comment by RonnyPfannschmidt** [comment]
It's not clear what you are asking for, there are no built-in summary combination hooks and your presented use case is fine to run on the coordinator

**Comment by gurdeepsinghiet** [comment]
actully i need to generate the html  test summary report which conatin pass,fail,Total test cases.

<html>
<body>


Testcase | Status | Priority
-- | -- | --
test_keyclock | Passed | P1
test_keyclock1 | Passed | P1
test_keyclock2 | Passed | P1
test_keyclock3 | Passed | P1
test_keyclock4 | Passed | P1
test_keyclock5 | Passed | P1
test_keyclock6 | Passed | P1


</body>
</html>Testcase	Status	Priority
[test_keyclock](https://github.com/pytest-dev/pytest-xdist/issues/test_keyclock.html)
Passed	P1
[test_keyclock1](https://github.com/pytest-dev/pytest-xdist/issues/test_keyclock1.html)
Passed	P1
[test_keyclock2](https://github.com/pytest-dev/pytest-xdist/issues/test_keyclock2.html)
Passed	P1
[test_keyclock3](https://github.com/pytest-dev/pytest-xdist/issues/test_keyclock3.html)
Passed	P1
[test_keyclock4](https://github.com/pytest-dev/pytest-xdist/issues/test_keyclock4.html)
Passed	P1
[test_keyclock5](https://github.com/pytest-dev/pytest-xdist/issues/test_keyclock5.html)
Passed	P1
[test_keyclock6](https://github.com/pytest-dev/pytest-xdist/issues/test_keyclock6.html)
Passed	P1
</body>
</html>

**Comment by RonnyPfannschmidt** [comment]
Using the logreport hook on the coordinator will automatically bring it together

**Comment by gurdeepsinghiet** [comment]
HI @RonnyPfannschmidt 
Thanks for ur resolution .
I got all the reporting data by implementing logreport .

here is the code implementation:

`class Reporting:
    def __init__(self):
	     self.reportSet=set()

    def pytest_sessionstart(self,session):
        session.results = dict()

    def pytest_runtest_logreport(self,report):
        if report and report.when and report.when == 'call':
            self.reportSet.add(report.nodeid.split("::")[1]+":" +report.outcome)
            print(self.reportSet)


    @pytest.hookimpl(hookwrapper=True, trylast=True)
    def pytest_sessionfinish(self, session, exitstatus):
        passed_amount = sum(1 for result in self.reportSet if result.split(":")[1] == "passed")
        failed_amount = sum(1 for result in self.reportSet if result.split(":")[1] == "failed")
        totalCase = passed_amount + failed_amount
        print(f'there are {passed_amount} passed and {failed_amount} failed tests in {totalCase} Total test cases')
        summary = []
        for result in self.reportSet:
            summaryPram = {}
            if result.split(":")[1] == "passed":
                summaryPram["testcasename"] = result.split(":")[0]
                summaryPram["status"] = "Passed"
                summary.append(summaryPram)
            elif result.split(":")[1] == "failed":
                summaryPram["testcasename"] = result.split(":")[0]
                summaryPram["status"] = "Failed"
                summary.append(summaryPram)

        return summary`

**Comment by gurdeepsinghiet** [comment]
i m closing my issue.
