### ISSUE TITLE
Can I choose what test cases I want to run with xdist?

### ISSUE THREAD

**Issue by ngyingkai** [pytest-dev/pytest-xdist#788]
Can I choose what test cases I want to run with xdist? The flip side works as well where if I can choose what cases I do not want to run with xdist.

There are some cases where I don't want to run in parallel as some of the data or dependant.

**Comment by nicoddemus** [comment]
Hi @ngyingkai, 

You can select tests normally with any pytest option (for example `-k` and `-m`).

Or do you mean run some tests with xdist and others run normally? In that case see #385.

Closing for now, feel free to follow up with further questions.
