### ISSUE TITLE
Option to set the default distribution algorithm

### ISSUE THREAD

**Issue by DavideCanton** [pytest-dev/pytest-xdist#789]
Hi, I have the following scenario:

- I have some tests that need to be run in the same worker due to the fact they use a shared object (I know it's not very idiomatic for unit tests, but it is really the simpler way to check what I need to check)
- I saw the `--dist loadgroup` option, but unfortunately it is not the default, so I should remember to specify every time the command line option
- I can't add it to the `addopts` setting since it errors if I don't specify either `-n` or `-tx`, and I want to be able to choose to run the tests the standard way too.

What could work for me is a setting to set the default algorithm to use when `--dist` is not specified, so that:
- if I run `pytest` standalone, it doesn't run in parallel
- if I run `pytest -n auto`, it uses the algorithm specified in the setting
- if I run `pytest -n auto --dist loadfile`, it overrides the setting with the `loadfile` algorithm.

**Comment by unparalleled-js** [comment]
I need this as well.

Something like this would be nice:

```toml
[ptest.xdist]
dist = loadscope
```

such that whenever `-n` is used, it will automatically use loadscope distribution. Like the issue author states, it helps so I don't have to remember to use `--dist loadscope` because I have some tests scattered about that share a resource (a special, complicated process running).

**Comment by DavideCanton** [comment]
I could try setting up a PR if someone is interested in merging it

**Comment by nicoddemus** [comment]
I don't think we need a separate option, I would prefer if we can make it possible to set `--dist X` using `addopts`, without erroring  out if `-n` is not passed too.

**Comment by unparalleled-js** [comment]
> I don't think we need a separate option, I would prefer if we can make it possible to set `--dist X` using `addopts`, without erroring out if `-n` is not passed too.

This works for me

**Comment by DavideCanton** [comment]
> I don't think we need a separate option, I would prefer if we can make it possible to set `--dist X` using `addopts`, without erroring out if `-n` is not passed too.

How I could run pytest without erroring if `-n` is not passed?

**Comment by nicoddemus** [comment]
I think it should be possible to implement that (can't look at the code right now).

**Comment by DavideCanton** [comment]
It can be implemented since we had to do it by using pytest hooks, but it's quite messy since you have to dig deep inside how the workers read the options

**Comment by nicoddemus** [comment]
Opened https://github.com/pytest-dev/pytest-xdist/pull/851. 👍

**Comment by DavideCanton** [comment]
Just to point out, the #851 only allows to set the default dist, but it breaks the standard `pytest` run without xdist since the `--dist` options requires either `-n` or `-tx`.
