### ISSUE TITLE
Allow xdist_group marks to apply to a class

### ISSUE THREAD

**Issue by hubert-hub** [pytest-dev/pytest-xdist#790]
It would very convenient if we could mark a test class and have that mark apply to all tests within. In a way, allow for the class part of loadscope to apply to loadgroup. Currently, I have to mark dozens of tests in a class that I already mark to use a class-scoped fixture at the top level.

**Comment by nicoddemus** [comment]
Hi @hubert-hub,

Hmm strange, when a mark is applied to a class, that mark is automatically applied to all test methods (that's a pytest feature, not being specific to xdist).

**Comment by hubert-hub** [comment]
You are right. I'm a primate banging on a keyboard. I had the wrong argument.
