### ISSUE TITLE
[BUG] pytest.mark.parametrize does not work when order of parameters is not guaranted

### ISSUE THREAD

**Issue by 07pepa** [pytest-dev/pytest-xdist#795]
# what  

when using default behavior (`pytest -n auto`) 
and invoking parametrized test that does not have guaranteed order of parameter aka consider folowing code

## example code
```python
import pytest

@pytest.mark.parametrize("param",
                         {"a",
                          "b"
                          })
def test_pytest_parametrize_unordered(param):
    print(param)
````
## caused errors
causes following errors

```
gw3:None (gw3)
Different tests were collected between gw0 and gw3. The difference is:
--- gw0

+++ gw3

@@ -1,2 +1,2 @@

+test.py::test_pytest_parametrize_unordered[b]
 test.py::test_pytest_parametrize_unordered[a]
-test.py::test_pytest_parametrize_unordered[b]
```
## theory why it hapens
it looks like the node compare (or used data structures) are order sensitive

however this is not right..... because pytest.parametrize have folowing (truncated) signature

```python
argvalues: Iterable[Union[ParameterSet, Sequence[object], object]]
```

As you can see iterable does not guarantees order
this means you should shift to something that only minds contents and not order. Because order of test should not matter (unless specialy specifed).. ther posible solution is to sort it internaly but there is not guarantee that items will be sortable so it may fail

## why to fix this
Please Fix this since there are valid usecases of unordered parametrized parameters ( like generator traversing folders does not have to guarantee orders of items)

secondly if i would be penant curent implementation is in violation of pytest and should be considered uncompatible

so i am hoping this will get fixed in next release

**Comment by RonnyPfannschmidt** [comment]
pytest/pytest-xdist dist leaves the stability of the test set to the test author, as its simply not safely possible to do it in the general case (floats, random data, intentional unstability), while it is trivial to put something like sorted in
