### ISSUE TITLE
How to enable the plugin logging

### ISSUE THREAD

**Issue by gomario** [pytest-dev/pytest-xdist#797]
We're having an issue where the test run abruptly ends , no summary report , runa a handful of cases and just ends. This is within a docker container but to get started on figuring out whats going on I noticed the plugin has a lot of great logging like " ('sending command shutdown(**{})',)" etc,  how do i enable logging and/or view this output ???

btw, Im running 2.4 and about to upgrade to 2.5.0

**Comment by nicoddemus** [comment]
Hi @gomario,

Use `--debug=<FILE>`, this will output those debug messages (called "trace" internally) to the given file.
