### ISSUE TITLE
Slaves should provide a hook that reports how many tests it collected to the master

### ISSUE THREAD

**Issue by thedrow** [pytest-dev/pytest-xdist#8]
https://github.com/Frozenball/pytest-sugar/pull/65 requires me to get the number of tests collected in order to display a progress bar. The xdist slaves do not report how many tests they have collected so I can't implement it.
Please adjust a hook or add a new hook that will report how many tests were collected by each slave.

**Comment by nicoddemus** [comment]
Hi @thedrow! Just to make sure we get the requirements correctly, could you please describe in a little more detail what you need? Could you also suggest a hook signature that would fit your needs?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus we need to find a reasonable way to expose collectionfinished

**Comment by nicoddemus** [comment]
I have a rough idea, but would like to hear from @thedrow to avoid implementing something that ends up not being usable for `pytest-sugar`. 

My first thought would be something like:

```python
def pytest_xdist_node_collection_finished(node, item_ids):
    """item_ids is a list of test item ids which were collected by the node (slave)"""
```

Would that be enough @thedrow?

**Comment by thedrow** [comment]
It depends if the hook will be raised on the master or not.
I need to be able to get the terminal reporter like so: https://github.com/thedrow/pytest-sugar/blob/patch-1/pytest_sugar.py#L64

**Comment by RonnyPfannschmidt** [comment]
it makes only sense on the master, slaves get the same information in modifyitems

but to be safe/sane there might be need for an 
```
def pytest_xdist_node_logreport(node, report):
  """like logreport, but also tell the node"""

```

@hpk42 could we potentially get pluggy to support plugins adding optional parameters to hooks

**Comment by thedrow** [comment]
I think that what @RonnyPfannschmidt suggested works best.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt It seems to me you meant adding `node` information to `pytest_runtest_logreport`, but that hook is called for test setup/call/teardown, not for collection (that would be `pytest_collectreport`). Or do you mean adding node information to both?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus well, i want to enable xdist to add them as optional parameters,

how that can work is subject for discussion, for now i would just add the implementation and invoke both the normal and the extended variant from xdist

**Comment by nicoddemus** [comment]
Sorry, I was not very clear: my question was to which hook you were referencing in the docstring in your example: `"like logreport, but also tell the node"`: which "logreport" you mean here, `pytest_runtest_logreport` or `pytest_collectreport`? :grin:

**Comment by RonnyPfannschmidt** [comment]
i was only referring to logreport, but collectreport is also affected

**Comment by nicoddemus** [comment]
Right. 

So to be clear, for pytest-sugar's needs and considering we don't wait for `pluggy` to support adding parameters to existing hooks, we would have to implement two new hooks:

```python
def pytest_xdist_runtest_logreport(node, report):
  """like pytest_runtest_logreport, but also tell the node"""

def pytest_xdist_collectreport(node, report):
  """like pytest_collectreport, but also tell the node"""
```

**Comment by RonnyPfannschmidt** [comment]
i think we also need `pytest_xdist_node_collection(node, items)` the interaction with collect-reports is painful otherwise

**Comment by nicoddemus** [comment]
So to summarize:

```python
def pytest_xdist_runtest_logreport(node, report):
    """like pytest_runtest_logreport, but also tell the node"""

def pytest_xdist_collectreport(node, report):
    """like pytest_collectreport, but also tell the node"""

def pytest_xdist_node_collection(node, items):
    """called by the master node when a worker finishes collecting. items is a list of testids."""
```

@thedrow what do you think? Would that be enough for `pytest-sugar`'s needs?

**Comment by thedrow** [comment]
Yes. I think so.
