### ISSUE TITLE
Add version field to setup.cfg

### ISSUE THREAD

**Issue by maiconfaria** [pytest-dev/pytest-xdist#801]
https://github.com/pytest-dev/pytest-xdist/blob/61132777f8d85f7e03837684fbbdb41cb4f9c486/setup.cfg#L3

Could the version number be added on the metadate? This is bring issues to dependencies for people that compile from source instead of using the .whl

**Comment by RonnyPfannschmidt** [comment]
Install build requirements

**Comment by maiconfaria** [comment]
If you build pytest-xdist from source the package will be reported as version 0.0.0.

**Comment by maiconfaria** [comment]
check https://github.com/maiconfaria/pytest-xdist/blob/baf01906255ffdbaca98a6854a8e3ad26df62464/setup.cfg#L3

with the addition:

```
python3.8 ./setup.py install --user
...
creating dist
creating 'dist/pytest_xdist-2.5.0-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pytest_xdist-2.5.0-py3.8.egg
creating /home/farim1/.local/lib/python3.8/site-packages/pytest_xdist-2.5.0-py3.8.egg
Extracting pytest_xdist-2.5.0-py3.8.egg to /home/farim1/.local/lib/python3.8/site-packages
Adding pytest-xdist 2.5.0 to easy-install.pth file

Installed /home/farim1/.local/lib/python3.8/site-packages/pytest_xdist-2.5.0-py3.8.egg
Processing dependencies for pytest-xdist==2.5.0
```

**Comment by nicoddemus** [comment]
We use `setuptools-scm` to manage the package version. 

Try installing with `pip` instead of executing `setup.py` directly, it should install the package with the correct version.
