### ISSUE TITLE
Using xdist will run pytest_terminal_summary many times

### ISSUE THREAD

**Issue by TheSlientnight** [pytest-dev/pytest-xdist#802]
## Question
when I using xdist --dist=auto, pytest_terminal_summary will run many times because tasks will run different thread, and each thread will run this function when this thread finished it's tasks
## example code
```python
def pytest_terminal_summary():
      passed = len(terminalreporter.stats.get('passed', []))
      failed = len(terminalreporter.stats.get('failed', []))
      error = len(terminalreporter.stats.get('error', []))
      skipped = len(terminalreporter.stats.get('skipped', []))
      total = passed + failed + error + skipped
      """send msg to web hook """
      data = {
          "msgtype": "actionCard",
          "actionCard": {
              "title": "auto test result",
              "text": "pass/failed/error/skiped:%s/%s/%s/%s\n\n"
                      "total: %s" % (passed, failed, error, skipped, total),
              "hideAvatar": "0",
              "btnOrientation": "0"
          }
      }
      url = "webhookurl"
      headers = {
          'Content-Type': 'application/json'
      }
      requests.post(url=url, data=json.dumps(data), headers=headers)
```
## What I need
now I got so many message from my web hook robot, but I only need to know the real summary with purest_terminal_summary function, so how can I got only one message from this function with using xdist
![image](https://user-images.githubusercontent.com/37974664/182143386-dccd9037-adbc-4582-8457-7dcbe5e4e842.png)

**Comment by nicoddemus** [comment]
Hi @TheSlientnight, 

> thread, and each thread will run this function when this thread finished it's tasks

They are actually run in separate processes, not threads.

> so how can I got only one message from this function with using xdist

You can check if you are in the master node by looking at the [PYTEST_XDIST_WORKER](https://pytest-xdist.readthedocs.io/en/latest/how-to.html#envvar-PYTEST_XDIST_WORKER) environment variable, and checking if it is `"master"` before issuing your hook.

**Comment by RonnyPfannschmidt** [comment]
why do we invoke terminal_summary in the workers, they dont have the terminal?

**Comment by nicoddemus** [comment]
Hmm good question, took a quick look at the code and the terminal plugin calls `pytest_terminal_summary`, but that plugin is disabled for workers, so it shouldn't be called.

**Comment by TheSlientnight** [comment]
> 

So I just can't know which woker invoke this plugin, can you tell me which hook or which function can I use for getting  result and send it to my web hook only one time.
Thx a lot😆

**Comment by nicoddemus** [comment]
Not sure, but as I said you can do this:

```python
def pytest_terminal_summary():
    if os.environ.get("PYTEST_XDIST_WORKER", "master") != "master":
        return
    passed = len(terminalreporter.stats.get('passed', []))
    failed = len(terminalreporter.stats.get('failed', []))
```

**Comment by TheSlientnight** [comment]
> Not sure, but as I said you can do this:
> 
> ```python
> def pytest_terminal_summary():
>     if os.environ.get("PYTEST_XDIST_WORKER", "master") != "master":
>         return
>     passed = len(terminalreporter.stats.get('passed', []))
>     failed = len(terminalreporter.stats.get('failed', []))
>     ...
> ```

It works, thanks a lot for helping me
