### ISSUE TITLE
Global setup and teardown for parallel tests

### ISSUE THREAD

**Issue by pyrito** [pytest-dev/pytest-xdist#809]
I recently noticed that the distributed pytests will actually call `pytest_sessionstart` and `pytest_sessionfinish` for each worker. This model does make sense, but I was wondering if it would be possible to have a global setup and teardown function to do some cleanup that should only be done by one worker?

**Comment by heitorlessa** [comment]
Tried this @pyrito?

https://pytest-xdist.readthedocs.io/en/latest/how-to.html#making-session-scoped-fixtures-execute-only-once

I have it working in a project I help maintain.
