### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: TEST_SESSIONS.SESSION_H

### ISSUE THREAD

**Issue by andreabisello** [pytest-dev/pytest-xdist#815]
The collection phase can crash randomly due to this issue on a windows 11 full updated with pytest 7.1.3 and xdist 2.5.0 with python 3.10.4 64bit edition

the problem looks related to the -n auto parameter, due if i set -n 3, it doesn't crash.

full log

C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1.2\plugins\python-ce\helpers\pycharm\_jb_pytest_runner.py" --path C:/src/qa-lsd-webservices/test_hub.py
Testing started at 10:07 ...
Launching pytest with arguments C:/src/qa-lsd-webservices/test_hub.py --no-header --no-summary -q in C:\src\qa-lsd-webservices

modulo -> C:/src/qa-lsd-webservices/test_hub.py
parametro -> configurations/utenze/COMMON-integration.ini
parametro -> configurations/puntamenti/integration.ini
============================= test session starts =============================
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I
[gw0] win32 Python 3.10.4 cwd: C:\src\qa-lsd-webservices
[gw1] win32 Python 3.10.4 cwd: C:\src\qa-lsd-webservices
[gw2] win32 Python 3.10.4 cwd: C:\src\qa-lsd-webservices
[gw3] win32 Python 3.10.4 cwd: C:\src\qa-lsd-webservices
[gw4] win32 Python 3.10.4 cwd: C:\src\qa-lsd-webservices
[gw5] win32 Python 3.10.4 cwd: C:\src\qa-lsd-webservices
[gw1] Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
[gw0] Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
[gw2] Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
[gw4] Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
[gw5] Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
INTERNALERROR> def worker_internal_error(self, node, formatted_error):
INTERNALERROR>         """
INTERNALERROR>         pytest_internalerror() was called on the worker.
INTERNALERROR>     
INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
INTERNALERROR>         here ourselves using the formatted message.
INTERNALERROR>         """
INTERNALERROR>         self._active_nodes.remove(node)
INTERNALERROR>         try:
INTERNALERROR> >           assert False, formatted_error
INTERNALERROR> E           AssertionError: Traceback (most recent call last):
INTERNALERROR> E               File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\main.py", line 266, in wrap_session
INTERNALERROR> E                 config.hook.pytest_sessionstart(session=session)
INTERNALERROR> E               File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR> E               File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E               File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 34, in _multicall
INTERNALERROR> E                 next(gen)  # first yield
INTERNALERROR> E               File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pytest_monitor\pytest_monitor.py", line 194, in pytest_sessionstart
INTERNALERROR> E                 session.pytest_monitor.compute_info(session.config.option.mtr_description,
INTERNALERROR> E               File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pytest_monitor\session.py", line 87, in compute_info
INTERNALERROR> E                 self.__db.insert_session(self.__session, run_date, scm, description)
INTERNALERROR> E               File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pytest_monitor\handler.py", line 17, in insert_session
INTERNALERROR> E                 self.__cnx.execute('insert into TEST_SESSIONS(SESSION_H, RUN_DATE, SCM_ID, RUN_DESCRIPTION)'
INTERNALERROR> E             sqlite3.IntegrityError: UNIQUE constraint failed: TEST_SESSIONS.SESSION_H
INTERNALERROR> E           assert False
INTERNALERROR> 
INTERNALERROR> C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\xdist\dsession.py:192: AssertionError
[gw3] node down: Not properly terminated

replacing crashed worker gw3
[gw6] win32 Python 3.10.4 cwd: C:\src\qa-lsd-webservices
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\xdist\dsession.py", line 117, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\xdist\dsession.py", line 140, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\xdist\dsession.py", line 229, in worker_errordown
INTERNALERROR>     self._active_nodes.remove(node)
INTERNALERROR> KeyError: <WorkerController gw3>

=========================== no tests ran in 12.47s ============================

Process finished with exit code 3

Empty suite

Empty suite

**Comment by nicoddemus** [comment]
The code which is crashing is in `pytest-monitor`:

```
INTERNALERROR> E File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pytest_monitor\pytest_monitor.py", line 194, in pytest_sessionstart
INTERNALERROR> E session.pytest_monitor.compute_info(session.config.option.mtr_description,
INTERNALERROR> E File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pytest_monitor\session.py", line 87, in compute_info
INTERNALERROR> E self.__db.insert_session(self.__session, run_date, scm, description)
INTERNALERROR> E File "C:\Users\andreabisello\AppData\Local\Programs\Python\Python310\lib\site-packages\pytest_monitor\handler.py", line 17, in insert_session
INTERNALERROR> E self.__cnx.execute('insert into TEST_SESSIONS(SESSION_H, RUN_DATE, SCM_ID, RUN_DESCRIPTION)'
INTERNALERROR> E sqlite3.IntegrityError: UNIQUE constraint failed: TEST_SESSIONS.SESSION_H
INTERNALERROR> E assert False
```

Seems like pytest-monitor needs explicit support to work with pytest-xdist?

I suggest to move/create this issue over to the pytest-monitor repository.

Closing for now, feel free to follow up with further questions.

**Comment by andreabisello** [comment]
@nicoddemus sorry

**Comment by nicoddemus** [comment]
Oh no problem :thum
