### ISSUE TITLE
Deprecate rsync support

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-xdist#825]
It's possible that the current tests don't correctly capture the requirements in a way that finds breakage.

If that's the case we should evaluate that and consider dropping rsync over fixing it.

_Originally posted by @RonnyPfannschmidt in https://github.com/pytest-dev/pytest-xdist/issues/823#issuecomment-1287753174_

**Comment by nicoddemus** [comment]
We probably can just deprecate in same way as we did with `--boxed`:

https://github.com/pytest-dev/pytest-xdist/blob/1471164197f59fd68f5729eea5f58e88ddc62522/src/xdist/plugin.py#L198-L205

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt is this something you want to do before the 3.0.0 release?

**Comment by RonnyPfannschmidt** [comment]
Ideally yes, but my bandwidth this week is unclear

**Comment by nicoddemus** [comment]
Want me to tackle it?

I think it is important to release 3.0 before or right after pytest 7.2, that's why I ask (but this deprecation can be done later of course).

**Comment by RonnyPfannschmidt** [comment]
Then let's defer

**Comment by nicoddemus** [comment]
While I waited for your response I went ahead and opened https://github.com/pytest-dev/pytest-xdist/pull/828, let me know if that's sufficient or you would like something more elaborate, in which case we can defer it.

**Comment by ssbarnea** [comment]
While the `rsyncdir(s)` were deprecated and I am not them anywhere, now I see my test suited failing because I run them with warnings as errors.

That was with latest versions of pytest and its plugins:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/ssbarnea/c/a/molecule/.tox/py/lib/python3.11/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Users/ssbarnea/c/a/molecule/.tox/py/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Users/ssbarnea/c/a/molecule/.tox/py/lib/python3.11/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ssbarnea/c/a/molecule/.tox/py/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ssbarnea/c/a/molecule/.tox/py/lib/python3.11/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ssbarnea/c/a/molecule/.tox/py/lib/python3.11/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/ssbarnea/c/a/molecule/.tox/py/lib/python3.11/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ssbarnea/c/a/molecule/.tox/py/lib/python3.11/site-packages/xdist/plugin.py", line 214, in pytest_configure
INTERNALERROR>     config.issue_config_time_warning(warning, 2)
INTERNALERROR>   File "/Users/ssbarnea/c/a/molecule/.tox/py/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1394, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> DeprecationWarning: The --rsyncdir command line argument and rsyncdirs config variable are deprecated.
INTERNALERROR> The rsync feature will be removed in pytest-xdist 4.0.
```

Am I the only one running with warnings as errors?

**Comment by henryiii** [comment]
Same in https://github.com/pypa/build/pull/527.

**Comment by clavedeluna** [comment]
Also running into above mentioned error.

**Comment by bluetech** [comment]
It's coming from the pytest-cov plugin: https://github.com/pytest-dev/pytest-cov/blob/f7fced579e36b72b57e14768026467e4c4511a40/src/pytest_cov/engine.py#L263

**Comment by henryiii** [comment]
Since this is being worked out, a temporary workaround could be to add:

```toml
[tool.pytest.ini_options]
filterwarnings = [
   "error",
   "ignore:The --rsyncdir command line argument and rsyncdirs config variable are deprecated.:DeprecationWarning",
 ]
```

instead of pinning something. That's what I'm doing ATM.

**Comment by nicoddemus** [comment]
Thanks folks (and @bluetech for finding the root cause).

Pinning this to give visibility.

**Comment by JonJagger** [comment]
Our flask server uses pytest-xdist to run its tests in parallel.
When we use `--pythonwarnings=error` we also get the INTERNALERROR message above.
However, when we add a pytest.ini file from above with filterwarnings we find that the pytest hook function called 
`pytest_terminal_summary` no longer runs !?
