### ISSUE TITLE
New Conda-forge release

### ISSUE THREAD

**Issue by ayushdg** [pytest-dev/pytest-xdist#832]
It would be great if xdist could cut a new release on conda-forge as well for users could pick up the latest version. 

For context the latest pytest Conda-forge [package](https://anaconda.org/conda-forge/pytest) drops it's dependency on the `py` package which led to failures when working with the latest `pytest-xdist` version available on conda today. The latest version drops it's dependency on `py.log` and hopefully should not see the same errors/issues.

As a temporary workaround adding the `py` package as an explicit dependency locally should fix the issues. 

Happy to move this to https://github.com/conda-forge/pytest-xdist-feedstock if that's a better place for the discussion.

**Comment by nicoddemus** [comment]
Fixed: https://github.com/conda-forge/pytest-xdist-feedstock/pull/48

Should be available after 1 hour or so, after conda-forge reindexes. 👍

**Comment by ayushdg** [comment]
Thanks for the quick fix here!
