### ISSUE TITLE
The package description adevrtizes a deprecated loop-on-fail feature

### ISSUE THREAD

**Issue by hroncok** [pytest-dev/pytest-xdist#835]
The package description explicitly mentions the loop-on-fail feature:

https://github.com/pytest-dev/pytest-xdist/blob/7949c14f67b28c2ceb98c0a76fc74ff2bb5fdb96/setup.cfg#L3

Which is deprecated:

https://github.com/pytest-dev/pytest-xdist/blob/7949c14f67b28c2ceb98c0a76fc74ff2bb5fdb96/CHANGELOG.rst#L17

I think the description needs to be updated. Happy to send a PR if you agree.

**Comment by nicoddemus** [comment]
Definitely, thanks @hroncok, the PR is appreciated. 👍
