### ISSUE TITLE
[info] pytest-xdist worker crash then log something

### ISSUE THREAD

**Issue by jay746** [pytest-dev/pytest-xdist#847]
I have a usecases where if worker crashes i want to collect some info and dump in log file, so that i can debug.
i tried to search the doc of pytest-xdist and some google but couldn't find anything.
Do we have any hooks that can be called from conftest to dump after the worker crashes?
or any other way possible? 
Thanks in advance for help and nice tool development.

**Comment by darugnaa** [comment]
You can try with `pytest_handlecrashitem(crashitem: Any, report: Any, sched: Any)` and `pytest_testnodedown(node: Any, error: Any)` hooks. There isn't much documentation about them.

See https://github.com/pytest-dev/pytest-xdist/blob/4d230b6de761bf5143fe21d6e303f6a125b17dc7/src/xdist/newhooks.py#L82
