### ISSUE TITLE
New `LoadScheduling` batch distribution logic doesn't work for long-running tests

### ISSUE THREAD

**Issue by mkoura** [pytest-dev/pytest-xdist#855]
The PR https://github.com/pytest-dev/pytest-xdist/pull/812 that implemented new batch distribution logic (and that is now released in 3.0.2) disregards long-running tests.

I have several modules with long-running tests and many of these tests are now scheduled on single worker, instead of being distributed evenly across multiple workers. As a result, total runtime of my testsuite more than doubled from ~ 2.5 hours to 5+ hours.

Are there any workarounds to bring back the original round-robin scheduling?

cc @amezin

**Comment by mkoura** [comment]
It looks like using the `LoadGroupScheduling` (`--dist loadgroup`) can be used as workaround.

**Comment by amezin** [comment]
Hm... The simplest solution would be to add another scheduler class, derived from LoadScheduling, where initial batch is distributed round-robin.

However, it will help only if your slow tests will fit into that initial batch (although if the difference is so huge - looks like previously they did).

Another option is to significantly change how LoadScheduling works. I have a few ideas, but not sure how they will turn out in reality.

Is the test suite you're talking publicly available?

**Comment by amezin** [comment]
Or, maybe, a more flexible solution: limit size of the chunks of consecutive tests that xdist submits to workers (in ini file and/or CLI argument). Setting it to 1 will effectively mean "round-robin distribution".

**Comment by mkoura** [comment]
@amezin Good idea with the config option.

My testsuite is public - https://github.com/input-output-hk/cardano-node-tests/tree/master/cardano_node_tests/tests
I'm using [pytest-order](https://github.com/pytest-dev/pytest-order) to make sure the long-running tests fit into initial batch.

**Comment by mkoura** [comment]
I've solved this for myself with [custom scheduler](https://github.com/input-output-hk/cardano-node-tests/pull/1542/files#diff-b06ea1c37e005098ecf308b347918e9ca49de38f1d9a4d7a06cc1510e8f9872a). It schedules long-running tests as early as possible while avoiding scheduling long-running tests one after the other (my long-running tests are marked with `pytest.mark.long`).

@amezin The work stealing scheduler is great idea for general purpose scheduler.

The issue can be closed if you don't want to track my usecase.

**Comment by amezin** [comment]
@mkoura out of curiosity, could you disable reordering workarounds, and try pytest-xdist `master` branch with `--dist worksteal`?

**Comment by nicoddemus** [comment]
Btw @amezin, feel free to kick off a new release if you would like to try it (see [`RELEASING.rst`](https://github.com/pytest-dev/pytest-xdist/blob/master/RELEASING.rst)).
