### ISSUE TITLE
Disabling random scheduling; preserve test order as collected

### ISSUE THREAD

**Issue by yuanagain** [pytest-dev/pytest-xdist#860]
Hi, I'm working with a test suite with highly heteregeneous (and often long--a few tests take over an hour) run times and I'm finding that because of how `pytest-xdist` randomly assigns tests to nodes, a few long tests are often being assigned to the same node--resulting in very long run times for the overall test suite.

Is there an option to disable this behavior? I'm considering two approaches, neither of which feels especially elegant:

1) For N workers, use N mutually exclusive markers (i.e. `pytest.mark.xdist_group_2`) via `item.add_marker` post-collection.

2) Find where the randomization occurs, then overload or patch said function

**Comment by nicoddemus** [comment]
Hi,

I would go with 1 and [`--dist loadgroup`](https://pytest-xdist.readthedocs.io/en/latest/distribution.html).

**Comment by yuanagain** [comment]
Sounds good, thanks

**Comment by amezin** [comment]
@yuanagain could you try pytest-xdist `master` branch with `--dist worksteal`?
