### ISSUE TITLE
"Pin" certain parameters to a process?

### ISSUE THREAD

**Issue by s-m-e** [pytest-dev/pytest-xdist#861]
I have a bunch of tests (all in one project) following pretty much the same pattern:

```python
import pytest

@pytest.mark.parametrize("foo", ["a", "b"])  # pin those permutations to one process?
@pytest.mark.parametrize("bar", ["c", "d"])
def test_something(foo: str, bar: str):
    pass
```

I'd like to parallelize them - but, if possible, I'd like "to pin" all permutation associated with one specific parameter to one process. In the above example, let's say `foo` is pinned, then one process could work through `('a', 'c')` and `('a', 'd')` while the other process could work through `('b', 'c')` and `('b', 'd')`. All variations with `foo == "a"` happen in one process, all variations with `foo == "b"` can potentially happen in another (single) process.

This is where I was hoping I could pin a parameter to a process. Is something like this possible or conceivable in some way, shape or form?

--- 

For context, my tests are heavily built on top of `ctypes` which is, for better or for worse, not entirely stateless as I have recently discovered. I.e. if I do something stupid with it, a completely unrelated test (many tests later) might crash. The exact behavior depends on the version of CPython (and on 32 bit Wine & Windows on a DLL's calling convention), but all from at least 3.7 to 3.11 have those hidden states of some form. The only good news is that this behavior can be reproduced if all tests run in the exact same order within a single process.

I am working on [zugbruecke](https://github.com/pleiszenburg/zugbruecke), a `ctypes` drop-in replacement that allows to call Windows DLLs from Unix-like systems or, in other words, a fancy RPC layer between a Unix process and a Wine process. The test suite can be found [here](https://github.com/pleiszenburg/zugbruecke/tree/master/tests). An original test looks as follows:

```python
@pytest.mark.parametrize("arch,conv,ctypes,dll_handle", get_context(__file__))
def test_int_with_size_without_pointer(arch, conv, ctypes, dll_handle):
    """
    Test simple int passing with size
    """

    sqrt_int = dll_handle.sqrt_int
    sqrt_int.argtypes = (ctypes.c_int16,)
    sqrt_int.restype = ctypes.c_int16

    assert 3 == sqrt_int(9)
```

`arch` can either be `win32` or `win64` (for 32 bit and 64 bit DLLs). `conv` can be `cdll` or `windll` (only relevant for 32 bit DLLs). `ctypes` represents my drop-in-replacement backed by different versions of CPython on top of Wine. `dll_handle` is just a `ctypes`-like handle to a DLL. The `ctypes` parameter would need to be pinned.

The test suite currently has 1.6k tests running anywhere from 10 to 40 minutes (single process), depending on the hardware underneath.

**Comment by nicoddemus** [comment]
Hi,

Check out [`--dist loadgroup`](https://pytest-xdist.readthedocs.io/en/latest/distribution.html), you might be able to make it work, if not I think you will need to implement a custom scheduler.
