### ISSUE TITLE
when running on multiple nodes all tests are running on all nodes

### ISSUE THREAD

**Issue by vedarthk** [pytest-dev/pytest-xdist#87]
I tried running with multiple nodes and also with single node then I observed that number of tests running on single node are same as the number of tests running on individual nodes (while running on 2 nodes).

Following is the output for multiple nodes:
```
========================================================= test session starts =========================================================
platform linux2 -- Python 2.7.6, pytest-3.0.1, py-1.4.31, pluggy-0.3.1
rootdir: /opt/app, inifile: pytest.ini
plugins: django-2.8.0, xdist-1.15.0, rage-0.1
gw0 [4770] / gw1 [4770]errors
scheduling tests via LoadScheduling
```

And following is for single node:
```
========================================================= test session starts =========================================================
platform linux2 -- Python 2.7.6, pytest-3.0.1, py-1.4.31, pluggy-0.3.1
rootdir: /opt/app, inifile: pytest.ini
plugins: django-2.8.0, xdist-1.15.0, rage-0.1
gw0 [4770] 0 items / 1 errors
scheduling tests via LoadScheduling
```

is there anything I am missing while executing the tests ?

**Comment by nicoddemus** [comment]
That's how xdist works: all workers collect all tests, which are then sent to master. The master then is responsible to send tests ids for to each worker to run.

Closing this for now, feel free to follow up with other questions.

**Comment by vedarthk** [comment]
@nicoddemus I am facing a problem while creating indexes in elasticsearch in my tests. I am creating indexes based on process ids and I observed that same test is running on both nodes which causes the index to be deleted in between. 

Is there any better way to handle data stores while running tests with xdist ?

**Comment by nicoddemus** [comment]
At which point are you creating the indexes? Can you show some example code?
