### ISSUE TITLE
Changes to implement work stealing scheduler not included in a release

### ISSUE THREAD

**Issue by cpnat** [pytest-dev/pytest-xdist#874]
Hello all,

I have recently been looking into the workstealing scheduler implemented here https://github.com/pytest-dev/pytest-xdist/pull/862.

This has not be included in a release yet, although the docs have been updated. Are you able to give any update when you think a new release might be?

**Comment by cpnat** [comment]
@amezin - wow, what a quick response. Thank you so much!

**Comment by amezin** [comment]
> This has not be included in a release yet, although the docs have been updated.

BTW @nicoddemus @RonnyPfannschmidt is it correct? Shouldn't readthedocs show docs for the latest release, not `master` branch, by default?

Otherwise unavailable (not yet released) CLI switches/options will confuse users. It would definitely be confusing for me as a user.

**Comment by RonnyPfannschmidt** [comment]
Sounds like we need fix the config

**Comment by nicoddemus** [comment]
I just changed the default version to `stable`, should be good now.
