### ISSUE TITLE
xdist seems to be incompatible with the 'sure' matcher library

### ISSUE THREAD

**Issue by rogueleaderr** [pytest-dev/pytest-xdist#90]
I'm using pytest (v 3.0.3) for a project and my tests are running slow so I wanted to try speeding them up with xdist (v.1.15). I'm using Python 3.5.2.

When I run

`python -m pytest -n 1 test --max-slave-restart=0`

The slave crashes with this error:

```
 File "/Users/gjlondon/anaconda/envs/falcon_spike/lib/python3.5/site-packages/xdist/slavemanage.py", line 308, in process_from_remote
    rep = unserialize_report(eventname, kwargs['data'])
  File "/Users/gjlondon/anaconda/envs/falcon_spike/lib/python3.5/site-packages/xdist/slavemanage.py", line 327, in unserialize_report
    return runner.TestReport(**reportdict)
TypeError: __init__() missing 1 required positional argument: 'when'
```

I started creating a minimal failing example project and everything worked, until I installed and included the matcher library I'm using, which is called [sure](https://github.com/gabrielfalcao/sure).

I'm not sure why the failure is happening (I know sure does a lot monkey patching magic, but it's a pretty useful library for creating human-readable tests). But the crash seems to happen in xdist code so I figured I'd post the issue here. I'd really like to use xdist but I've probably got too much `sure` code in my tests to remove 😢 

Here's a link to a minimal failing example: https://github.com/rogueleaderr/xdist_sure

**Comment by rogueleaderr** [comment]
(I cross-posted the issue in the `sure` repo: https://github.com/gabrielfalcao/sure/issues/127)

**Comment by RonnyPfannschmidt** [comment]
seems like sure breaks something pretty deep inside pytest-xdist
at first glance it seems to beentirely the fault of sure - after all it looks like it is patching builtin classes

**Comment by timofurrer** [comment]
I've fixed this bug with https://github.com/gabrielfalcao/sure/pull/129 and I'll release asap a new version of sure. Thanks! :beers:

**Comment by nicoddemus** [comment]
Many thanks @timofurrer for letting us know! 

I'm closing this issue then.
