### ISSUE TITLE
Proposal for new feature: xdist_parallel_parametrize

### ISSUE THREAD

**Issue by eliax1996** [pytest-dev/pytest-xdist#903]
One of the project that I'm working on heavily rely on the `pytest.mark.parametrize` marker in our end-to-end tests to define a set of parameters for the test.
We currently run our test suite with `--dist loadfile`, which works well for most of our test suite, but we would like to run our e2e tests in parallel with different parameters.

An example of a typical test that requires a long time to finish is the following:

```python
@pytest.mark.parametrize(
    "my_cluster_version", [VERSION_1,VERSION_2,VERSION_3]
)
def test_my_e2e_awesome_system(my_cluster_version: ClusterVersion):
   my_cluster = spawn_my_cluster(my_cluster_version)
   stuff_done = my_cluster.do_stuff()
   assert stuff_done == expected_behaviour
``` 

I propose a new tag, `xdist_parallel_parametrize`, which would allow us to run tests with different parameters in parallel. Here's an example of how it could work:

```python
@pytest.mark.xdist_parallel_parametrize(
    "my_cluster_version", [VERSION_1,VERSION_2,VERSION_3]
)
def test_my_e2e_awesome_system(my_cluster_version):
   my_cluster = spawn_my_cluster(my_cluster_version)
   stuff_done = my_cluster.do_stuff()
   assert stuff_done == expected_behaviour
```

Would it be possible to implement this feature? If so, could a core contributor provide guidance on the high-level design? I'm willing to contribute and open a pull request.

**Comment by RonnyPfannschmidt** [comment]
The initial considerations for this have been to send over details on fixture parameter ids and scopes to enable affinity

There has not been any practical design work on this

**Comment by RonnyPfannschmidt** [comment]
@eliax1996 instead of a new concept, I'd like to focus on communication of fixture parameters and scopes

Session scope parameters can be used for scheduling decisions

Collection should not differ between nodes

**Comment by eliax1996** [comment]
Thank you for your reply @RonnyPfannschmidt.

> @eliax1996 instead of a new concept, I'd like to focus on communication of fixture parameters and scopes
> Session scope parameters can be used for scheduling decisions

Wdym? Are you suggesting to transform the `@pytest.mark.parametrize` into a fixture and use some existing feature to transform the N run into N different jobs that could be scheduled differently enabling the concurrent execution of the different cases?

> Collection should not differ between nodes

In the previous message obviously I was meaning that this new step is shared between all the nodes, such that the final list would be the same for every node.

**Comment by RonnyPfannschmidt** [comment]
Parametrize and fixture parameters use the same mechanism

`parametrize("mybackend",..., scope="session"` should be a used to figure scheduling affinity instead of a new marker

**Comment by eliax1996** [comment]
Thank you for your suggestion. If I understand correctly, the idea is to use the existing parametrize mechanism with a scope="session" to create a fixture that has a scoped session, and based on the id of the worker, filter out a subset of parameters in order to execute a subset of tests (even no test for certain workers if for e.g. the parameters are 2 and the workers are 5).

This sounds like a feasible approach, but I am not sure how to integrate it with the scheduling mechanism. Could you please provide some guidance on how to implement this in a way that works with the current scheduling mechanism?

(And also, can you confirm, did I correctly understood the suggestion or did I simplified/misunderstood the suggestion?

**Comment by RonnyPfannschmidt** [comment]
There would not be any filtering

Just that the scheduler would take a look at parameter scopes and ids to pick the worker node for a test

**Comment by RonnyPfannschmidt** [comment]
@eliax1996 each parameter variation of parameterize is collected as separate test

**Comment by RonnyPfannschmidt** [comment]
aka

```
@pytest.mark.parametrize("var", [1,2,3], scope="session")
def test_multiple(var): pass
```
would collect 3 tests

**Comment by eliax1996** [comment]
Thank you 😄 now I have enough info to investigate and play a little bit with the scheduler.

Probably I would modify a little bit the `src/xdist/scheduler/loadfile.py` scheduler and I will write a piece of doc on how to enable/disable this scheduling "feature".

Thank you a lot for the knowledge sharing @RonnyPfannschmidt

**Comment by eliax1996** [comment]
I left the comment here as a guide for anyone that is facing a similar problem.
I think we can close the issue with that
