### ISSUE TITLE
Implement running tests in parallel using fork

### ISSUE THREAD

**Issue by cool-RR** [pytest-dev/pytest-xdist#91]
I'd like to have my tests run in parallel, but the default `subprocess` use is not good for me. I want to use fork, hopefully using the stdlib `multiprocessing.Process`. This is because there are a few global items I define that I want to be shared across all tests, and with forking they'll be shared but not with a new process.

**Comment by RonnyPfannschmidt** [comment]
this is plainly impossible wit the pytest parallel model,
the parallel processes get started *before* it imports tests so you cant share data that way to begin with
