### ISSUE TITLE
Allow for a worker time to live option

### ISSUE THREAD

**Issue by kingbuzzman** [pytest-dev/pytest-xdist#911]
Debugging hanging tests are a real pain in the behind.

It would be nice to specify an option for a TTL for a test worker, and if the test takes longer than the TTL is, automatically kill the process and report on the failure. (optional: start another worker to maintain the number of workers to the `-n` specified amount)

Use case:
I have a 30 minute timeout on github actions, and a test if failing for finish within the allotted time, and all i get back is "Error: The operation was canceled." -- not the most helpful. On the flip side, if allowed to run longer it would not finish by the time my nonexistent children, have children of their own.

If I can put a timeout on the worker running the test to die after 1-2 minutes (being SUPER generous) I would at least be able to trace the issue.

**Comment by nicoddemus** [comment]
Hi @kingbuzzman ,

At work we have this same problem, and we use [`pytest-timeout`](https://pypi.org/project/pytest-timeout/) to handle it.

**Comment by nicoddemus** [comment]
Closing for now, feel free to follow up with further questions.
