### ISSUE TITLE
Test methods with threads using xdist

### ISSUE THREAD

**Issue by ageneralova** [pytest-dev/pytest-xdist#916]
Hi, guys
I'm trying to use xdist to parallel tests in out project. But there is an issue that one of the tests runs forever\hangs up. 
Our project is not usual backend, it is a huge script with threads inside. I have a hypothesis that this test hangs up because it invokes the whole script, not a part of it, where threads exist. 
Do you know some limitations about testing threads with xdist?
Could it be that there is some conflict between parallelization of xdist and parallelization (threading) inside of invoked method in test?
Could you advise sth (besides refactoring of the project)? Maybe there is some settings of xdist that could resolve the problem?

Thank you,
Tasya

**Comment by nicoddemus** [comment]
Shouldn't really be a problem, as each worker is its own process, and each process is free to run as many threads as they want.

Some suggestions/questions:

1. Does the test suite run to completion without using xdist?
2. You can use pytest-timeout to kill the worker after X seconds -- when this happens, it will dump a traceback, which might give a clue why that particular test is hanging.

**Comment by ageneralova** [comment]
1. Yes
2. Added pytest-timeout according to your advice.

Thank you for your time!
Seems it was sth on CI side.
