### ISSUE TITLE
Appium tests are not running in distributed mode across the multiple devices

### ISSUE THREAD

**Issue by Mayur5712** [pytest-dev/pytest-xdist#921]
I am trying to integrate appium tests using pytest and xdist. My requirement is I want to distribute my tests across the multiple devices. I tried below code but still xdist is executing every test case on all the devices. I wanted to execute different test cases on different devices. 

Please find below code I have used

`import pytest
from appium import webdriver

DEVICES = [
    {"platformName": "Android", "deviceName": "device1", "udid": "device1-udid", "appPackage": "com.example.app"},
    {"platformName": "Android", "deviceName": "device2", "udid": "device2-udid", "appPackage": "com.example.app"},
]

@pytest.fixture(scope="session", params=DEVICES)
def appium_driver(request):
    desired_caps = request.param
    driver = webdriver.Remote("http://localhost:4723/wd/hub", desired_caps)
    yield driver
    driver.quit()

def test_login(appium_driver):
    pass`

def test_login2(appium_driver):
    pass`

def test_login3(appium_driver):
    pass`

Please guide on this.

**Comment by RonnyPfannschmidt** [comment]
As no details where provided on how the tests were executed I'm closing this as not actionable
