### ISSUE TITLE
Allow staggering workers startup

### ISSUE THREAD

**Issue by xmo-odoo** [pytest-dev/pytest-xdist#924]
This is a bit of a specific need, but I've got a large test suite which does a fair amount of IO, as a result a lot of test walltime is spent idling.

To get better utilisation out of walltime (at a cost in efficiency) I can crank up the number of workers (16, for a 4c/8t machine, turns out pretty good).

*However* the session setup phase is a lot more CPU-heavy (a lot of work is done there to save time later), having 16 workers all boot at the same time and go through this make using the machine difficult as last-minute load average climbs to 18 for several minutes, which makes the machine rather unresponsive.

Being able to delay worker startup in order to stagger them a bit would likely reduce or avoid the overload, at a cost in runtime (walltime), but hopefully nowhere near lowering the number of workers to machine limits (4/8).

**Comment by RonnyPfannschmidt** [comment]
the details of setup cost/running is unclear here

please outline the actual use-case to determine the scope of the details

**Comment by RonnyPfannschmidt** [comment]
So a semaphore could already solve the contention problem?

**Comment by RonnyPfannschmidt** [comment]
Currently no supporting semaphore Implementation is available

But a semaphore is way simpler than other potential solution's

**Comment by RonnyPfannschmidt** [comment]
One Big lock is easily possible and documented as pattern in the docs

**Comment by RonnyPfannschmidt** [comment]
Glad it worked out,sometimes the x-y problem hits us hard in our own head,
