### ISSUE TITLE
Groupping in different files doesn't run sequentially

### ISSUE THREAD

**Issue by snps-marcelob** [pytest-dev/pytest-xdist#945]
Hello,

xdist_group doesn't seem to create groups in different files. For example,  if I have two files test_file1.py and test_file2.py.

In test_file1 I have the content:

```python
@pytest.mark.xdist_group(name="foo_group")
def test_file1_function() -> None:
   ....
``` 

In test_file2 I have the content:

```python
@pytest.mark.xdist_group(name="foo_group")
def test_file2_function() -> None:
   ....
``` 
In my tests, it doesn't run these two tests sequentially. I didn't see signaling that it didn't work in different files. It is possible to have groups in different files? If no, is there any alternative?

Thanks for your attention 😄 ,
jmmb

**Comment by petacz** [comment]
Hi @snps-marcelob,

Are you running with "--dist loadgroup"?

**Comment by snps-marcelob** [comment]
Yes, but I stopped using it because I was having issues with some tests. Thank you
