### ISSUE TITLE
pytest-xdist 3.3.1 hangs on while running test in pytest

### ISSUE THREAD

**Issue by TestMagic0989** [pytest-dev/pytest-xdist#964]
initialized: 2/2 workersINFO:root:Skipping screenshot: Feature is disabled by default.
ready: 1/2 workers      INFO:root:Skipping screenshot: Feature is disabled by default.
ready: 2/2 workers
but it does not run any test and stops right here used command to run below:
pytest -n 2 --tags tagname

**Comment by TestMagic0989** [comment]
issue resolved

**Comment by gova-i267** [comment]
I have the same problem now.

pytest-xdist==3.5.0
