### ISSUE TITLE
Test execution hangs on Linux, OSX fine

### ISSUE THREAD

**Issue by marscher** [pytest-dev/pytest-xdist#97]
Hi,
when we execute our testsuite with xdist -n2 the tests deterministically hang during the execution of a test involving the multiproccessing module (joblib). However this only happens on Travis Linux docker, but not on Travis OSX workers.

Example "failure" on Linux:
https://travis-ci.org/markovmodel/PyEMMA/jobs/175502853#L1709

Can you please give me any hint, what could be wrong here?

**Comment by marscher** [comment]
Sorry, the "hang" was caused by specifying the number of jobs as the physical cpu count in a docker container, where the host system is under heavy load (travis).

**Comment by RonnyPfannschmidt** [comment]
i see, container are indeed painful that way because they dont see a revised proc usually
