### ISSUE TITLE
 Increase test completion counter

### ISSUE THREAD

**Issue by MaxoH4uk** [pytest-dev/pytest-xdist#977]
Hi!

In the pytest_runtest_makereport hook I get the result of the test execution - successful, failed or skipped.
At the moment, so that there are no problems when starting with n > 1, I have implemented an increase in the counter through file locking.
Is there any other way to do this? For example, so that all processes have a common dictionary in which the counter will be incremented?

**Comment by RonnyPfannschmidt** [comment]
It's not quite clear what you are asking for,

A completion counter would typically be implemented on the coordinator,thus no multiprocess handling would be needed

**Comment by MaxoH4uk** [comment]
> It's not quite clear what you are asking for,
> 
> A completion counter would typically be implemented on the coordinator,thus no multiprocess handling would be needed

I have an application on FastAPI.

Essentially, this is an add-on for running autotests.

There is also a plugin like this: https://stackoverflow.com/questions/72277284/retrieve-pytest-results-programmatically-when-run-via-pytest-main

I would like to update the information in the database after each test completed.

I need a counter that will increment passed/failed/skipped and completed tests.
